// src/app/components/file-upload.tsx
import { useRef, useState, type DragEvent } from 'react';
import { track } from 'app/analytics/analytics';
import './file-upload.css';

export const DEFAULT_FILE_EXT = 'jpg, jpeg, gif, png, bmp, doc, docx, xls, xlsx, ppt, pptx, pdf, txt, rtf';

interface FileUploadProps {
  fileExt?: string;
  maxFiles?: number;
  /** Per-file limit, in MB. */
  maxSize?: number;
  /** Files already attached. Counted against `maxFiles` and echoed back with every change. */
  files?: File[];
  showList?: boolean;
  onFilesChange: (files: File[]) => void;
}

export function FileUpload({
  fileExt = DEFAULT_FILE_EXT,
  maxFiles = 15,
  maxSize = 10,
  files = [],
  showList = true,
  onFilesChange
}: FileUploadProps) {
  const [dragDropClass, setDragDropClass] = useState('dragarea');
  const [errors, setErrors] = useState<string[]>([]);
  const inputRef = useRef<HTMLInputElement>(null);

  function validate(fileList: File[]): string[] {
    const found: string[] = [];

    if (maxFiles > 0 && fileList.length + files.length > maxFiles) {
      found.push('Too many files');
    }

    if (fileExt.length > 0) {
      const extensions = fileExt.split(',').map(x => x.toUpperCase().trim());
      for (const file of fileList) {
        const ext = file.name.toUpperCase().split('.').pop() || file.name;
        if (!extensions.includes(ext)) {
          found.push('Invalid extension: ' + file.name);
        }
      }
    }

    if (maxSize > 0) {
      for (const file of fileList) {
        // rounded to 2 decimal places, so a file a few bytes over the limit still passes
        const size = Math.round((file.size / 1024 / 1024) * 100) / 100;
        if (size > maxSize) {
          found.push('File too large: ' + file.name);
        }
      }
    }

    return found;
  }

  function addFiles(fileList: FileList, method: 'drag_drop' | 'browse') {
    const added = Array.from(fileList);
    const found = validate(added);
    setErrors(found);

    if (found.length > 0) {
      setTimeout(() => setErrors([]), 5000);
      track('File Upload Failed', {
        file_count: added.length,
        upload_method: method,
        error_count: found.length,
        errors: found
      });
      return;
    }

    const totalSize = added.reduce((sum, file) => sum + file.size, 0);
    track('File Upload Attempted', {
      file_count: added.length,
      total_size_mb: Math.round((totalSize / 1024 / 1024) * 100) / 100,
      upload_method: method
    });
    onFilesChange([...files, ...added]);
  }

  function removeFile(file: File) {
    setErrors([]);
    track('File Upload Removed', {
      file_name: file.name,
      file_size_mb: Math.round((file.size / 1024 / 1024) * 100) / 100
    });
    onFilesChange(files.filter(item => item !== file));
  }

  function setDrag(event: DragEvent, className: string) {
    event.preventDefault();
    setDragDropClass(className);
  }

  return (
    <>
      <div
        draggable="true"
        className={dragDropClass + ' dragDropStyling'}
        onDragOver={event => setDrag(event, 'droparea')}
        onDragEnter={event => setDrag(event, 'droparea')}
        onDragEnd={event => setDrag(event, 'dragarea')}
        onDragLeave={event => setDrag(event, 'dragarea')}
        onDrop={event => {
          setDrag(event, 'dragarea');
          event.stopPropagation();
          if (event.dataTransfer?.files) {
            addFiles(event.dataTransfer.files, 'drag_drop');
          }
        }}
      >
        <div className="row">
          <div className="col-md-12 text-center">
            <a
              href="#"
              onClick={event => {
                event.preventDefault();
                inputRef.current?.click();
              }}
            >
              <i className="material-icons">file_upload</i>
              Drop files to attach, or browse.
              <br />
            </a>
            <span className="fileInfo">
              Accepted file types: {fileExt}
              <br />
              Individual file size limit: {maxSize}MB
            </span>
            <input
              type="file"
              ref={inputRef}
              multiple={maxFiles > 1}
              // Clearing on click lets the same file be picked twice in a row.
              onClick={event => {
                (event.target as HTMLInputElement).value = '';
              }}
              onChange={event => {
                if (event.target.files) {
                  addFiles(event.target.files, 'browse');
                }
              }}
              style={{ display: 'none' }}
            />
          </div>
        </div>
      </div>

      {showList && files.length > 0 && (
        <div className="files-list">
          <ul>
            {files.map(f => (
              <li key={f.name}>
                <span className="name">{f.name}</span>
                <span className="value">
                  <button type="button" className="btn btn-danger btn-xs" onClick={() => removeFile(f)} title="Remove this file">
                    <i className="material-icons">clear</i>
                    <span>Remove</span>
                  </button>
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {errors.length > 0 && (
        <div className="errors-list">
          <ul>
            {errors.map(err => (
              <li key={err}>
                <i className="material-icons">error</i>&nbsp;{err}
              </li>
            ))}
          </ul>
        </div>
      )}
    </>
  );
}

// src/app/file-upload/file-upload.component.ts
import { Component, input, output, signal, inject } from '@angular/core';
import { AnalyticsService } from '../services/analytics/analytics.service';


@Component({
  selector: 'app-file-upload',
  imports: [],
  templateUrl: './file-upload.component.html',
  styleUrls: ['./file-upload.component.css'],
  host: {
    '(dragover)': 'onDragOver($event)',
    '(dragenter)': 'onDragEnter($event)',
    '(dragend)': 'onDragEnd($event)',
    '(dragleave)': 'onDragLeave($event)',
    '(drop)': 'onDrop($event)'
  },
})
export class FileUploadComponent {
  private analytics = inject(AnalyticsService);
  
  dragDropClass = signal('dragarea');
  
  fileExt = input<string>('jpg, jpeg, gif, png, bmp, doc, docx, xls, xlsx, ppt, pptx, pdf, txt, rtf');
  maxFiles = input<number>(15);
  maxSize = input<number>(10); // in MB
  files = input<File[]>([]);
  showInfo = input<boolean>(true);
  showList = input<boolean>(true);
  
  filesChange = output<File[]>();
  
  errors = signal<string[]>([]);

  private currentFiles: File[] = [];

  onDragOver(event: DragEvent) {
    this.dragDropClass.set('droparea');
    event.preventDefault();
  }

  onDragEnter(event: DragEvent) {
    this.dragDropClass.set('droparea');
    event.preventDefault();
  }

  onDragEnd(event: DragEvent) {
    this.dragDropClass.set('dragarea');
    event.preventDefault();
  }

  onDragLeave(event: DragEvent) {
    this.dragDropClass.set('dragarea');
    event.preventDefault();
  }

  onDrop(event: DragEvent) {
    this.dragDropClass.set('dragarea');
    event.preventDefault();
    event.stopPropagation();
    if (event.dataTransfer?.files) {
      this.addFiles(event.dataTransfer.files, 'drag_drop');
    }
  }

  onFileChange(event: Event) {
    const target = event.target as HTMLInputElement;
    if (target.files) {
      this.addFiles(target.files, 'browse');
    }
  }

  addFiles(fileList: FileList, method: 'drag_drop' | 'browse' = 'browse') {
    this.errors.set([]); // clear previous errors
    this.currentFiles = [...this.files()];

    if (this.isValidFiles(fileList)) {
      const totalSize = Array.from(fileList).reduce((sum, file) => sum + file.size, 0);
      
      // Track file upload attempt
      this.analytics.track('File Upload Attempted', {
        file_count: fileList.length,
        total_size_mb: Math.round((totalSize / 1024 / 1024) * 100) / 100,
        upload_method: method
      });
      
      for (const file of Array.from(fileList)) {
        this.currentFiles.push(file);
      }
      this.filesChange.emit(this.currentFiles);
    } else {
      // Track validation errors
      this.analytics.track('File Upload Failed', {
        file_count: fileList.length,
        upload_method: method,
        error_count: this.errors().length,
        errors: this.errors()
      });
    }
  }

  removeFile(file: File) {
    this.errors.set([]); // clear previous errors
    this.currentFiles = [...this.files()];

    const index = this.currentFiles.indexOf(file);
    if (index !== -1) {
      // Track file removal
      this.analytics.track('File Upload Removed', {
        file_name: file.name,
        file_size_mb: Math.round((file.size / 1024 / 1024) * 100) / 100
      });
      
      this.currentFiles.splice(index, 1);
    }
    this.filesChange.emit(this.currentFiles);
  }

  private isValidFiles(fileList: FileList): boolean {
    if (this.maxFiles() > 0) { this.validateMaxFiles(fileList); }
    if (this.fileExt().length > 0) { this.validateFileExtensions(fileList); }
    if (this.maxSize() > 0) { this.validateFileSizes(fileList); }
    return (this.errors().length === 0);
  }

  private validateMaxFiles(fileList: FileList): boolean {
    if ((fileList.length + this.files().length) > this.maxFiles()) {
      const currentErrors = [...this.errors()];
      currentErrors.push('Too many files');
      this.errors.set(currentErrors);
      setTimeout(() => this.errors.set([]), 5000);
      return false;
    }
    return true;
  }

  private validateFileExtensions(fileList: FileList): boolean {
    let ret = true;
    const extensions = this.fileExt().split(',').map(x => x.toUpperCase().trim());
    for (const file of Array.from(fileList)) {
      const ext = file.name.toUpperCase().split('.').pop() || file.name;
      if (!extensions.includes(ext)) {
        const currentErrors = [...this.errors()];
        currentErrors.push('Invalid extension: ' + file.name);
        this.errors.set(currentErrors);
        setTimeout(() => this.errors.set([]), 5000);
        ret = false;
      }
    }
    return ret;
  }

  private validateFileSizes(fileList: FileList): boolean {
    let ret = true;
    for (const file of Array.from(fileList)) {
      const fileSizeinMB = file.size / 1024 / 1024; // in MB
      const size = Math.round(fileSizeinMB * 100) / 100; // convert up to 2 decimal places
      if (size > this.maxSize()) {
        const currentErrors = [...this.errors()];
        currentErrors.push('File too large: ' + file.name);
        this.errors.set(currentErrors);
        setTimeout(() => this.errors.set([]), 5000);
        ret = false;
      }
    }
    return ret;
  }
}

<div draggable="true" [class]="dragDropClass() + ' dragDropStyling'">
  <div class="row">
    <div class="col-md-12 text-center">
      <a href="javascript:void(0)" (click)="file.click()">
        <i class="material-icons">file_upload</i>
        Drop files to attach, or browse.
        <br>
      </a>
      <span class="fileInfo">Accepted file types: {{fileExt()}}
      <br>
      Individual file size limit: {{maxSize()}}MB</span>
      <input type="file" #file [multiple]="(maxFiles() > 1)" (click)="file.value = ''" value="" (change)="onFileChange($event)" style="display:none" />
    </div>
  </div>
</div>

@if (showList() && files().length > 0) {
  <div class="files-list">
    <ul>
      @for (f of files(); track f.name) {
        <li>
          <span class="name">{{f.name}}</span>
          <span class="value">
            <button type="button" class="btn btn-danger btn-xs" (click)="removeFile(f)" title="Remove this file">
              <i class="material-icons">clear</i>
              <span>Remove</span>
            </button>
          </span>
        </li>
      }
    </ul>
  </div>
}

@if (errors().length > 0) {
  <div class="errors-list">
    <ul>
      @for (err of errors(); track err) {
        <li>
          <i class="material-icons">error</i>&nbsp;{{err}}
        </li>
      }
    </ul>
  </div>
}
