// src/app/contact/contact.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';

import { HeroBannerComponent, HeroBannerAction } from '../shared/hero-banner/hero-banner.component';
import { InfoCardComponent, InfoCardButton } from '../shared/info-card/info-card.component';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [HeroBannerComponent, InfoCardComponent],
  standalone: true
})
export class ContactComponent {
  readonly heroBannerTitle = 'Connect With Us';
  readonly heroBannerDescription = "This website aims to improve transparency of the provincial environmental assessment process, and to provide citizens and stakeholders with access to project data and information. If you are interested in providing us with feedback about your experience using this website, please feel free to send us your feedback.";
  readonly heroBannerActions: HeroBannerAction[] = [
    {
      label: 'Submit your Feedback',
      href: 'mailto:EAO.EPICsystem@gov.bc.ca',
      icon: 'email',
      title: 'Submit your feedback to the Environmental Assessment Office'
    }
  ];

  readonly infoCards = [
    {
      title: 'B.C. Environmental Assessment Office',
      description: 'Please use the <a href="https://dir.gov.bc.ca/gtds.cgi?show=Branch&organizationCode=ENV&organizationalUnitCode=ENVIRON5" target="_blank" rel="noopener">B.C. EAO Government Directory</a> listing to find contact information for specific Environmental Assessment Office staff.',
      icon: 'phone',
      button: {
        text: 'Visit EAO B.C. Government Directory',
        href: 'https://dir.gov.bc.ca/gtds.cgi?show=Branch&organizationCode=ENV&organizationalUnitCode=ENVIRON5',
        target: '_blank',
        rel: 'noopener',
        title: 'Go to the EAO B.C. Government Directory'
      } as InfoCardButton
    },
    {
      title: 'Compliance Oversight',
      description: 'For questions about compliance, or if you have information about possible non-compliance with an environmental assessment certificate, please email <a href="mailto:eao.compliance@gov.bc.ca">eao.compliance@gov.bc.ca</a>.',
      icon: 'email',
      button: {
        text: 'Email EAO Compliance',
        href: 'mailto:eao.compliance@gov.bc.ca',
        title: 'Email us your questions about compliance oversight'
      } as InfoCardButton
    },
    {
      title: 'Report Natural Resource Violations',
      description: 'If you have seen misconduct involving wildlife, ecosystems, heritage sites or natural resources, you can report it at this <a href="http://www2.gov.bc.ca/gov/content/environment/natural-resource-stewardship/natural-resource-law-enforcement/report-natural-resource-violations" target="_blank" rel="noopener">link here</a>.',
      icon: 'report_problem',
      button: {
        text: 'Report a Natural Resource Violation',
        href: 'http://www2.gov.bc.ca/gov/content/environment/natural-resource-stewardship/natural-resource-law-enforcement/report-natural-resource-violations',
        target: '_blank',
        rel: 'noopener',
        title: 'Report a Natural Resource Violation'
      } as InfoCardButton
    }
  ];
}

<div class="hero-banner">
	<div class="container">
		<div class="container-inner">
			<div class="hero-banner__content">
				<h1>Connect with us...</h1>
				<p>This website aims to improve transparency of the provincial environmental assessment process, and to provide citizens and stakeholders with access to project data and information. If you are interested in providing us with feedback about your experience using this website, please feel free to  <a href="mailto:epicsupport.eao@gov.bc.ca" class="inverted-link">send us your feedback</a>.</p>
        <div class="hero-banner__actions-buttons">
          <a class="btn slide-l-btn hero-btn inverted" title="Submit your feedback to the Environmental Assessment Office" href="mailto:epicsupport.eao@gov.bc.ca">
            <i class="material-icons">email</i>
            <span>Submit your Feedback</span>
          </a>
        </div>  
      </div>
		</div>
	</div>
</div>

<section class="container" id="anchor-point">
  <div class="block-container">
    <div class="block">
      <div class="inner-block">
        <span class="icon-container">
          <i class="material-icons">
            phone
          </i>
        </span>
        <h3>B.C. Environmental Assessment Office</h3>
        <p>Please use the <a href="https://dir.gov.bc.ca/gtds.cgi?show=Branch&organizationCode=ENV&organizationalUnitCode=ENVIRON5" target="_blank">B.C. EAO Government Directory</a> listing to find contact information for specific Environmental Assessment Office staff.</p>
      </div>
      <a class="btn content-btn-alt slide-l-btn" title="Go to the EAO B.C. Government Directory" href="https://dir.gov.bc.ca/gtds.cgi?show=Branch&organizationCode=ENV&organizationalUnitCode=ENVIRON5"target="_blank">
        <i class="material-icons">list</i>
        <span>Visit EAO B.C. Government Directory</span>
      </a>
    </div>
    <div class="block">
      <div class="inner-block">
        <span class="icon-container">
          <i class="material-icons">
            email
          </i>
        </span>
        <h3>Compliance Oversight</h3>
        <p>For questions about compliance, or if you have information about possible non-compliance with an environmental assessment certificate, please email <a href="mailto:eao.compliance@gov.bc.ca">eao.compliance@gov.bc.ca</a>.</p>
      </div>
      <a class="btn content-btn-alt slide-l-btn" title="Email us your questions about compliance oversight" href="mailto:eao.compliance@gov.bc.ca">
        <i class="material-icons">email</i>
        <span>Email EAO Compliance</span>
    </a>
    </div>
    <div class="block">
      <div class="inner-block">
        <span class="icon-container">
          <i class="material-icons">
            web
          </i>
        </span>
        <h3>Report Natural Resource Violations</h3>
        <p>If you have seen misconduct involving wildlife, ecosystems, heritage sites or natural resources, you can report it at this <a href="http://www2.gov.bc.ca/gov/content/environment/natural-resource-stewardship/natural-resource-law-enforcement/report-natural-resource-violations" target="_blank">link here</a>.</p>
      </div>
      <a class="btn content-btn-alt slide-l-btn" title="Report a Natural Resource Violation" href="http://www2.gov.bc.ca/gov/content/environment/natural-resource-stewardship/natural-resource-law-enforcement/report-natural-resource-violations" target="_blank">
        <i class="material-icons">report_problem</i>
        <span>Report a Natural Resource Violation</span>
      </a>
    </div>
  </div>
</section>

// src/app/pages/contact.tsx
import { HeroBanner, type HeroBannerAction } from 'app/components/hero-banner';
import { InfoCard, type InfoCardButton } from 'app/components/info-card';

const HERO_TITLE = 'Connect With Us';
const HERO_DESCRIPTION = 'This website aims to improve transparency of the provincial environmental assessment process, and to provide citizens and stakeholders with access to project data and information. If you are interested in providing us with feedback about your experience using this website, please feel free to send us your feedback.';
const HERO_ACTIONS: HeroBannerAction[] = [
  {
    label: 'Submit your Feedback',
    href: 'mailto:EAO.EPICsystem@gov.bc.ca',
    icon: 'email',
    title: 'Submit your feedback to the Environmental Assessment Office'
  }
];

const INFO_CARDS: { title: string; description: string; icon: string; button: InfoCardButton }[] = [
  {
    title: 'B.C. Environmental Assessment Office',
    description: 'Please use the <a href="https://dir.gov.bc.ca/gtds.cgi?show=Branch&organizationCode=ENV&organizationalUnitCode=ENVIRON5" target="_blank" rel="noopener">B.C. EAO Government Directory</a> listing to find contact information for specific Environmental Assessment Office staff.',
    icon: 'phone',
    button: {
      text: 'Visit EAO B.C. Government Directory',
      href: 'https://dir.gov.bc.ca/gtds.cgi?show=Branch&organizationCode=ENV&organizationalUnitCode=ENVIRON5',
      target: '_blank',
      rel: 'noopener',
      title: 'Go to the EAO B.C. Government Directory'
    }
  },
  {
    title: 'Compliance Oversight',
    description: 'For questions about compliance, or if you have information about possible non-compliance with an environmental assessment certificate, please email <a href="mailto:eao.compliance@gov.bc.ca">eao.compliance@gov.bc.ca</a>.',
    icon: 'email',
    button: {
      text: 'Email EAO Compliance',
      href: 'mailto:eao.compliance@gov.bc.ca',
      title: 'Email us your questions about compliance oversight'
    }
  },
  {
    title: 'Report Natural Resource Violations',
    description: 'If you have seen misconduct involving wildlife, ecosystems, heritage sites or natural resources, you can report it at this <a href="http://www2.gov.bc.ca/gov/content/environment/natural-resource-stewardship/natural-resource-law-enforcement/report-natural-resource-violations" target="_blank" rel="noopener">link here</a>.',
    icon: 'report_problem',
    button: {
      text: 'Report a Natural Resource Violation',
      href: 'http://www2.gov.bc.ca/gov/content/environment/natural-resource-stewardship/natural-resource-law-enforcement/report-natural-resource-violations',
      target: '_blank',
      rel: 'noopener',
      title: 'Report a Natural Resource Violation'
    }
  }
];

export function Contact() {
  return (
    <>
      <HeroBanner title={HERO_TITLE} description={HERO_DESCRIPTION} actions={HERO_ACTIONS} />

      <div className="bg-faded">
        <section className="container">
          <div className="feature-cards-container">
            {INFO_CARDS.map(card => (
              <div className="feature-card" key={card.title}>
                <InfoCard title={card.title} description={card.description} icon={card.icon} button={card.button} />
              </div>
            ))}
          </div>
        </section>
      </div>
    </>
  );
}
