// src/app/home/home.component.ts
import { Component, OnInit, OnDestroy, ChangeDetectionStrategy, signal, inject, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

import { SearchService } from 'app/services/search.service';
import { ApiService } from 'app/services/api';
import { LoggingService } from 'app/services/logging.service';
import { News } from 'app/models/news';
import { HeroBannerComponent, HeroBannerAction } from '../shared/hero-banner/hero-banner.component';
import { InfoCardComponent, InfoCardButton } from '../shared/info-card/info-card.component';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrl: './home.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule, RouterModule, HeroBannerComponent, InfoCardComponent],
  standalone: true
})
export class HomeComponent implements OnInit, OnDestroy {
  private searchService = inject(SearchService);
  private apiService = inject(ApiService);
  private logger = inject(LoggingService);
  private destroy$ = new Subject<boolean>();

  results = signal<News[]>([]);
  surveyUrl = signal<string>('');
  showSurveyBanner = signal<boolean>(false);
  loading = signal<boolean>(true);

  readonly heroBannerTitle = 'Environmental Assessments';
  readonly heroBannerDescription = "British Columbia's environmental assessment process provides opportunities for Indigenous Nations, government agencies and the public to influence the outcome of environmental assessments in British Columbia.";
  readonly heroBannerActions: HeroBannerAction[] = [
    {
      label: 'Find Environmental Assessment Projects',
      routerLink: '/projects',
      icon: 'list'
    },
    {
      label: 'List of Projects',
      routerLink: '/projects-list',
      icon: 'list'
    },
    {
      label: 'Project Notifications',
      routerLink: '/project-notifications',
      icon: 'list'
    }
  ];

  readonly aboutCards = [
    {
      title: 'Legislation',
      description: 'Learn about the legislation and regulations that apply to environmental assessments in the province of British Columbia.',
      button: {
        text: 'Learn More',
        link: '/legislation',
        title: 'Learn more about legislation'
      } as InfoCardButton
    },
    {
      title: 'Process & Procedures',
      description: 'Learn more about how the Environmental Assessment Office neutrally administers a process that holds all participants accountable.',
      button: {
        text: 'Learn More',
        link: '/process',
        title: 'Learn more about process and procedures'
      } as InfoCardButton
    },
    {
      title: 'Compliance Oversight',
      description: 'Learn about how we collaborate with other agencies to coordinate oversight of environmental assessment projects.',
      button: {
        text: 'Learn More',
        link: '/compliance-oversight',
        title: 'Learn more about compliance oversight'
      } as InfoCardButton
    }
  ];

  ngOnInit(): void {
    this.loading.set(true);
    this.searchService.getTopNewsItems()
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (res: News[]) => {
          this.results.set(res || []);
          this.loading.set(false);
        },
        error: (err) => {
          this.logger.error('Error loading recent activities', 'HomeComponent', err);
          this.results.set([]);
          this.loading.set(false);
        }
      });

    this.surveyUrl.set(this.apiService.surveyUrl || '');
    this.showSurveyBanner.set(this.apiService.showSurveyBanner);
  }

  ngOnDestroy(): void {
    this.destroy$.next(true);
    this.destroy$.complete();
  }
}

<div class="hero-banner">
  <div class="container">
    <div class="container-inner">
      <div class="hero-banner__content">
        <span tabindex="0">
          <h1>Environmental Assessments</h1>
          <p>
            British Columbia's environmental assessment process provides
            opportunities for Indigenous Nations, government agencies and the
            public to influence the outcome of environmental assessments in
            British Columbia.
          </p>
        </span>
        <div class="hero-banner__actions">
          <div class="hero-banner__actions-buttons">
            <a class="btn slide-l-btn hero-btn inverted" href="/projects" [routerLink]="['/projects']">
              <i class="material-icons">list</i><span>Find Environmental Assessment Projects</span>
            </a>
            <a class="btn slide-l-btn hero-btn inverted" href="/projects-list" [routerLink]="['/projects-list']">
              <i class="material-icons">list</i><span>List of Projects</span>
            </a>
            <a class="btn slide-l-btn hero-btn inverted ml-4" href="/project-notifications"
              [routerLink]="['/project-notifications']">
              <i class="material-icons">list</i><span>Project Notifications</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="survey-banner" *ngIf="showSurveyBanner">
  <div class="container">
    <div class="container-inner">
      <h5>
        Can you take a few minutes to help us improve how we get input from the
        public?
      </h5>
      <div class="survey-content">
        <p>
          We are creating a better way to listen and respond to public feedback
          during the environmental assessment process. Please fill out our short
          5-10 minute survey to help us design a better online platform for
          hearing what you think about projects under review.
        </p>
        <a class="survey-link" href="{{ surveyUrl }}" rel="noopener" target="_blank"
          >Share your thoughts</a
        >
      </div>
    </div>
  </div>
</div>
<main>
  <div id="anchor-point">
    <section class="container">
      <h2 tabindex="0" class="mb-4">Recent Activities & Updates</h2>
      <div class="home-news-feed">
        <table class="table" id="tableTop" *ngIf="results">
          <tbody *ngFor="let item of results">
            <tr *ngIf="item.active == true" tabindex="0">
              <td>
                <div class="title-container">
                  <h3 class="title-container__title">
                    <span class="font-weight-bold" *ngIf="item.project">
                      {{ item.project?.name }}
                    </span>
                    <span *ngIf="item.notificationName" class="font-weight-bold">{{ item.notificationName }}</span>
                    <span class="home-news-feed__headline">{{
                      item.headline
                      }}</span>
                  </h3>
                  <span class="title-container__date">{{
                    item.dateAdded | date: 'longDate'
                    }}</span>
                </div>
                <div>
                  <div class="activity-content" [innerHTML]="item.content"></div>
                </div>
                <div>
                  <a class="btn btn-sm content-btn-alt" title="View more information about {{ item.project.name }}"
                    [routerLink]="['/p', item.project?._id]" *ngIf="item.project?._id">
                    Project Info
                  </a>
                  <a
                    *ngIf="
                      item.pcp &&
                      item.type === 'Public Comment Period' &&
                      (!item.pcp.isMet || !item.pcp.metURL)
                    "
                    class="btn btn-sm content-btn-alt"
                    title="View this Public Comment Period"
                    [routerLink]="['/p', item.project?._id, 'cp', item.pcp._id]"
                  >
                    Submit/ View Comments
                  </a>
                  <a
                    *ngIf="
                      item.pcp &&
                      item.type === 'Public Comment Period' &&
                      item.pcp.isMet &&
                      item.pcp.metURL
                    "
                    class="btn btn-sm content-btn-alt"
                    href="{{ item.pcp.metURL }}"
                    rel="noopener"
                    target="_blank"
                    title="View this Public Comment Period"
                  >
                    Submit/ View Comments
                  </a>
                  <a *ngIf="
                      item.documentUrl &&
                      !item?.documentUrl.includes('docs?folder') &&
                      !item?.notificationName
                    "
                    class="btn btn-sm content-btn-alt"
                    href="{{ item.documentUrl }}"
                    rel="noopener"
                    target="_blank"
                    title="View more information"
                  >
                    View Document(s)
                  </a>
                  <a *ngIf="
                      item.documentUrl &&
                      item?.notificationName &&
                      item?.type ===
                        'Project Notification Public Comment Period'
                    "
                    class="btn btn-sm content-btn-alt"
                    href="{{ item.documentUrl }}"
                    rel="noopener"
                    target="_blank"
                    title="View more information"
                  >
                    View Project Notification Public Comment Period
                  </a>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
        <div class="news-block-more">
          <a class="btn slide-r-btn content-btn-alt" href="/news" [routerLink]="['/news']">
            <span>View All Activities & Updates</span>
            <i class="material-icons">&#xE5C8;</i>
          </a>
        </div>
      </div>
    </section>
    <hr />
    <div class="bg-faded">
      <section class="container">
        <h2 tabindex="0">About the B.C. Environmental Assessment Process...</h2>
        <p tabindex="0">
          Learn more about how the Environmental Assessment Office neutrally
          administers a process that is predictable, transparent, timely,
          procedurally fair, and holds all participants accountable.
        </p>
        <div class="row feature-blocks">
          <div class="col-md-4">
            <div tabindex="0" class="feature-block">
              <h3>Legislation</h3>
              <p>
                Learn about the legislation and regulations that apply to
                environmental assessments in the province of British Columbia.
              </p>
              <a class="btn btn-sm inverted" href="/legislation" [routerLink]="['/legislation']"
                aria-label="Learn more about legislation">Learn More</a>
            </div>
          </div>
          <div class="col-md-4">
            <div tabindex="0" class="feature-block">
              <h3>Process & Procedures</h3>
              <p>
                Learn more about how the Environmental Assessment Office
                neutrally administers a process that holds all participants
                accountable.
              </p>
              <a class="btn btn-sm inverted" href="/process" [routerLink]="['/process']"
                aria-label="Learn more about process and procedures">Learn More</a>
            </div>
          </div>
          <div tabindex="0" class="col-md-4">
            <div class="feature-block">
              <h3>Compliance Oversight</h3>
              <p>
                Learn about how we collaborate with other agencies to coordinate
                oversight of environmental assessment projects.
              </p>
              <a class="btn btn-sm inverted" href="/compliance-oversight" [routerLink]="['/compliance-oversight']"
                aria-label="Learn more about compliance oversight">Learn More</a>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</main>

// src/app/pages/home.tsx
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router';
import { getTopNewsItems } from 'app/api/search';
import { surveyUrl, showSurveyBanner } from 'app/api/api';
import type { News } from 'app/models/news';
import { HeroBanner, type HeroBannerAction } from 'app/components/hero-banner';
import { InfoCard, type InfoCardButton } from 'app/components/info-card';
import { ActivityCard } from 'app/components/activity-card';
import './home.css';

const HERO_TITLE = 'Environmental Assessments';
const HERO_DESCRIPTION = "British Columbia's environmental assessment process provides opportunities for Indigenous Nations, government agencies and the public to influence the outcome of environmental assessments in British Columbia.";
const HERO_ACTIONS: HeroBannerAction[] = [
  { label: 'Find Environmental Assessment Projects', routerLink: '/projects', icon: 'list' },
  { label: 'List of Projects', routerLink: '/projects-list', icon: 'list' },
  { label: 'Project Notifications', routerLink: '/project-notifications', icon: 'list' }
];

const ABOUT_CARDS: { title: string; description: string; button: InfoCardButton }[] = [
  {
    title: 'Legislation',
    description: 'Learn about the legislation and regulations that apply to environmental assessments in the province of British Columbia.',
    button: { text: 'Learn More', link: '/legislation', title: 'Learn more about legislation' }
  },
  {
    title: 'Process & Procedures',
    description: 'Learn more about how the Environmental Assessment Office neutrally administers a process that holds all participants accountable.',
    button: { text: 'Learn More', link: '/process', title: 'Learn more about process and procedures' }
  },
  {
    title: 'Compliance Oversight',
    description: 'Learn about how we collaborate with other agencies to coordinate oversight of environmental assessment projects.',
    button: { text: 'Learn More', link: '/compliance-oversight', title: 'Learn more about compliance oversight' }
  }
];

export function Home() {
  const { data: results = [], isPending } = useQuery<News[]>({
    queryKey: ['topNewsItems'],
    queryFn: getTopNewsItems
  });

  const survey = surveyUrl();
  const showSurvey = showSurveyBanner();

  return (
    <>
      <HeroBanner title={HERO_TITLE} description={HERO_DESCRIPTION} actions={HERO_ACTIONS} />

      <div>
        {showSurvey && survey && (
          <div className="survey-banner">
            <div className="container">
              <div className="d-flex flex-column flex-md-row gap-3">
                <div className="flex-grow-1">
                  <h5 className="mb-3">Can you take a few minutes to help us improve your experience on EPIC?</h5>
                  <p className="mb-0">
                    We are working on some improvements to this website and would like to hear about your experience.
                    Please fill out a short 5-10 minute survey to help us design a better EAO Project Information Centre.
                    Thank you!
                  </p>
                </div>
                <div className="flex-shrink-0">
                  <a className="btn btn-primary survey-link" href={survey} rel="noopener" target="_blank">Share your thoughts</a>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      <main>
        <div id="anchor-point">
          <section className="container">
            <div className="home-news-feed">
              <h2 tabIndex={0}>Recent Activities &amp; Updates</h2>
              {isPending ? (
                <div className="d-flex justify-content-center align-items-center py-5">
                  <div className="spinner-border text-primary" style={{ width: '3rem', height: '3rem' }} role="status">
                    <span className="visually-hidden">Loading...</span>
                  </div>
                </div>
              ) : results.length > 0 ? (
                <table className="table" id="tableTop">
                  {results.filter(item => item.active).map(item => (
                    <tbody key={item._id}>
                      <ActivityCard rowData={item} />
                    </tbody>
                  ))}
                </table>
              ) : null}
              <div className="mt-4 text-center">
                <Link className="btn slide-r-btn btn-outline-primary d-inline-flex align-items-center gap-2" to="/news">
                  <span>View All Activities &amp; Updates</span>
                  <i className="material-icons">&#xE5C8;</i>
                </Link>
              </div>
            </div>
          </section>

          <div className="bg-faded mt-5">
            <section className="container">
              <h2 tabIndex={0}>About the B.C. Environmental Assessment Process</h2>
              <p tabIndex={0}>
                Learn more about how the Environmental Assessment Office neutrally
                administers a process that is predictable, transparent, timely,
                procedurally fair, and holds all participants accountable.
              </p>
              <div className="feature-cards-container">
                {ABOUT_CARDS.map(card => (
                  <div className="feature-card" key={card.title}>
                    <InfoCard title={card.title} description={card.description} button={card.button} />
                  </div>
                ))}
              </div>
            </section>
          </div>
        </div>
      </main>
    </>
  );
}
