// src/app/layout/footer.tsx
import { useEffect, useRef } from 'react';
import { useLocation } from 'react-router';
import { adminUrl } from 'app/api/api';
import './footer.css';

export function Footer({ className = '' }: { className?: string }) {
  const { pathname } = useLocation();
  const footerRef = useRef<HTMLElement>(null);

  useEffect(() => {
    const updateFooterHeight = () => {
      const height = footerRef.current?.offsetHeight;
      if (height) {
        document.documentElement.style.setProperty('--footer-height', `${height}px`);
      }
    };
    updateFooterHeight();
    window.addEventListener('resize', updateFooterHeight);
    return () => window.removeEventListener('resize', updateFooterHeight);
  }, [pathname]);

  return (
    <footer
      ref={footerRef}
      className={`app-footer${pathname.startsWith('/projects') ? ' app-footer--sm' : ''}${className ? ' ' + className : ''}`}
      id="footer"
    >
      <div className="container">
        <div className="footer-admin clearfix">
          <ul className="gov-links">
            <li><a href="#">Home</a></li>
            <li><a href="http://www2.gov.bc.ca/gov/content/home/copyright" target="_blank" rel="noopener">Copyright</a></li>
            <li><a href="http://www2.gov.bc.ca/gov/content/home/disclaimer" target="_blank" rel="noopener">Disclaimer</a></li>
            <li><a href="http://www2.gov.bc.ca/gov/content/home/privacy" target="_blank" rel="noopener">Privacy</a></li>
            <li><a href="http://www2.gov.bc.ca/gov/content/home/accessibility" target="_blank" rel="noopener">Accessibility</a></li>
            <li><a href={adminUrl()} className="gtm-admin-login" target="_blank" rel="noopener">Admin Login</a></li>
          </ul>
        </div>
      </div>
    </footer>
  );
}

// src/app/footer/footer.component.ts
import { Component, ChangeDetectionStrategy, inject, AfterViewInit, OnDestroy, ElementRef, effect } from '@angular/core';

import { Router, RouterModule } from '@angular/router';
import { ApiService } from 'app/services/api';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterModule],
})
export class FooterComponent implements AfterViewInit, OnDestroy {
  public api = inject(ApiService);
  public router = inject(Router);
  private elementRef = inject(ElementRef);
  private resizeListener: () => void;
  private updateFooterHeightTimeoutId: any = null;

  constructor() {
    // Update footer height on route changes
    effect(() => {
      const _url = this.router.url;
      this.updateFooterHeightTimeoutId = setTimeout(() => this.updateFooterHeight(), 0);
    });
    
    // Bind the resize listener so we can remove it later
    this.resizeListener = () => this.updateFooterHeight();
  }

  ngAfterViewInit() {
    this.updateFooterHeight();
    // Also update on window resize
    window.addEventListener('resize', this.resizeListener);
  }

  ngOnDestroy() {
    // Clean up event listener
    window.removeEventListener('resize', this.resizeListener);
    
    // Clear any pending timeout
    if (this.updateFooterHeightTimeoutId) {
      clearTimeout(this.updateFooterHeightTimeoutId);
      this.updateFooterHeightTimeoutId = null;
    }
  }

  private updateFooterHeight() {
    const footerElement = this.elementRef.nativeElement.querySelector('.app-footer');
    if (footerElement) {
      const height = footerElement.offsetHeight;
      document.documentElement.style.setProperty('--footer-height', `${height}px`);
    }
  }
}

<footer class="app-footer" id="footer"
  [class.app-footer--sm]="router.url.startsWith('/projects')">
  <div class="container">
<!--     <div class="footer-info row">
      <div class="col-md-4">
        <section>
          <h4>Navigate</h4>
          <ul class="nav-links">
            <li><a routerLink="/projects">Find Environmental Assessment Projects</a></li>
            <li><a routerLink="/contact">Contact Us</a></li>
          </ul>
        </section>
      </div>
      <div class="col-md-8">
        <section>
          <h4>More Information</h4>
          <p class="mb-0">EPIC</p>
        </section>
      </div>
    </div> -->
    <div class="footer-admin clearfix">
      <ul class="gov-links">
        <li><a href="#">Home</a></li>
        <li><a href="http://www2.gov.bc.ca/gov/content/home/copyright" target="_blank" rel="noopener">Copyright</a></li>
        <li><a href="http://www2.gov.bc.ca/gov/content/home/disclaimer" target="_blank" rel="noopener">Disclaimer</a></li>
        <li><a href="http://www2.gov.bc.ca/gov/content/home/privacy" target="_blank" rel="noopener">Privacy</a></li>
        <li><a href="http://www2.gov.bc.ca/gov/content/home/accessibility" target="_blank" rel="noopener">Accessibility</a></li>
        <li><a [href]="api.adminUrl" class="gtm-admin-login" target="_blank" rel="noopener">Admin Login</a></li>
      </ul>
    </div>
  </div>
</footer>
