// src/app/pages/comments/comments.tsx
import { useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router';
import { useQuery } from '@tanstack/react-query';
import { downloadDocument, searchKeywords } from 'app/api/api';
import * as commentApi from 'app/api/comment';
import * as commentPeriodApi from 'app/api/commentperiod';
import * as documentApi from 'app/api/document';
import * as projectApi from 'app/api/project';
import { logger } from 'app/config/logging';
import { track } from 'app/analytics/analytics';
import type { Comment } from 'app/models/comment';
import type { Document } from 'app/models/document';
import type { Project } from 'app/models/project';
import { showToast } from 'app/state/toast';
import { TableTemplate } from 'app/components/table/table-template';
import { tableObject, type ITableMessage } from 'app/components/table/table-object';
import { mediumDate } from 'app/utils/utils';
import { safeHtml } from 'app/utils/safe-html';
import { AddComment } from './add-comment';
import { CommentsTableRow } from './comments-table-rows';
import './comments.css';

type CommentsType = 'PROJECT' | 'PROJECT-NOTIFICATION';

const COMMENT_PERIOD_HEADERS: Record<string, string> = {
  Closed: 'Public Comment Period is Now Closed',
  Upcoming: 'Public Comment Period is Upcoming',
  Open: 'Public Comment Period is Now Open',
};

/** Project notifications have no project endpoint, so their name comes out of search. */
async function getNotificationProject(projId: string): Promise<Project | null> {
  try {
    const raw = await searchKeywords(
      '',
      'ProjectNotification',
      [],
      1,
      1,
      '',
      '',
      { _id: projId },
      false,
      null,
      {},
      false,
    );
    const hit = (raw as any)?.[0]?.searchResults?.[0];
    return hit ? ({ name: hit.name } as Project) : null;
  } catch {
    // the notification name is non-critical
    return null;
  }
}

async function loadComments(periodId: string, pageNum: number, pageSize: number) {
  const res = await commentApi.getByPeriodId(periodId, pageNum, pageSize, true);
  const comments: Comment[] = res?.currentComments ?? [];

  // Every comment's attachments come back in one request rather than one request per comment.
  const allDocIds: string[] = [];
  comments.forEach((comment) => {
    if (comment.documents && comment.documents.length > 0) {
      // documents arrive as ids or as objects carrying one
      comment.documents = comment.documents.map((doc: any) =>
        typeof doc === 'string' ? doc : doc._id || doc,
      );
      allDocIds.push(...comment.documents);
    }
  });

  if (allDocIds.length > 0) {
    try {
      const docMap = new Map<string, Document>();
      (await documentApi.getByMultiId(allDocIds)).forEach((doc) => {
        if (doc?._id) docMap.set(doc._id, doc);
      });
      comments.forEach((comment) => {
        if (comment.documents) {
          comment.documents = comment.documents.map((id: string) => docMap.get(id)).filter(Boolean);
        }
      });
    } catch (error) {
      logger.error('Error loading documents for comments', 'Comments', error);
      comments.forEach((comment) => {
        if (comment.documents) comment.documents = [];
      });
    }
  }

  return { totalCount: Number(res?.totalCount ?? 0), comments };
}

export function Comments() {
  const { projId, commentPeriodId } = useParams();
  const { pathname } = useLocation();
  const navigate = useNavigate();
  const isProjectNotificationRoute = pathname.includes('/pn/');

  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [modalOpen, setModalOpen] = useState(false);

  const projectQuery = useQuery({
    queryKey: ['comments-project', projId, isProjectNotificationRoute],
    enabled: !!projId,
    queryFn: async (): Promise<{ project: Project | null; type: CommentsType }> => {
      if (!isProjectNotificationRoute) {
        try {
          const project = await projectApi.getById(projId!);
          if (project) return { project, type: 'PROJECT' };
        } catch (error) {
          logger.error('Error loading project', 'Comments', error);
          return { project: null, type: 'PROJECT' };
        }
        logger.warn(`Project ${projId} not found, trying as ProjectNotification`, 'Comments');
      }
      return { project: await getNotificationProject(projId!), type: 'PROJECT-NOTIFICATION' };
    },
  });

  const periodQuery = useQuery({
    queryKey: ['commentPeriod', commentPeriodId],
    enabled: !!commentPeriodId,
    queryFn: () => commentPeriodApi.getById(commentPeriodId!),
  });

  const commentPeriod = periodQuery.data ?? null;
  const project = projectQuery.data?.project ?? null;
  const type: CommentsType =
    projectQuery.data?.type ?? (isProjectNotificationRoute ? 'PROJECT-NOTIFICATION' : 'PROJECT');

  const docsQuery = useQuery({
    queryKey: ['commentPeriodDocs', commentPeriodId],
    enabled: !!commentPeriod?.relatedDocuments?.length,
    queryFn: () => documentApi.getByMultiId(commentPeriod!.relatedDocuments),
  });

  const commentsQuery = useQuery({
    queryKey: ['comments', commentPeriod?._id, page, pageSize],
    enabled: !!commentPeriod?._id,
    queryFn: () => loadComments(commentPeriod!._id, page, pageSize),
    // Keep the table on screen while the next page loads, matching the Angular page, which only
    // showed the big spinner on the first load.
    placeholderData: (previous) => previous,
  });

  useEffect(() => {
    if (!projId || !commentPeriodId) {
      logger.error('Missing route parameters', 'Comments', { projId, commentPeriodId });
      navigate('/projects');
      return;
    }
    if (periodQuery.isError) {
      logger.error('Error loading comment period', 'Comments', periodQuery.error);
      showToast('Failed to load comment period', { duration: 3000, type: 'error' });
      navigate('/projects');
      return;
    }
    if (periodQuery.isSuccess && !periodQuery.data) {
      showToast('Comment period not found', { duration: 3000, type: 'error' });
      navigate('/projects');
    }
  }, [
    projId,
    commentPeriodId,
    periodQuery.isError,
    periodQuery.isSuccess,
    periodQuery.data,
    periodQuery.error,
    navigate,
  ]);

  const tableData = useMemo(
    () =>
      tableObject({
        tableId: 'comments',
        component: CommentsTableRow,
        options: {
          showPageCountDisplay: true,
          showPagination: true,
          showPageSizePicker: true,
          showTopControls: true,
          showHeader: false,
          disableRowHighlight: true,
        },
        currentPage: page,
        pageSize,
        totalListItems: commentsQuery.data?.totalCount ?? 0,
        items: (commentsQuery.data?.comments ?? []).map((comment) => ({ rowData: comment })),
      }),
    [page, pageSize, commentsQuery.data],
  );

  function onMessageOut(msg: ITableMessage) {
    if (msg.label === 'pageNum') {
      setPage(msg.data);
    } else if (msg.label === 'pageSize') {
      setPageSize(Number(msg.data.value));
      setPage(1);
    }
  }

  function onDownloadDocument(doc: Document) {
    downloadDocument(doc)
      .then(() => showToast('Downloading document', { duration: 2000, type: 'info' }))
      .catch(() =>
        showToast('Error opening document! Please try again later', {
          duration: 2000,
          type: 'error',
        }),
      );
  }

  function goBackToProjectDetails() {
    if (type === 'PROJECT' && project) {
      navigate(`/p/${project._id}`);
    } else {
      navigate('/project-notifications');
    }
  }

  function onModalDismiss(reason: string, modalPage: number) {
    setModalOpen(false);
    logger.debug('Modal cancelled', 'Comments', { reason });
    if (project) {
      track('Comment Modal Dismissed', {
        project_id: project._id,
        project_name: project.name,
        comment_period_id: commentPeriod?._id,
        page: modalPage,
        reason,
      });
    }
  }

  const commentPeriodDocs = docsQuery.data ?? [];
  const commentPeriodHeader = commentPeriod
    ? COMMENT_PERIOD_HEADERS[commentPeriod.commentPeriodStatus] || ''
    : '';
  const pageLoading = !commentPeriod || (type === 'PROJECT' && projectQuery.isPending);

  return (
    <>
      <div className="project">
        <main className="project-info">
          <div className="hero-banner-alt">
            <div className="container">
              <div className="hero-banner__content">
                {pageLoading ? (
                  <div className="d-flex justify-content-center align-items-center py-5">
                    <div className="spinner-border" role="status">
                      <span className="visually-hidden">Loading...</span>
                    </div>
                  </div>
                ) : (
                  <>
                    <h1>{project?.name || '-'}</h1>

                    {commentPeriod._id && (
                      <>
                        <h2>{commentPeriodHeader || '-'}</h2>
                        <h2>
                          {mediumDate(commentPeriod.dateStarted)} -{' '}
                          {commentPeriod.longEndDate.toFormat('MMMM dd @ hh:mm a ZZZZ')}
                        </h2>
                        <hr className="comment-period-divider" />

                        <div className="header-section">
                          <div>
                            <div
                              id="instructions"
                              dangerouslySetInnerHTML={safeHtml(
                                String(commentPeriod.instructions ?? ''),
                              )}
                            ></div>
                            {commentPeriod.additionalText && <p>{commentPeriod.additionalText}</p>}
                            {commentPeriod.informationLabel && (
                              <p>{commentPeriod.informationLabel}</p>
                            )}
                          </div>
                        </div>
                      </>
                    )}

                    {type === 'PROJECT' && (
                      <>
                        <span className="ea-decision">{project?.eacDecision?.name || '-'}</span>
                        <div className="basic-info">
                          <div>
                            <span className="info-label">Proponent</span>
                            <p className="value">{project?.proponent?.name || '-'}</p>
                          </div>
                          <div>
                            <span className="info-label">Type</span>
                            <p className="value">{project?.type || '-'}</p>
                          </div>
                          <div>
                            <span className="info-label">Sub-type</span>
                            <p className="value">{project?.sector || '-'}</p>
                          </div>
                        </div>
                      </>
                    )}

                    {commentPeriodDocs.length > 0 && (
                      <div className="mb-3">
                        <div className="card-header">Related Documents</div>
                        <ul className="doc-list mb-0">
                          {commentPeriodDocs.map((doc) => (
                            <li
                              key={doc._id}
                              className="clickable-row"
                              role="button"
                              tabIndex={0}
                              onClick={() => onDownloadDocument(doc)}
                              onKeyDown={(event) => {
                                if (event.key === 'Enter' || event.key === ' ')
                                  onDownloadDocument(doc);
                              }}
                            >
                              <span className="cell icon">
                                <i className="material-icons">insert_drive_file</i>
                              </span>
                              <span className="cell name" title={doc.displayName || ''}>
                                {doc.displayName}
                              </span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {commentPeriod.openHouses && commentPeriod.openHouses.length > 0 && (
                      <div className="mb-3">
                        <div className="card border-0">
                          <div className="card-header">Open Houses</div>
                          <ul className="list-group mb-0">
                            {commentPeriod.openHouses.map(
                              (openHouse: { eventDate: string; description: string }) => (
                                <li
                                  className="list-group-item"
                                  key={`${openHouse.eventDate}-${openHouse.description}`}
                                >
                                  <h6 className="mb-2">
                                    <b>Date:</b>&nbsp;{mediumDate(openHouse.eventDate)}
                                  </h6>
                                  <h6 className="mb-0">
                                    <b>Description:</b>&nbsp;{openHouse.description}
                                  </h6>
                                </li>
                              ),
                            )}
                          </ul>
                        </div>
                      </div>
                    )}

                    <button
                      className="btn btn-sm inverted"
                      onClick={goBackToProjectDetails}
                      type="button"
                    >
                      {type === 'PROJECT'
                        ? 'Back to Project Details'
                        : 'Back to Project Notifications'}
                    </button>
                  </>
                )}
              </div>
            </div>
          </div>
        </main>
      </div>

      <div className="container comments">
        {commentsQuery.isPending ? (
          <div className="d-flex justify-content-center my-5">
            <div className="spinner-border" role="status">
              <span className="visually-hidden">Loading...</span>
            </div>
          </div>
        ) : (
          <>
            {commentPeriod?.commentPeriodStatus === 'Open' && (
              <div className="mb-3 d-flex justify-content-end">
                <button
                  className="btn btn-warning"
                  onClick={() => commentPeriod._id && setModalOpen(true)}
                  type="button"
                >
                  Submit Comment
                </button>
              </div>
            )}

            {tableData.totalListItems > 0 && (
              <div>
                <TableTemplate data={tableData} onMessage={onMessageOut} />
              </div>
            )}
            {tableData.totalListItems === 0 && <div>There are no comments.</div>}
          </>
        )}
      </div>

      {modalOpen && commentPeriod && (
        <AddComment
          currentPeriod={commentPeriod}
          project={project as Project}
          onDismiss={onModalDismiss}
        />
      )}
    </>
  );
}

// src/app/project/comments/comments.component.ts
import { Component, OnInit, ChangeDetectorRef, OnDestroy } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subject } from 'rxjs/Subject';
import { NgbModal, NgbModalRef } from '@ng-bootstrap/ng-bootstrap';
import { MatSnackBarRef, SimpleSnackBar, MatSnackBar } from '@angular/material';
import { CommentPeriod } from 'app/models/commentperiod';
import { Comment } from 'app/models/comment';

import { CommentService } from 'app/services/comment.service';
import { AddCommentComponent } from './add-comment/add-comment.component';
import { Project } from 'app/models/project';
import { DocumentService } from 'app/services/document.service';
import { ApiService } from 'app/services/api';
import { TableParamsObject } from 'app/shared/components/table-template/table-params-object';
import { TableObject } from 'app/shared/components/table-template/table-object';
import { TableTemplateUtils } from 'app/shared/utils/table-template-utils';
import { CommentsTableRowsComponent } from 'app/project/comments/comments-table-rows/comments-table-rows.component';
import { Utils } from 'app/shared/utils/utils';

@Component({
  selector: 'app-comments',
  templateUrl: './comments.component.html',
  styleUrls: ['./comments.component.scss']
})
export class CommentsComponent implements OnInit, OnDestroy {
  public loading = true;
  public commentsLoading = true;
  public loadingDoc = false;
  public commentPeriod: CommentPeriod;
  public project: Project;
  public comments: Comment[];
  public commentPeriodDocs;

  public commentTableData: TableObject;
  public commentPeriodHeader: String;

  private ngUnsubscribe: Subject<boolean> = new Subject<boolean>();
  private commentPeriodId = null;
  private ngbModal: NgbModalRef = null;

  public tableParams: TableParamsObject = new TableParamsObject();
  private snackBarRef: MatSnackBarRef<SimpleSnackBar> = null;
  public commentTableColumns = [];

  constructor(
    public snackBar: MatSnackBar,
    private api: ApiService,
    private route: ActivatedRoute,
    private commentService: CommentService,
    private documentService: DocumentService,
    private _changeDetectionRef: ChangeDetectorRef,
    private modalService: NgbModal,
    private router: Router,
    private tableTemplateUtils: TableTemplateUtils,
    private utils: Utils,
  ) { }

  ngOnInit() {
    // Get page size and current page from url
    this.route.params.subscribe(params => {
      this.tableParams = this.tableTemplateUtils.getParamsFromUrl(params);
    });

    // get data from route resolver
    this.route.data
      .takeUntil(this.ngUnsubscribe)
      .subscribe(
        (data: { commentPeriod: CommentPeriod, project: Project }) => {

          if (data.project) {
            const results = data.project;
            this.project = results ? results : null;
          }

          if (data.commentPeriod) {
            // To fix the issue where the last page is empty.
            this.commentPeriod = data.commentPeriod;
            if (this.commentPeriod.commentPeriodStatus === 'Closed') {
              this.commentPeriodHeader = 'Public Comment Period is Now Closed';
            } else if (this.commentPeriod.commentPeriodStatus === 'Pending') {
              this.commentPeriodHeader = 'Public Comment Period is Pending';
            } else if (this.commentPeriod.commentPeriodStatus === 'Open') {
              this.commentPeriodHeader = 'Public Comment Period is Now Open';
            }

            if (this.commentPeriod.relatedDocuments && this.commentPeriod.relatedDocuments.length > 0) {
              this.documentService.getByMultiId(this.commentPeriod.relatedDocuments)
                .takeUntil(this.ngUnsubscribe)
                .subscribe(docs => {
                  this.commentPeriodDocs = docs;
                  this._changeDetectionRef.detectChanges();
                });
            }
            this.commentPeriodId = this.commentPeriod._id;
            this.commentService.getByPeriodId(this.commentPeriodId, this.tableParams.currentPage, this.tableParams.pageSize, true)
              .takeUntil(this.ngUnsubscribe)
              .subscribe((res: any) => {
                this.comments = res.currentComments;
                this.tableParams.totalListItems = res.totalCount;
                this.commentTableColumns = [
                  {
                    name: `Showing ${this.comments.length} comments out of ${this.tableParams.totalListItems}:`,
                    value: 'comment',
                    width: 'no-sort',
                    nosort: true
                  },
                ];
                this.setCommentRowData();

                this.loading = false;
                this._changeDetectionRef.detectChanges();
              });

          } else {
            alert('Uh-oh, couldn\'t load comment period');
            // project not found --> navigate back to project list
            this.router.navigate(['/projects']);
          }
        }
      );
  }


  setCommentRowData() {
    this.commentTableData = new TableObject(
      CommentsTableRowsComponent,
      this.comments,
      this.tableParams
    );
  }

  setColumnSort(column) {
    if (this.tableParams.sortBy.charAt(0) === '+') {
      this.tableParams.sortBy = '-' + column;
    } else {
      this.tableParams.sortBy = '+' + column;
    }
    this.getPaginatedComments(this.tableParams.currentPage);
  }

  public downloadDocument(document) {
    this.loadingDoc = true;
    const doc = this.api.downloadDocument(document)
      .then((res) => {
        // Turn this into a toast
        this.loadingDoc = false;
        this.snackBarRef = this.snackBar.open('Downloading document');
        window.setTimeout(() => this.snackBar.dismiss(), 2000)
      })
      .catch((error) => {
        this.loadingDoc = false;
        this.snackBarRef = this.snackBar.open('Error opening document! Please try again later');
        window.setTimeout(() => this.snackBar.dismiss(), 2000)
      })

  }

  public addComment() {
    if (this.commentPeriodId) {
      // open modal
      this.ngbModal = this.modalService.open(AddCommentComponent, { backdrop: 'static', size: 'lg' });
      // set input parameter
      (<AddCommentComponent>this.ngbModal.componentInstance).currentPeriod = this.commentPeriod;
      (<AddCommentComponent>this.ngbModal.componentInstance).project = this.project;
      // check result
      this.ngbModal.result.then(
        value => {
          // saved
          console.log(`Success, value = ${value}`);
        },
        reason => {
          // cancelled
          console.log(`Cancelled, reason = ${reason}`);
        }
      );
    }
  }

  public goBackToProjectDetails() {
    this.router.navigate(['/p', this.project._id]);
  }

  getPaginatedComments(pageNumber) {
    // Go to top of page after clicking to a different page.
    // window.scrollTo(0, 0);
    this.loading = true;

    this.tableParams = this.tableTemplateUtils.updateTableParams(this.tableParams, pageNumber, this.tableParams.sortBy);

    this.commentService.getByPeriodId(this.commentPeriodId, this.tableParams.currentPage, this.tableParams.pageSize, true)
      .takeUntil(this.ngUnsubscribe)
      .subscribe((res: any) => {
        this.tableParams.totalListItems = res.totalCount;
        this.comments = res.currentComments;
        this.tableTemplateUtils.updateUrl(this.tableParams.sortBy, this.tableParams.currentPage, this.tableParams.pageSize);
        this.setCommentRowData();
        this.loading = false;
        this._changeDetectionRef.detectChanges();
      });
  }

  ngOnDestroy() {
    this.ngUnsubscribe.next();
    this.ngUnsubscribe.complete();
  }
}

<div *ngIf="loading" class="spinner-border" role="status">
  <span class="sr-only">Loading...</span>
</div>

<div *ngIf="!loading" class="project">
  <main class="project-info">
    <div class="hero-banner-alt">
      <div class="container">
        <div class="hero-banner__content">
          <h1>{{project?.name || '-'}}</h1>
          <div class="header-section mb-4" *ngIf="commentPeriod !== null && commentPeriod._id == commentPeriod._id">
            <h3>
              {{commentPeriodHeader}}
            </h3>
            <h3>
              {{commentPeriod.dateStarted | date:'mediumDate'}} - {{commentPeriod.longEndDate.format('MMMM DD @ hh:mm z')}}
            </h3>
            <div *ngIf="commentPeriod.informationLabel !== null">
              <div id="instructions" [innerHTML]="commentPeriod.instructions  | safeHtml"></div>
              <br>
              <p>
                {{commentPeriod.additionalText}}
              </p>
              <br>
              <p>
                {{commentPeriod.informationLabel}}
              </p>
            </div>
            <div *ngIf="commentPeriod.informationLabel === null">
              <div id="instructions" [innerHTML]="commentPeriod.instructions  | safeHtml"></div>
            </div>
            <div class="d-flex justify-content-end">
              <button class="btn btn-light" (click)="addComment()" type="button"
                *ngIf="commentPeriod.commentPeriodStatus === 'Open'">Submit Comment</button>
            </div>
          </div>
          <!-- <p class="desc" [innerHTML]="(project?.description || '-') | newlines"></p> -->
          <span class="ea-decision">{{project?.eacDecision?.name || "-"}}</span>
          <div class="basic-info">
            <div>
              <label>Proponent</label>
              <p class="value">{{project?.proponent?.name || "-" | titlecase}}</p>
            </div>
            <div>
              <label>Type</label>
              <p class="value">{{project?.type || "-" | titlecase}}</p>
            </div>
            <div>
              <label>Sub-type</label>
              <p class="value">{{project?.sector || "-" | titlecase}}</p>
            </div>
          </div>
          <div class="related-documents value mt-4" *ngIf="commentPeriodDocs && commentPeriodDocs.length > 0">
            <div class="card">
              <div class="card-header">
                Related Documents
              </div>
              <ul class="doc-list mt-0">
                <li class="clickable-row" *ngFor="let doc of commentPeriodDocs" (click)="downloadDocument(doc)">
                  <span class="cell icon">
                    <i class="material-icons">insert_drive_file</i>
                  </span>
                  <span class="cell name" [title]="doc.displayName || ''">
                    <span class="cell__txt-content">{{doc.displayName}}</span>
                  </span>
                </li>
              </ul>
            </div>
          </div>
          <div class="open-houses value mt-4" *ngIf="commentPeriod && commentPeriod.openHouses && commentPeriod.openHouses.length > 0">
            <div class="card">
              <div class="card-header">
                Open Houses
              </div>
              <ul class="list-group">
                <li class="list-group-item" *ngFor="let openHouse of commentPeriod.openHouses">
                  <h6>
                    <b>Date:</b>&nbsp;{{openHouse.eventDate | date}}
                  </h6>
                  <br>
                  <h6>
                    <b>Description:</b>&nbsp;{{openHouse.description}}
                  </h6>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <button class="btn btn-sm inverted mb-3" (click)="goBackToProjectDetails()" type="button">
          Back to project details
        </button>
      </div>
    </div>
  </main>
</div>
<div *ngIf="!loading" class="container comments mt-3">
  <div *ngIf="tableParams.totalListItems > 0">
    <app-table-template [columns]="commentTableColumns" [data]="commentTableData" (onColumnSort)='setColumnSort($event)'
      (onPageNumUpdate)='getPaginatedComments($event)'>
    </app-table-template>
  </div>
  <div *ngIf="tableParams.totalListItems == 0">
    There are no comments.
  </div>
</div>
