// src/app/pages/project-list/project-list-table-rows.tsx
import { useNavigate } from 'react-router';
import { track } from 'app/analytics/analytics';
import type { TableRowProps } from 'app/components/table/table-object';

export function ProjectListTableRow({ rowData }: TableRowProps) {
  const navigate = useNavigate();

  function goToProject(project: any): void {
    track('Project Viewed', {
      project_id: project._id,
      project_name: project.name,
      source: 'list_view'
    });
    navigate(`/p/${project._id}/project-details`);
  }

  return (
    <tr
      tabIndex={0}
      className="clickable-row"
      onClick={() => goToProject(rowData)}
      onKeyUp={event => {
        if (event.key === 'Enter') goToProject(rowData);
      }}
    >
      <td data-label="Name" className="col-2">{rowData.name || '-'}</td>
      <td data-label="Proponent" className="col-2">{rowData.proponent?.name || '-'}</td>
      <td data-label="Type" className="col-2">{rowData.type || '-'}</td>
      <td data-label="Region" className="col-2">{rowData.region || '-'}</td>
      <td data-label="Phase" className="col-2">{rowData.currentPhaseName?.name || '-'}</td>
      <td data-label="Decision" className="col-2">{rowData.eacDecision?.name || '-'}</td>
    </tr>
  );
}

// src/app/projects/project-list/project-list-table-rows/project-list-table-rows.component.ts
import { Component, EventEmitter, inject } from '@angular/core';
import { Router } from '@angular/router';
import { TableRowComponent, ITableMessage } from 'app/shared/components/table-template/table-row-component';
import { TableObject } from 'app/shared/components/table-template/table-object';

@Component({
  selector: 'app-project-list-table-rows',
  templateUrl: './project-list-table-rows.component.html',
  styleUrls: ['./project-list-table-rows.component.css'],
  standalone: true
})
export class ProjectListTableRowsComponent implements TableRowComponent {
  private router = inject(Router);

  // TableRowComponent interface properties
  rowData: any;
  tableData!: TableObject;
  messageOut = new EventEmitter<ITableMessage>();
  messageIn = new EventEmitter<ITableMessage>();

  goToProject(project: any): void {
    this.router.navigate([`p/${project._id}/project-details`]);
  }
}

<tr tabindex="0"
  class="clickable-row"
  (click)="goToProject(rowData)"
  (keyup.enter)="goToProject(rowData)">
  <td scope="row" data-label="Name" class="col-2">{{rowData.name || '-'}}</td>
  <td scope="row" data-label="Proponent" class="col-2">{{rowData.proponent?.name || '-'}}</td>
  <td scope="row" data-label="Type" class="col-2">{{rowData.type || '-'}}</td>
  <td scope="row" data-label="Region" class="col-2">{{rowData.region || '-'}}</td>
  <td scope="row" data-label="Phase" class="col-2">{{rowData.currentPhaseName?.name || '-'}}</td>
  <td scope="row" data-label="Decision" class="col-2">{{rowData.eacDecision?.name || '-'}}</td>
</tr>
