// src/app/components/info-card.tsx
import { Link } from 'react-router';
import { safeHtml } from 'app/utils/safe-html';

export interface InfoCardButton {
  text: string;
  link?: string;
  href?: string;
  icon?: string;
  target?: string;
  rel?: string;
  title?: string;
}

interface InfoCardProps {
  title: string;
  description: string;
  icon?: string;
  button?: InfoCardButton;
}

export function InfoCard({ title, description, icon, button }: InfoCardProps) {
  return (
    <div className="feature-block">
      {icon && (
        <div className="feature-block__icon">
          <div
            className="rounded-circle border border-white border-3 d-inline-flex align-items-center justify-content-center"
            style={{ width: '80px', height: '80px' }}
          >
            <i className="material-icons fs-1 text-white">{icon}</i>
          </div>
        </div>
      )}
      <div className="feature-block__header">
        <h3>{title}</h3>
      </div>
      <div className="feature-block__body">
        <p dangerouslySetInnerHTML={safeHtml(description)}></p>
      </div>
      {button && (
        <div className="feature-block__footer">
          {button.link ? (
            <Link className="btn btn-sm inverted" to={button.link} aria-label={button.title || button.text}>
              {button.text}
            </Link>
          ) : button.href ? (
            <a
              className="btn btn-sm inverted"
              href={button.href}
              target={button.target || '_self'}
              rel={button.rel || ''}
              title={button.title || button.text}
            >
              {button.text}
            </a>
          ) : null}
        </div>
      )}
    </div>
  );
}

// src/app/shared/info-card/info-card.component.ts
import { Component, input } from '@angular/core';
import { RouterLink } from '@angular/router';

export interface InfoCardButton {
  text: string;
  link?: string;
  href?: string;
  icon?: string;
  target?: string;
  rel?: string;
  title?: string;
}

@Component({
  selector: 'app-info-card',
  templateUrl: './info-card.component.html',
  imports: [RouterLink],
})
export class InfoCardComponent {
  title = input.required<string>();
  description = input.required<string>();
  icon = input<string>();
  button = input<InfoCardButton>();
}

<div class="feature-block">
  @if (icon()) {
    <div class="feature-block__icon">
      <div class="rounded-circle border border-white border-3 d-inline-flex align-items-center justify-content-center" style="width: 80px; height: 80px;">
        <i class="material-icons fs-1 text-white">{{ icon() }}</i>
      </div>
    </div>
  }
  <div class="feature-block__header">
    <h3>{{ title() }}</h3>
  </div>
  <div class="feature-block__body">
    <p [innerHTML]="description()"></p>
  </div>
  @if (button()) {
    <div class="feature-block__footer">
      @if (button()!.link) {
        <a class="btn btn-sm inverted" 
           [routerLink]="button()!.link"
           [attr.aria-label]="button()!.title || button()!.text">
          {{ button()!.text }}
        </a>
      } @else if (button()!.href) {
        <a class="btn btn-sm inverted" 
           [href]="button()!.href"
           [target]="button()!.target || '_self'"
           [rel]="button()!.rel || ''"
           [title]="button()!.title || button()!.text">
          {{ button()!.text }}
        </a>
      }
    </div>
  }
</div>
