// src/app/components/filters/search-filter-template.tsx
import { useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router';
import { track } from 'app/analytics/analytics';
import { CustomMultiSelect } from './custom-multi-select';
import { DatePicker } from './date-picker';
import {
  buildSearchPackage,
  FilterType,
  hasActiveFilters,
  initialFilterValues,
  type FilterObject,
  type FilterValues,
  type SearchPackage,
} from './filter-object';
import './filters.css';

interface SearchFilterTemplateProps {
  title?: string;
  tooltip?: string;
  keywordWatermark?: string;
  advancedFilters?: boolean;
  showAdvancedFilters?: boolean;
  searchOnFilterChange?: boolean;
  filterItemPanelSize?: number;
  filters?: FilterObject[];
  /** Seeds the keyword box from a param the host owns (tab-scoped keywords). */
  keywordOverride?: string;
  searchHelpLink?: string | null;
  searching?: boolean;
  /** 'filters' renders the redesigned tune-icon toggle; 'advanced' keeps the legacy label. */
  filterToggle?: 'advanced' | 'filters';
  /** Debounces the keyword box 300ms after the last keystroke and hides the Search button, since there is nothing left to click. */
  searchAsYouType?: boolean;
  onSearch: (searchPackage: SearchPackage) => void;
  onToggleFiltersPanel?: (event: { showPanel: boolean }) => void;
  onFilterChange?: (values: FilterValues) => void;
  onResetControls?: () => void;
}

const RESERVED_PARAMS = ['currentPage', 'pageSize', 'sortBy', 'keywords'];

export function SearchFilterTemplate({
  title,
  tooltip,
  keywordWatermark,
  advancedFilters = false,
  showAdvancedFilters = false,
  searchOnFilterChange = true,
  filterItemPanelSize = 4,
  filters = [],
  keywordOverride = '',
  searchHelpLink = null,
  searching = false,
  filterToggle = 'advanced',
  searchAsYouType = false,
  onSearch,
  onToggleFiltersPanel,
  onFilterChange,
  onResetControls,
}: SearchFilterTemplateProps) {
  const [searchParams] = useSearchParams();
  const [keywords, setKeywords] = useState(
    () => keywordOverride || searchParams.get('keywords') || '',
  );
  const [values, setValues] = useState<FilterValues>({});
  const [showFiltersPanel, setShowFiltersPanel] = useState(showAdvancedFilters);
  const [lastShowAdvanced, setLastShowAdvanced] = useState(showAdvancedFilters);
  const previousKeywords = useRef(keywords);
  const seededFrom = useRef<FilterObject[] | null>(null);
  const debounceTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    return () => {
      if (debounceTimer.current) clearTimeout(debounceTimer.current);
    };
  }, []);

  function cancelPendingSearch(): void {
    if (debounceTimer.current) {
      clearTimeout(debounceTimer.current);
      debounceTimer.current = null;
    }
  }

  // The host opens the panel when the URL already carries a filter; follow it without an effect.
  if (lastShowAdvanced !== showAdvancedFilters) {
    setLastShowAdvanced(showAdvancedFilters);
    setShowFiltersPanel(showAdvancedFilters);
  }

  // Filters arrive asynchronously (orgs, lists). Seed the form off the URL the first time a
  // populated set shows up, and again only if the host swaps the filter set out.
  useEffect(() => {
    if (!advancedFilters || filters.length === 0 || seededFrom.current === filters) {
      return;
    }
    seededFrom.current = filters;
    const urlValues: FilterValues = {};
    for (const [key, value] of searchParams.entries()) {
      if (!RESERVED_PARAMS.includes(key)) {
        urlValues[key] = value;
      }
    }
    setValues(initialFilterValues(filters, urlValues));
  }, [advancedFilters, filters, searchParams]);

  function emitSearch(nextValues: FilterValues, nextKeywords: string): void {
    const searchPackage = buildSearchPackage(
      filters,
      nextValues,
      nextKeywords,
      nextKeywords !== previousKeywords.current,
    );
    previousKeywords.current = nextKeywords;

    track('Search Executed', {
      search_term: searchPackage.keywords || '',
      has_keywords: !!searchPackage.keywords,
      keyword_count: searchPackage.keywords ? searchPackage.keywords.split(' ').length : 0,
      filter_count: Object.keys(searchPackage.filters).length,
      subset: null,
    });

    onSearch(searchPackage);
  }

  function setValue(key: string, value: any): void {
    const nextValues = { ...values, [key]: value };
    setValues(nextValues);
    onFilterChange?.(nextValues);
    if (searchOnFilterChange) {
      emitSearch(nextValues, keywords);
    }
  }

  function toggleAdvancedFilters(): void {
    const showPanel = !showFiltersPanel;
    window.hj?.('event', 'SEARCH_TOGGLED');
    track('Filters Panel Toggled', { action: showPanel ? 'opened' : 'closed' });
    setShowFiltersPanel(showPanel);
    onToggleFiltersPanel?.({ showPanel });
  }

  function clearFilters(): void {
    cancelPendingSearch();
    window.hj?.('event', 'FILTERS_CLEARED');
    track('Filters Cleared', {
      had_keywords: !!keywords,
      had_filters: hasActiveFilters(values, keywords),
    });

    setValues({});
    setKeywords('');
    previousKeywords.current = '';
    onResetControls?.();
    onSearch({ keywords: '', keywordsChanged: false, subset: null, filters: {} });
  }

  return (
    <div className="search-filter-wrapper">
      {title && (
        <div className="row mb-3">
          <div className="col">
            <span className="keyword-search-text">{title}</span>
            {tooltip && (
              <span
                className="material-icons align-text-bottom ml-2"
                title={tooltip}
                aria-label="Icon that displays a tooltip when focused or hovered over"
              >
                help_outline
              </span>
            )}
          </div>
        </div>
      )}

      <div className="search-bar-section mb-4">
        <div className="row">
          <div className="col">
            <div className="input-group">
              <div className="search-input-wrapper position-relative">
                <input
                  type="text"
                  className="form-control data-hj-allow"
                  value={keywords}
                  onChange={(event) => {
                    const nextKeywords = event.target.value;
                    setKeywords(nextKeywords);
                    if (searchAsYouType) {
                      cancelPendingSearch();
                      debounceTimer.current = setTimeout(() => {
                        emitSearch(values, nextKeywords);
                      }, 300);
                    }
                  }}
                  onKeyUp={(event) => {
                    if (event.key === 'Enter') {
                      cancelPendingSearch();
                      emitSearch(values, keywords);
                    }
                  }}
                  placeholder={keywordWatermark || 'Type keyword to search'}
                  aria-label={keywordWatermark || 'Type keyword to search'}
                  aria-describedby="basic-addon2"
                />
                {keywords.length > 0 && (
                  <button
                    className="search-clear-btn btn btn-link"
                    type="button"
                    title="Clear search"
                    onClick={() => {
                      cancelPendingSearch();
                      setKeywords('');
                      emitSearch(values, '');
                    }}
                  >
                    <span className="material-icons">close</span>
                  </button>
                )}
              </div>
              {!searchAsYouType && (
                <button
                  className="btn btn-warning"
                  type="button"
                  onClick={() => emitSearch(values, keywords)}
                  disabled={searching}
                >
                  {searching ? (
                    <span
                      className="spinner-border spinner-border-sm"
                      role="status"
                      aria-hidden="true"
                    ></span>
                  ) : (
                    <span className="material-icons">search</span>
                  )}
                  <span className="ms-2">{searching ? 'Searching...' : 'Search'}</span>
                </button>
              )}
            </div>
          </div>
        </div>
      </div>

      {(searchHelpLink || advancedFilters) && (
        <div className="action-buttons-section">
          <div className="row">
            <div className="col-sm-12 col-md-6 text-md-start text-center mb-md-0 mb-3">
              {searchHelpLink && (
                <Link
                  className="btn btn-primary d-inline-flex align-items-center"
                  to={searchHelpLink}
                  target="_blank"
                  rel="noopener"
                >
                  <span className="material-icons">info</span>
                  <span className="ms-2">Search Help</span>
                </Link>
              )}
            </div>
            <div className="col-sm-12 col-md-6 text-md-end text-center">
              {advancedFilters && filterToggle === 'filters' && (
                <button
                  type="button"
                  className="btn btn-primary"
                  onClick={toggleAdvancedFilters}
                  aria-expanded={showFiltersPanel}
                  aria-controls="advancedFilterPanel"
                >
                  <span className="material-icons" aria-hidden="true">
                    tune
                  </span>
                  Filters
                </button>
              )}
              {advancedFilters && filterToggle === 'advanced' && (
                <button className="btn btn-primary" onClick={toggleAdvancedFilters}>
                  {showFiltersPanel ? 'Close' : 'Open'} Advanced Filters
                  <span className="material-icons align-middle">
                    {showFiltersPanel ? 'keyboard_arrow_up' : 'keyboard_arrow_down'}
                  </span>
                </button>
              )}
            </div>
          </div>
        </div>
      )}

      {advancedFilters && (
        <div className="advanced-filters-section">
          <div
            id="advancedFilterPanel"
            className="row border-bottom pb-3"
            hidden={!showFiltersPanel}
          >
            <form className="filter-form" noValidate onSubmit={(event) => event.preventDefault()}>
              <div className={`row${searching ? ' disable-div' : ''}`}>
                {filters.map((filter) => (
                  <div
                    key={filter.id}
                    className={`pb-1 filter-panel col-md-${filter.itemPanelSize ?? filterItemPanelSize}`}
                  >
                    {filter.type === FilterType.DateRange && (
                      <div>
                        {filter.name && filter.name.length > 0 && (
                          <span className="control-label font-weight-bold">{filter.name}</span>
                        )}
                        <div className="row">
                          <div className="col-md-6 start-date-padding">
                            <label
                              htmlFor={filter.filterDefinition.startDateId}
                              className="control-label font-weight-bold"
                            >
                              {filter.filterDefinition.startDateLabel}
                            </label>
                            <DatePicker
                              id={filter.filterDefinition.startDateId}
                              value={values[filter.filterDefinition.startDateId] ?? ''}
                              minDate={filter.filterDefinition.minDate}
                              maxDate={filter.filterDefinition.maxDate}
                              onChange={(value) =>
                                setValue(filter.filterDefinition.startDateId, value)
                              }
                            />
                          </div>
                          <div className="col-md-6 end-date-padding">
                            <label
                              htmlFor={filter.filterDefinition.endDateId}
                              className="control-label font-weight-bold"
                            >
                              {filter.filterDefinition.endDateLabel}
                            </label>
                            <DatePicker
                              id={filter.filterDefinition.endDateId}
                              value={values[filter.filterDefinition.endDateId] ?? ''}
                              minDate={filter.filterDefinition.minDate}
                              maxDate={filter.filterDefinition.maxDate}
                              onChange={(value) =>
                                setValue(filter.filterDefinition.endDateId, value)
                              }
                            />
                          </div>
                        </div>
                      </div>
                    )}

                    {filter.type === FilterType.MultiSelect && (
                      <div>
                        {filter.name && filter.name.length > 0 && (
                          <span className="control-label font-weight-bold">{filter.name}</span>
                        )}
                        <div className="form-group">
                          <CustomMultiSelect
                            id={filter.name}
                            items={filter.filterDefinition.options ?? []}
                            selected={values[filter.id] ?? []}
                            bindLabel="name"
                            groupBy={filter.filterDefinition.group?.name ?? null}
                            placeholder={`Type ${filter.name}`}
                            onChange={(selected) => setValue(filter.id, selected)}
                          />
                        </div>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </form>
            <div className="reset-button-container">
              <button
                className="btn btn-primary float-end"
                onClick={clearFilters}
                disabled={searching || !hasActiveFilters(values, keywords)}
              >
                Reset Filters
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// src/app/shared/components/search-filter-template/search-filter-template.component.ts
import { ViewEncapsulation, ChangeDetectionStrategy, OnInit, OnDestroy, Component, Input, EventEmitter, Output, Inject, AfterViewInit } from '@angular/core';
import { FilterObject, FilterType } from './filter-object';
import { ActivatedRoute } from '@angular/router';
import { SubsetsObject } from './subset-object';
import { FormGroup, FormControl } from '@angular/forms';
import { DOCUMENT } from '@angular/common';
import { Utils } from 'app/shared/utils/utils';
import { takeWhile } from 'rxjs/operators';

/**
 * Common template component for NRPTI search filters. The default component will only include a keyword
 * search bar. You can extend the functionality of the search by adding additional options.
 *
 * You can add a keyword subset filter by adding a subset object, which will display a dropdown on
 * the left of the keyword search, allowing for subset searches. See the SubsetObject class for
 * further instructions on their setup and use
 *
 * You can add advanced filters by setting the advancedFilters option to true, and supplying
 * an array of FilterObjects. Filter objects include definitions for the advanced search
 * components, their source ID's, selectable options, and type. More informatin is
 * available in the FilterObject class.
 *
 * @export
 * @class SearchFilterTemplateComponent
 * @implements {OnInit}
 * @implements {OnDestroy}
 */
@Component({
  selector: 'search-filter-template',
  templateUrl: './search-filter-template.component.html',
  styleUrls: ['./search-filter-template.component.scss'],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.Default
})
export class SearchFilterTemplateComponent implements OnInit, AfterViewInit, OnDestroy {
  // Inputs
  @Input() title: string;
  @Input() tooltip: string;
  @Input() keywordWatermark: string;
  @Input() subsets: SubsetsObject;
  @Input() advancedFilters = false;
  @Input() attachPanelToDiv = null;
  @Input() advancedFilterTitle = null;
  @Input() advancedFilterText = null;
  @Input() showAdvancedFilters = false;
  @Input() searchOnFilterChange = true;
  @Input() filterItemPanelSize = 4;
  @Input() filters: FilterObject[] = [];
  @Input() keywordOverride: '';
  @Input() searchHelpLinkArray: null;

  // Outputs and Emitters
  // searchEvent fires whenever a search is executed. The host component is responsible
  // for parsing the search package and handling as necessary
  @Output() searchEvent: EventEmitter<any> = new EventEmitter<any>();
  // resetControls fires when the filter form is reset
  @Output() resetControls: EventEmitter<void> = new EventEmitter<void>();
  // filterChange fires whenever a filter on the advanced filter form is changed
  @Output() filterChange: EventEmitter<any> = new EventEmitter<any>();
  // toggleFiltersPanelEvent fires when a User clicks the show/hide advanced filters button
  @Output() toggleFiltersPanelEvent: EventEmitter<any> = new EventEmitter<any>();

  // public vars
  public FilterType = FilterType; // enum access for the template html
  public keywordSearchWords: string;
  public previousKeywords: string;
  public queryParams = {};
  public formGroup: FormGroup; // Helper formGroup for grabbing values from controls

  private alive = true;
  /**
   * Creates an instance of SearchFilterTemplateComponent.
   * @param {Router} router Router used to detect URL params
   * @param {Utils} utils Utils class for date conversion
   * @memberof SearchFilterTemplateComponent
   */
  constructor(
    private route: ActivatedRoute,
    public utils: Utils,
    @Inject(DOCUMENT) _document
  ) { }

  ngOnDestroy(): void { }

  ngOnInit() {
    const urlValues: object = {}; // Storage for the URL params

    // ensure we parse through values from the URL and preselect anything
    // that needs pre-selecting

    this.route.queryParamMap.pipe(takeWhile(() => this.alive)).subscribe(data => {
      const filterParams = { ...data['params'] };
      delete filterParams.currentPage;
      delete filterParams.pageSize;
      delete filterParams.sortBy;

      for (const key in filterParams) {
        // we know how to handle keyword and subset, but everything
        // else will be dynamic
        if (key === 'keywords') {
          this.keywordSearchWords = filterParams[key];
        } else if (key === 'subset') {
          if (this.subsets) {
            this.subsets.selectedSubset = this.subsets.options.find(subset => subset.subset === filterParams[key]) ||
              this.subsets.options[0];
          }
        } else {
          // add all remaining kvp's onto the urlValues object.
          // We can use these when building the form group to preset
          // component values
          urlValues[key] = filterParams[key];
        }
      }
    });

    if (this.keywordOverride) {
      this.keywordSearchWords = this.keywordOverride;
    }

    // build formGroup based on provided filters
    this.buildFormComponents(urlValues);
  }

  /**
   * This will force a rebuild of all filter object components
   * in the search controls 'filters' array, and update the
   * forms group. This is kept public in case you want to allow
   * for dynamically changing the advanced filters on a host component
   *
   * @param {*} defaultFormValues A KVP object that will map default settings for filter values
   * @memberof SearchFilterTemplateComponent
   */
  buildFormComponents(defaultFormValues = {}) {
    // If we don't have advanced filters active, don't build the form
    if (!this.advancedFilters) {
      return;
    }

    // ensure defaultFormValues isn't null
    if (defaultFormValues === null) {
      defaultFormValues = {};
    }

    // This sloppy mess will iterate over each filter that's been passed
    // into the filters array. For each filter type, a form control will
    // be created. If default form values are passed in, an attempt will
    // be made to preset the values.
    const groupControls = {};

    this.filters.forEach(filter => {
      if (filter.type === FilterType.DateRange) {
        // read the url and apply val or null where appropriate
        groupControls[filter.filterDefinition.startDateId] = new FormControl();
        groupControls[filter.filterDefinition.endDateId] = new FormControl();

        if (defaultFormValues[filter.filterDefinition.startDateId]) {
          const date = new Date(defaultFormValues[filter.filterDefinition.startDateId]);

          groupControls[filter.filterDefinition.startDateId]
            .setValue({ year: date.getFullYear(), day: date.getDay(), month: date.getMonth() });
        }

        if (defaultFormValues[filter.filterDefinition.endDateId]) {
          const date = new Date(defaultFormValues[filter.filterDefinition.endDateId]);

          groupControls[filter.filterDefinition.endDateId]
            .setValue({ year: date.getFullYear(), day: date.getDay(), month: date.getMonth() });
        }
      } else if (filter.type === FilterType.Checkbox) {
        if (!filter.filterDefinition.grouped) {
          filter.filterDefinition.options.forEach(option => {
            groupControls[option.id] = new FormControl();

            if (defaultFormValues[option.id]) {
              groupControls[option.id].setValue(defaultFormValues[option.id]);
            }
          });
        } else {
          const vals = defaultFormValues[filter.id];

          filter.filterDefinition.options.forEach(option => {
            groupControls[option.id] = new FormControl();

            if (vals && vals.split(',').includes(option.id)) {
              groupControls[option.id].setValue(true);
            }
          });
        }
      } else if (filter.type === FilterType.MultiSelect) {
        groupControls[filter.id] = new FormControl();

        if (defaultFormValues[filter.id]) {
          groupControls[filter.id].setValue(decodeURIComponent(defaultFormValues[filter.id]));
        }
      } else if (filter.type === FilterType.Dropdown) {
        groupControls[filter.id] = new FormControl();

        if (defaultFormValues[filter.id]) {
          groupControls[filter.id].setValue(decodeURIComponent(defaultFormValues[filter.id].split(',')));
        }
      } else {
        groupControls[filter.id] = new FormControl();

        if (defaultFormValues[filter.id]) {
          groupControls[filter.id].setValue(defaultFormValues[filter.id]);
        }
      }
    });

    this.formGroup = new FormGroup(groupControls);
    this.formGroup.valueChanges.subscribe(val => {
      this.filterChange.emit(val);
      if (this.searchOnFilterChange) {
        this.search();
      }
    });
  }

  ngAfterViewInit() {
    // if the advanced filters panel is hidden, this will not work
    if (this.attachPanelToDiv && document.getElementById(this.attachPanelToDiv)) {
      // what if the user is hiding the advanced filters page? We need the panel
      // 'visible' to append... so just grab the value and re-apply after append
      const showAdvancedFiltersSetting = this.showAdvancedFilters;
      this.showAdvancedFilters = true;
      document.getElementById(this.attachPanelToDiv).appendChild(document.getElementById('advancedFilterPanel'));
      this.showAdvancedFilters = showAdvancedFiltersSetting;
    }
  }
  /*****************************************************
   *  Events/Emitters
   *****************************************************/

  /**
   * Search will build a search package containing keyword and filter settings
   * and fire en event to the host component to handle the search.
   *
   * @memberof SearchFilterTemplateComponent
   */
  search() {
    // Create a search package containing the users search
    // filters
    const searchPackage = {
      keywords: this.keywordSearchWords,
      keywordsChanged: this.keywordSearchWords !== this.previousKeywords,
      subset: this.subsets ? this.subsets.selectedSubset.subset : null,
      filters: {}
    };

    this.previousKeywords = this.keywordSearchWords;

    // loop through form filter objects, pull out the values
    // and append to the package
    this.filters.forEach(filter => {
      if (filter.type === FilterType.DateRange) {
        const dateFilter = filter.filterDefinition;

        if (this.formGroup.get(dateFilter.startDateId).value) {
          searchPackage.filters[dateFilter.startDateId] =
            this.utils.convertFormGroupNGBDateToJSDate(this.formGroup.get(dateFilter.startDateId).value).toISOString();
        }

        if (this.formGroup.get(dateFilter.endDateId).value) {
          searchPackage.filters[dateFilter.endDateId] =
            this.utils.convertFormGroupNGBDateToJSDate(this.formGroup.get(dateFilter.endDateId).value).toISOString();
        }
      } else if (filter.type === FilterType.Checkbox) {
        if (!filter.filterDefinition.grouped) {
          filter.filterDefinition.options.forEach(option => {
            if (this.formGroup.get(option.id).value) {
              searchPackage.filters[option.id] = this.formGroup.get(option.id).value;
            }
          });
        } else {
          const groupedVals = [];

          filter.filterDefinition.options.forEach(option => {
            if (this.formGroup.get(option.id).value) {
              groupedVals.push(option.id);
            }
          });

          if (groupedVals.length > 0) {
            searchPackage.filters[filter.id] = groupedVals;
          }
        }
      } else if (filter.type === FilterType.MultiSelect) {
        const groupedVals = [];
        if (filter.filterDefinition.selectedOptions.length > 0) {
          filter.filterDefinition.selectedOptions.forEach(item => {
            groupedVals.push(item._id);
          });
          searchPackage.filters[filter.id] = groupedVals;
        } else {
          delete searchPackage.filters[filter.id];
        }
      } else {
        if (this.formGroup.get(filter.id).value) {
          searchPackage.filters[filter.id] = this.formGroup.get(filter.id).value;
        }
      }
    });
    // and return the package to the host component
    this.searchEvent.emit(searchPackage);
  }

  /*****************************************************
   *  Utility and Helper functions
   *****************************************************/

  // hides and displays the advanced filters
  // Emits an event on the toggleFiltersPanelEvent emitter
  toggleAdvancedFilters() {
    this.showAdvancedFilters = !this.showAdvancedFilters;
    this.toggleFiltersPanelEvent.emit({ showPanel: this.showAdvancedFilters });
  }

  /**
   * Clears all filter components on the search form,
   * including keyword and subset selections
   *
   * @memberof SearchFilterTemplateComponent
   */
  clearFilters() {
    // reset the form group, doesn't appear to reset multiselects, or date ranges
    this.formGroup.reset();
    // clear multiSelects && date ranges
    for (const filter of this.filters.filter(f => f.type === FilterType.MultiSelect)) {
      filter.filterDefinition.selectedOptions = [];
    }
    // clear keywords
    this.keywordSearchWords = '';
    // reset the subset settings
    if (this.subsets) {
      this.changeSubset(this.subsets.defaultSubset);
    }
    // emit to the host that the form was reset
    this.resetControls.emit();
    // rerun the search
    this.search();
  }

  // Resets a specific filter
  resetFilter(filterId) {
    for (const filter of this.filters) {
      if (filter.id === filterId && filter.type === FilterType.RadioPicker) {
        this.formGroup.get(filter.id).setValue(null);
        break;
      }
    }
  }

  /**
   * Clear the keyword search text box
   *
   * @memberof SearchFilterTemplateComponent
   */
  clearSearchTerms() {
    this.keywordSearchWords = '';
    this.search();
  }

  /**
   *
   * Change the selected subset item. Also, when
   * a subset changes, we should trigger a search event
   * if there are any keywords
   *
   * @param {*} subsetItem
   * @memberof SearchFilterTemplateComponent
   */
  changeSubset(subsetItem): void {
    this.subsets.selectedSubset = subsetItem;
    this.queryParams[subsetItem.subsetLabel] = subsetItem.subset;

    if (this.keywordSearchWords) {
      this.queryParams['keywords'] = this.keywordSearchWords;
      this.search();
    }
  }

  changeMultiSelect() {
    this.search();
  }
}

<div class="search-filter-wrapper">
  <!-- Header Row -->
  @if (title()) {
    <div class="row mb-3">
      <div class="col">
        <span class="keyword-search-text">{{title()}}</span>
        @if (tooltip()) {
          <span class="material-icons align-text-bottom ml-2"
            [ngbTooltip]="tooltip()!"
            placement="end"
            aria-label="Icon that displays a tooltip when focused or hovered over">
            help_outline
          </span>
        }
      </div>
    </div>
  }

  <!-- Search bar section -->
  <div class="search-bar-section mb-4">
    <div class="row">
      <div class="col">
        <div class="input-group">
          @if (subsets(); as subsetsValue) {
            <div class="dropdown">
              <button class="btn btn-outline-secondary dropdown-toggle"
                type="button"
                id="dropdown"
                data-bs-toggle="dropdown"
                aria-expanded="false">
                @if (subsetsValue.selectedSubset !== null) {
                  {{ subsetsValue.selectedSubset.subsetLabel }}
                } @else {
                  {{ subsetsValue.defaultSubset!.subsetLabel }}
                }
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdown">
                @for (subset of subsetsValue.options; track subset.subset) {
                  <li>
                    <button class="dropdown-item"
                      type="button"
                      [disabled]="subsetsValue.selectedSubset!.subsetLabel === subset.subsetLabel"
                      (click)="changeSubset(subset)">
                      {{ subset.subsetLabel }}
                      @if (subsetsValue.selectedSubset === subset) {
                        <span class="material-icons material-icons align-text-bottom">
                          check_circle
                        </span>
                      }
                    </button>
                  </li>
                }
              </ul>
            </div>
          }
          <div class="search-input-wrapper position-relative">
            <input type="text"
              class="form-control data-hj-allow"
              (keyup.enter)="search()"
              [ngModel]="keywordSearchWords()"
              (ngModelChange)="keywordSearchWords.set($event)"
              [placeholder]="keywordWatermark() || 'Type keyword to search'"
              [attr.aria-label]="keywordWatermark() || 'Type keyword to search'"
              aria-describedby="basic-addon2">
            @if (keywordSearchWords() && keywordSearchWords().length > 0) {
              <button class="search-clear-btn btn btn-link"
                type="button"
                title="Clear search"
                (click)="clearSearchTerms()">
                <span class="material-icons">close</span>
              </button>
            }
          </div>
          <button class="btn btn-warning"
            type="button"
            (click)="search()"
            [disabled]="searching()">
            @if (!searching()) {
              <span class="material-icons">search</span>
            }
            @if (searching()) {
              <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            }
            <span class="ms-2">{{searching() ? 'Searching...' : 'Search'}}</span>
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Action buttons section -->
  @if (searchHelpLinkArray() || advancedFilters()) {
  <div class="action-buttons-section">
    <div class="row">
      <div class="col-sm-12 col-md-6 text-md-start text-center mb-md-0 mb-3">
        @if (searchHelpLinkArray()) {
          <a class="btn btn-primary d-inline-flex align-items-center"
            [routerLink]="searchHelpLinkArray()!"
            target="_blank"
            rel="noopener">
            <span class="material-icons">info</span>
            <span class="ms-2">Search Help</span>
          </a>
        }
      </div>
      <!-- Advanced Filters toggle -->
      <div class="col-sm-12 col-md-6 text-md-end text-center">
        @if (advancedFilters()) {
          <button class="btn btn-primary"
            (click)="toggleAdvancedFilters()">
            {{showFiltersPanel() ? 'Close' : 'Open'}} Advanced Filters
            <span class="material-icons align-middle">
              {{showFiltersPanel() ? 'keyboard_arrow_up' : 'keyboard_arrow_down'}}
            </span>
          </button>
        }
      </div>
    </div>
  </div>
  }

  <!-- Advanced filters panel section -->
  @if (advancedFilters()) {
    <div class="advanced-filters-section">
      <div id="advancedFilterPanel"
        class="row border-bottom pb-3"
        [hidden]="!showFiltersPanel()">
      <form class="filter-form"
        [formGroup]="formGroup"
        novalidate>
        @if (advancedFilterTitle() && advancedFilterTitle()!.length > 0) {
          <div class="row filter-header">
            <h3>{{advancedFilterTitle()}}</h3>
          </div>
        }
        @if (advancedFilterText() && advancedFilterText()!.length > 0) {
          <div class="row filter-header">
            <p>{{advancedFilterText()}}</p>
          </div>
        }
        <div class="row"
          [ngClass]="searching() ? 'disable-div' : ''">
          <!-- for each filter, create a block for each filter type -->
          @for (filter of filters(); track filter.id) {
            <div [class]="'pb-1 filter-panel col-md-' + (filter.itemPanelSize ? filter.itemPanelSize : filterItemPanelSize())">
              <!-- Date range filter-->
              @if (filter.type === FilterType.DateRange) {
                <div>
                  @if (filter.name && filter.name.length > 0) {
                    <span class="control-label font-weight-bold">{{filter.name}}</span>
                  }
                  <div class="row">
                    <div class="col-md-6 start-date-padding">
                      <label [for]="filter.filterDefinition.startDateId"
                        class="control-label font-weight-bold"
                        tabindex="0">{{filter.filterDefinition.startDateLabel}}</label>
                      @if (formGroup.get(filter.filterDefinition.startDateId); as startControl) {
                        <lib-date-picker [id]="filter.filterDefinition.startDateId"
                          [control]="$any(startControl)"
                          [minDate]="filter.filterDefinition.minDate"
                          [maxDate]="filter.filterDefinition.maxDate">
                        </lib-date-picker>
                      }
                    </div>
                    <div class="col-md-6 end-date-padding">
                      <label [for]="filter.filterDefinition.endDateId"
                        class="control-label font-weight-bold"
                        tabindex="0">{{filter.filterDefinition.endDateLabel}}</label>
                      @if (formGroup.get(filter.filterDefinition.endDateId); as endControl) {
                        <lib-date-picker [id]="filter.filterDefinition.endDateId"
                          [control]="$any(endControl)"
                          [minDate]="filter.filterDefinition.minDate"
                          [maxDate]="filter.filterDefinition.maxDate">
                        </lib-date-picker>
                      }
                    </div>
                  </div>
                </div>
              }
              <!-- dropdown filter -->
              @if (filter.type === FilterType.Dropdown) {
                <div>
                  @if (filter.name && filter.name.length > 0) {
                    <span class="control-label font-weight-bold">{{filter.name}}</span>
                  }
                  <select class="form-select"
                    [attr.aria-label]="filter.name + ' dropdown'"
                    [formControlName]="filter.id"
                    [attr.multiple]="filter.filterDefinition.multiselect ? true : null">
                    @if (!filter.filterDefinition.multiselect) {
                      <option value="">Select an option</option>
                    }
                    @for (option of filter.filterDefinition.options; track option) {
                      <option [value]="option">{{option}}</option>
                    }
                  </select>
                </div>
              }
              <!-- multi select filter -->
              @if (filter.type === FilterType.MultiSelect) {
                <div>
                  @if (filter.name && filter.name.length > 0) {
                    <span class="control-label font-weight-bold"
                      tabindex="0">{{filter.name}}</span>
                  }
                  <app-autocomplete-multi-select [filter]="filter"
                    (changeEvent)="changeMultiSelect()"
                    [control]="$any(formGroup.get(filter.id))">
                  </app-autocomplete-multi-select>
                </div>
              }
              <!-- radio button filter -->
              @if (filter.type === FilterType.RadioPicker) {
                <div>
                  @if (filter.name && filter.name.length > 0) {
                    <span class="control-label font-weight-bold">{{filter.name}}</span>
                  }
                  <div class="row">
                    @for (radio of filter.filterDefinition.options; track radio.id) {
                      <div class="col-xl-5">
                        <div class="radio">
                          <input type="radio"
                            [id]="radio.id"
                            [value]="radio.value"
                            [formControlName]="filter.id"
                            [name]="filter.id" />
                          <label class="radio-label"
                            [for]="radio.id">{{radio.label}}</label>
                        </div>
                      </div>
                    }
                    <div class="col-xl-1 d-flex align-items-center">
                      @if (formGroup.get(filter.id)!.value) {
                        <button type="button" class="clear-button"
                          (click)="resetFilter(filter.id)"
                          aria-label="Clear filter">
                          <svg class="bi bi-x-circle"
                            width="1em"
                            height="1em"
                            viewBox="0 0 16 16"
                            fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                              d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                            <path fill-rule="evenodd"
                              d="M11.854 4.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708-.708l7-7a.5.5 0 0 1 .708 0z" />
                            <path fill-rule="evenodd"
                              d="M4.146 4.146a.5.5 0 0 0 0 .708l7 7a.5.5 0 0 0 .708-.708l-7-7a.5.5 0 0 0-.708 0z" />
                          </svg>
                        </button>
                      }
                    </div>
                  </div>
                </div>
              }
              <!-- check box filter -->
              @if (filter.type === FilterType.Checkbox) {
                <div>
                  @if (filter.name && filter.name.length > 0) {
                    <span class="control-label font-weight-bold">{{filter.name}}</span>
                  }
                  <div class="row">
                    @for (box of filter.filterDefinition.options; track box.id) {
                      <div class="col-xl-3">
                        <div class="form-check">
                          <input class="form-check-input" 
                            type="checkbox"
                            [id]="box.id"
                            [name]="box.id"
                            [formControlName]="box.id">
                          <label class="form-check-label" [for]="box.id">
                            {{box.label}}
                          </label>
                        </div>
                      </div>
                    }
                  </div>
                </div>
              }
              <!-- Slider toggle -->
              @if (filter.type === FilterType.SliderToggle) {
                <div>
                  @if (filter.name && filter.name.length > 0) {
                    <span class="control-label font-weight-bold">{{filter.name}}</span>
                  }
                  <div class="row slide-toggle-margin">
                    <div class="form-check form-switch">
                      <input class="form-check-input" 
                        type="checkbox"
                        role="switch"
                        [id]="filter.id"
                        [name]="filter.name"
                        [formControlName]="filter.id"
                        [checked]="filter.filterDefinition.onOption.isChecked">
                      <label class="form-check-label" [for]="filter.id">
                        @if (formGroup.get(filter.id)!.value) {
                          {{ filter.filterDefinition.onOption.label }}
                        } @else {
                          {{ filter.filterDefinition.offOption.label }}
                        }
                      </label>
                    </div>
                  </div>
                </div>
              }
            </div>
          }
        </div>
      </form>
      <div class="reset-button-container">
        <button class="btn btn-primary float-end"
          (click)="clearFilters()"
          [disabled]="searching() || !hasActiveFilters()">
          Reset Filters
        </button>
      </div>
    </div>
    </div>
  }
</div>
