// src/app/shared/components/custom-multi-select/custom-multi-select.component.ts
import { Component, input, output, forwardRef, signal, computed, OnInit, OnDestroy, ElementRef, inject } from '@angular/core';

import { FormsModule, ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

export type CustomMultiSelectOption = Record<string, any>;

export interface CustomMultiSelectGroup {
  name: string;
  items: CustomMultiSelectOption[];
}

@Component({
  selector: 'app-custom-multi-select',
  templateUrl: './custom-multi-select.component.html',
  styleUrls: ['./custom-multi-select.component.css'],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => CustomMultiSelectComponent),
      multi: true
    }
  ],
  imports: [FormsModule]
})
export class CustomMultiSelectComponent implements ControlValueAccessor, OnInit, OnDestroy {
  private elementRef = inject(ElementRef);
  
  id = input('');
  name = input('');
  items = input<CustomMultiSelectOption[]>([]);
  bindLabel = input('label');
  groupBy = input<string | null>(null);
  placeholder = input('Select items');
  multiple = input(true);
  markFirst = input(false);
  closeOnSelect = input(false);
  compareWith = input<(item: any, selected: any) => boolean>((a, b) => a === b);
  
  add = output<CustomMultiSelectOption>();
  remove = output<CustomMultiSelectOption>();
  clear = output<void>();

  // Internal state
  isOpen = signal(false);
  searchTerm = signal('');
  selectedItems = signal<CustomMultiSelectOption[]>([]);
  focusedIndex = signal(-1);
  
  // Filtered and grouped items
  filteredItems = computed(() => {
    const term = this.searchTerm().toLowerCase();
    if (!term) return this.items();
    
    return this.items().filter(item => {
      const label = this.getLabel(item).toLowerCase();
      return label.includes(term);
    });
  });

  groupedItems = computed(() => {
    const filtered = this.filteredItems();
    
    if (!this.groupBy()) {
      return [{ name: '', items: filtered }];
    }
    
    const groups = new Map<string, CustomMultiSelectOption[]>();
    
    filtered.forEach(item => {
      const groupValue = item[this.groupBy()!] || '';
      if (!groups.has(groupValue)) {
        groups.set(groupValue, []);
      }
      groups.get(groupValue)!.push(item);
    });
    
    return Array.from(groups.entries()).map(([name, items]) => ({ name, items }));
  });

  // ControlValueAccessor
  // eslint-disable-next-line @typescript-eslint/no-empty-function
  private onChange: any = () => {};
  // eslint-disable-next-line @typescript-eslint/no-empty-function
  private onTouched: any = () => {};
  disabled = false;

  writeValue(value: any): void {
    this.selectedItems.set(value || []);
  }

  registerOnChange(fn: any): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled;
  }

  // Helper methods
  getLabel(item: CustomMultiSelectOption): string {
    return item[this.bindLabel()] || '';
  }

  isSelected(item: CustomMultiSelectOption): boolean {
    return this.selectedItems().some(selected => 
      this.compareWith()(item, selected)
    );
  }

  toggleDropdown(): void {
    if (this.disabled) return;
    this.isOpen.set(!this.isOpen());
    if (this.isOpen()) {
      this.focusedIndex.set(-1);
      setTimeout(() => {
        const searchInput = document.querySelector('.custom-multi-select__search') as HTMLInputElement;
        searchInput?.focus();
      }, 0);
    } else {
      this.searchTerm.set('');
      this.onTouched();
    }
  }

  selectItem(item: CustomMultiSelectOption, event?: Event): void {
    if (event) {
      event.stopPropagation();
    }
    
    if (this.isSelected(item)) {
      this.deselectItem(item);
    } else {
      const newSelected = [...this.selectedItems(), item];
      this.selectedItems.set(newSelected);
      this.onChange(newSelected);
      this.add.emit(item);
      
      if (this.closeOnSelect()) {
        this.isOpen.set(false);
      }
    }
    
    this.searchTerm.set('');
    this.focusedIndex.set(-1);
  }

  deselectItem(item: CustomMultiSelectOption): void {
    const newSelected = this.selectedItems().filter(selected => 
      !this.compareWith()(item, selected)
    );
    this.selectedItems.set(newSelected);
    this.onChange(newSelected);
    this.remove.emit(item);
  }

  clearAll(event?: Event): void {
    if (event) {
      event.stopPropagation();
    }
    this.selectedItems.set([]);
    this.onChange([]);
    this.clear.emit();
  }

  onSearchInput(event: Event): void {
    const input = event.target as HTMLInputElement;
    this.searchTerm.set(input.value);
    this.focusedIndex.set(-1);
  }

  // Keyboard navigation
  onKeyDown(event: KeyboardEvent): void {
    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        this.moveFocus(1);
        break;
      case 'ArrowUp':
        event.preventDefault();
        this.moveFocus(-1);
        break;
      case 'Enter':
        event.preventDefault();
        if (this.focusedIndex() >= 0) {
          const flatItems = this.getFlatItems();
          const item = flatItems[this.focusedIndex()];
          if (item) {
            this.selectItem(item);
          }
        }
        break;
      case 'Escape':
        event.preventDefault();
        this.isOpen.set(false);
        this.searchTerm.set('');
        break;
    }
  }

  private moveFocus(direction: number): void {
    const flatItems = this.getFlatItems();
    const maxIndex = flatItems.length - 1;
    let newIndex = this.focusedIndex() + direction;
    
    if (newIndex < 0) newIndex = 0;
    if (newIndex > maxIndex) newIndex = maxIndex;
    
    this.focusedIndex.set(newIndex);
    
    // Scroll into view
    setTimeout(() => {
      const focusedElement = document.querySelector('.custom-multi-select__option--focused');
      focusedElement?.scrollIntoView({ block: 'nearest', behavior: 'smooth' });
    }, 0);
  }

  private getFlatItems(): CustomMultiSelectOption[] {
    return this.groupedItems().flatMap(group => group.items);
  }

  getItemIndex(item: CustomMultiSelectOption): number {
    const flatItems = this.getFlatItems();
    return flatItems.findIndex(i => this.compareWith()(i, item));
  }

  // Click outside handler
  onDocumentClick = (event: MouseEvent): void => {
    const target = event.target as HTMLElement;
    const hostElement = this.elementRef.nativeElement;
    if (hostElement && !hostElement.contains(target)) {
      this.isOpen.set(false);
      this.searchTerm.set('');
    }
  };

  ngOnInit(): void {
    document.addEventListener('click', this.onDocumentClick);
  }

  ngOnDestroy(): void {
    document.removeEventListener('click', this.onDocumentClick);
  }
}

<div [id]="id()" class="custom-multi-select" [class.custom-multi-select--open]="isOpen()" [class.custom-multi-select--disabled]="disabled">
  <!-- Selected values display / dropdown trigger -->
  <div class="custom-multi-select__control" 
       (click)="toggleDropdown()" 
       (keydown.enter)="toggleDropdown()"
       (keydown.space)="toggleDropdown(); $event.preventDefault()"
       tabindex="0" 
       role="combobox" 
       [attr.aria-expanded]="isOpen()" 
       [attr.aria-controls]="id() + '-listbox'"
       [attr.aria-label]="placeholder()">
    
    <!-- Selected items as chips -->
    @if (selectedItems().length > 0) {
      <div class="custom-multi-select__values">
        @for (item of selectedItems(); track $index) {
          <div class="custom-multi-select__value">
            <span class="custom-multi-select__value-label">{{ getLabel(item) }}</span>
            @if (groupBy() && item[groupBy()!]) {
              <span class="custom-multi-select__value-group">({{ item[groupBy()!] }})</span>
            }
            <button 
              type="button"
              class="custom-multi-select__value-remove" 
              (click)="deselectItem(item); $event.stopPropagation()"
              [attr.aria-label]="'Remove ' + getLabel(item)">
              ×
            </button>
          </div>
        }
      </div>
    }
    
    <!-- Placeholder when empty -->
    @if (selectedItems().length === 0) {
      <span class="custom-multi-select__placeholder">{{ placeholder() }}</span>
    }
    
    <!-- Clear all button -->
    @if (selectedItems().length > 0) {
      <button 
        type="button"
        class="custom-multi-select__clear" 
        (click)="clearAll($event)"
        aria-label="Clear all selections">
        ×
      </button>
    }
    
    <!-- Dropdown arrow -->
    <span class="custom-multi-select__arrow" [class.custom-multi-select__arrow--up]="isOpen()">
      <svg width="10" height="6" viewBox="0 0 10 6" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M1 1L5 5L9 1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    </span>
  </div>
  
  <!-- Dropdown panel -->
  @if (isOpen()) {
    <div class="custom-multi-select__dropdown" [id]="id() + '-listbox'" role="listbox" [attr.aria-label]="'Options for ' + placeholder()">
      
      <!-- Search input -->
      <div class="custom-multi-select__search-wrapper">
        <input 
          type="text"
          class="custom-multi-select__search"
          [value]="searchTerm()"
          (input)="onSearchInput($event)"
          (keydown)="onKeyDown($event)"
          placeholder="Search..."
          aria-label="Search options"
        />
      </div>
      
      <!-- Options list -->
      <div class="custom-multi-select__options">
        @if (groupedItems().length === 0 || filteredItems().length === 0) {
          <div class="custom-multi-select__no-results">No items found</div>
        }
        
        @for (group of groupedItems(); track group.name) {
          @if (group.items.length > 0) {
            
            <!-- Group header -->
            @if (groupBy() && group.name) {
              <div class="custom-multi-select__group-header">
                {{ group.name }}
              </div>
            }
            
            <!-- Group items -->
            @for (item of group.items; track $index) {
              <div 
                class="custom-multi-select__option"
                [class.custom-multi-select__option--selected]="isSelected(item)"
                [class.custom-multi-select__option--focused]="getItemIndex(item) === focusedIndex()"
                (click)="selectItem(item, $event)"
                (keydown.enter)="selectItem(item, $event)"
                (keydown.space)="selectItem(item, $event); $event.preventDefault()"
                tabindex="0"
                role="option"
                [attr.aria-selected]="isSelected(item)">
                
                <!-- Checkbox -->
                <span class="custom-multi-select__checkbox">
                  @if (isSelected(item)) {
                    <svg width="12" height="10" viewBox="0 0 12 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M1 5L4.5 8.5L11 1.5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                  }
                </span>
                
                <!-- Label -->
                <span class="custom-multi-select__option-label">{{ getLabel(item) }}</span>
              </div>
            }
          }
        }
      </div>
    </div>
  }
</div>

// src/app/components/filters/custom-multi-select.tsx
import { useEffect, useMemo, useRef, useState } from 'react';

export type CustomMultiSelectOption = Record<string, any>;

interface CustomMultiSelectProps {
  id?: string;
  items: CustomMultiSelectOption[];
  selected: CustomMultiSelectOption[];
  bindLabel?: string;
  groupBy?: string | null;
  placeholder?: string;
  disabled?: boolean;
  onChange: (selected: CustomMultiSelectOption[]) => void;
}

/** Same identity rules the Angular comparator used: `code`, then `_id`, then the value itself. */
function sameOption(item: any, other: any): boolean {
  if (item && other && Object.hasOwn(item, 'code')) return item.code === other.code;
  if (item && other && Object.hasOwn(item, '_id')) return item._id === other._id;
  return item === other;
}

export function CustomMultiSelect({
  id = '',
  items,
  selected,
  bindLabel = 'label',
  groupBy = null,
  placeholder = 'Select items',
  disabled = false,
  onChange,
}: CustomMultiSelectProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [focusedIndex, setFocusedIndex] = useState(-1);
  const hostRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!isOpen) return;
    function onDocumentClick(event: MouseEvent): void {
      if (hostRef.current && !hostRef.current.contains(event.target as Node)) {
        setIsOpen(false);
        setSearchTerm('');
      }
    }
    document.addEventListener('click', onDocumentClick);
    return () => document.removeEventListener('click', onDocumentClick);
  }, [isOpen]);

  const getLabel = (item: CustomMultiSelectOption): string => item[bindLabel] || '';

  const filteredItems = useMemo(() => {
    const term = searchTerm.toLowerCase();
    if (!term) return items;
    return items.filter((item) => (item[bindLabel] || '').toLowerCase().includes(term));
  }, [items, searchTerm, bindLabel]);

  const groupedItems = useMemo(() => {
    if (!groupBy) {
      return [{ name: '', items: filteredItems }];
    }
    const groups = new Map<string, CustomMultiSelectOption[]>();
    for (const item of filteredItems) {
      const groupValue = item[groupBy] || '';
      if (!groups.has(groupValue)) groups.set(groupValue, []);
      groups.get(groupValue)!.push(item);
    }
    return Array.from(groups.entries()).map(([name, groupItems]) => ({ name, items: groupItems }));
  }, [filteredItems, groupBy]);

  const flatItems = useMemo(() => groupedItems.flatMap((group) => group.items), [groupedItems]);

  const isSelected = (item: CustomMultiSelectOption): boolean =>
    selected.some((entry) => sameOption(item, entry));

  function toggleDropdown(): void {
    if (disabled) return;
    setIsOpen((open) => !open);
    setFocusedIndex(-1);
    setSearchTerm('');
  }

  function selectItem(item: CustomMultiSelectOption): void {
    if (isSelected(item)) {
      onChange(selected.filter((entry) => !sameOption(item, entry)));
    } else {
      onChange([...selected, item]);
    }
    setSearchTerm('');
    setFocusedIndex(-1);
  }

  function onKeyDown(event: React.KeyboardEvent): void {
    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        setFocusedIndex((index) => Math.min(flatItems.length - 1, index + 1));
        break;
      case 'ArrowUp':
        event.preventDefault();
        setFocusedIndex((index) => Math.max(0, index - 1));
        break;
      case 'Enter': {
        event.preventDefault();
        const item = flatItems[focusedIndex];
        if (item) selectItem(item);
        break;
      }
      case 'Escape':
        event.preventDefault();
        setIsOpen(false);
        setSearchTerm('');
        break;
    }
  }

  return (
    <div
      ref={hostRef}
      id={id}
      className={`custom-multi-select${isOpen ? ' custom-multi-select--open' : ''}${
        disabled ? ' custom-multi-select--disabled' : ''
      }`}
    >
      <div
        className="custom-multi-select__control"
        onClick={toggleDropdown}
        onKeyDown={(event) => {
          if (event.key === 'Enter' || event.key === ' ') {
            event.preventDefault();
            toggleDropdown();
          }
        }}
        tabIndex={0}
        role="combobox"
        aria-expanded={isOpen}
        aria-controls={`${id}-listbox`}
        aria-label={placeholder}
      >
        {selected.length > 0 ? (
          <div className="custom-multi-select__values">
            {selected.map((item, index) => (
              <div
                className="custom-multi-select__value"
                key={item['_id'] ?? item['code'] ?? index}
              >
                <span className="custom-multi-select__value-label">{getLabel(item)}</span>
                {groupBy && item[groupBy] && (
                  <span className="custom-multi-select__value-group">({item[groupBy]})</span>
                )}
                <button
                  type="button"
                  className="custom-multi-select__value-remove"
                  onClick={(event) => {
                    event.stopPropagation();
                    onChange(selected.filter((entry) => !sameOption(item, entry)));
                  }}
                  aria-label={`Remove ${getLabel(item)}`}
                >
                  ×
                </button>
              </div>
            ))}
          </div>
        ) : (
          <span className="custom-multi-select__placeholder">{placeholder}</span>
        )}

        {selected.length > 0 && (
          <button
            type="button"
            className="custom-multi-select__clear"
            onClick={(event) => {
              event.stopPropagation();
              onChange([]);
            }}
            aria-label="Clear all selections"
          >
            ×
          </button>
        )}

        <span
          className={`custom-multi-select__arrow${isOpen ? ' custom-multi-select__arrow--up' : ''}`}
        >
          <svg
            width="10"
            height="6"
            viewBox="0 0 10 6"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M1 1L5 5L9 1"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        </span>
      </div>

      {isOpen && (
        <div
          className="custom-multi-select__dropdown"
          id={`${id}-listbox`}
          role="listbox"
          aria-label={`Options for ${placeholder}`}
        >
          <div className="custom-multi-select__search-wrapper">
            <input
              type="text"
              className="custom-multi-select__search"
              value={searchTerm}
              onChange={(event) => {
                setSearchTerm(event.target.value);
                setFocusedIndex(-1);
              }}
              onKeyDown={onKeyDown}
              placeholder="Search..."
              aria-label="Search options"
              // eslint-disable-next-line jsx-a11y/no-autofocus -- focus moves into a panel the reader just opened, not on page load
              autoFocus
            />
          </div>

          <div className="custom-multi-select__options">
            {filteredItems.length === 0 && (
              <div className="custom-multi-select__no-results">No items found</div>
            )}

            {groupedItems.map((group) =>
              group.items.length === 0 ? null : (
                <div key={group.name}>
                  {groupBy && group.name && (
                    <div className="custom-multi-select__group-header">{group.name}</div>
                  )}
                  {group.items.map((item) => (
                    <div
                      key={item['_id'] ?? item['code'] ?? getLabel(item)}
                      className={`custom-multi-select__option${
                        isSelected(item) ? ' custom-multi-select__option--selected' : ''
                      }${flatItems[focusedIndex] === item ? ' custom-multi-select__option--focused' : ''}`}
                      onClick={(event) => {
                        event.stopPropagation();
                        selectItem(item);
                      }}
                      onKeyDown={(event) => {
                        if (event.key === 'Enter' || event.key === ' ') {
                          event.preventDefault();
                          selectItem(item);
                        }
                      }}
                      tabIndex={0}
                      role="option"
                      aria-selected={isSelected(item)}
                    >
                      <span className="custom-multi-select__checkbox">
                        {isSelected(item) && (
                          <svg
                            width="12"
                            height="10"
                            viewBox="0 0 12 10"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg"
                          >
                            <path
                              d="M1 5L4.5 8.5L11 1.5"
                              stroke="currentColor"
                              strokeWidth="2"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                            />
                          </svg>
                        )}
                      </span>
                      <span className="custom-multi-select__option-label">{getLabel(item)}</span>
                    </div>
                  ))}
                </div>
              ),
            )}
          </div>
        </div>
      )}
    </div>
  );
}
