// src/app/pages/project/commenting-tab.tsx
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router';
import { getAllByProjectId, isClosed, isNotStarted, isOpen } from 'app/api/commentperiod';
import type { CommentPeriod } from 'app/models/commentperiod';
import { mediumDate } from 'app/utils/utils';
import { useProjectContext } from './project-context';
import './commenting-tab.css';

/** Pulls the subject out of the boilerplate instructions text, e.g. "the Draft Application". */
function subjectFromInstructions(instructions: string): { subject: string; fullText: string } {
  const fullText = instructions
    ? instructions
        .replace(/<[^>]*>/g, ' ')
        .replace(/\s+/g, ' ')
        .trim()
    : '';
  const match = fullText.match(/Comment Period on the (.*?) for /);
  return { subject: match ? match[1] : '', fullText };
}

/**
 * Comment periods, deduplicated by id and — for ENGAGE-hosted ones — by the engagement they link
 * to, since the same engagement can be synced into more than one period.
 */
function toCards(periods: CommentPeriod[]): CommentPeriod[] {
  const seenIds = new Set<string>();
  const seenUrls = new Set<string>();

  return periods.filter((period) => {
    const { subject, fullText } = subjectFromInstructions(period.instructions);
    period.instructions = subject;
    period.additionalText = period.additionalText || fullText || period.informationLabel;

    if (seenIds.has(period._id)) return false;
    seenIds.add(period._id);
    if (period.isMet && period.metURL) {
      if (seenUrls.has(period.metURL)) return false;
      seenUrls.add(period.metURL);
    }
    return true;
  });
}

const SKELETON_CARDS = [1, 2];

export function CommentingTab() {
  const { projId } = useProjectContext();
  const navigate = useNavigate();

  const { data: commentPeriods, isPending } = useQuery({
    queryKey: ['comment-periods', projId],
    enabled: !!projId,
    queryFn: async () => {
      const res: any = await getAllByProjectId(projId);
      return res?.data ? toCards(res.data) : [];
    },
  });

  function goToCP(commentPeriod: CommentPeriod): void {
    if (commentPeriod.isMet && commentPeriod.metURL) {
      window.open(commentPeriod.metURL, '_blank');
    } else {
      navigate(`/p/${projId}/cp/${commentPeriod._id}`);
    }
  }

  if (isPending) {
    return (
      <>
        {SKELETON_CARDS.map((index) => (
          <div className="cp-card cp-card--skeleton" key={index}>
            <div className="cp-card__header">
              <div
                className="skeleton-cell"
                style={{ width: '90px', height: '12px', borderRadius: '4px' }}
              ></div>
              <div
                className="skeleton-cell"
                style={{ width: '70px', height: '20px', borderRadius: '999px', marginLeft: 'auto' }}
              ></div>
            </div>
            <div className="cp-card__body">
              <div
                className="skeleton-cell"
                style={{
                  width: '55%',
                  height: '14px',
                  borderRadius: '4px',
                  marginBottom: '0.5rem',
                }}
              ></div>
              <div
                className="skeleton-cell"
                style={{
                  width: '38%',
                  height: '11px',
                  borderRadius: '4px',
                  marginBottom: '0.5rem',
                }}
              ></div>
              <div
                className="skeleton-cell"
                style={{ width: '88%', height: '11px', borderRadius: '4px' }}
              ></div>
            </div>
          </div>
        ))}
      </>
    );
  }

  if (!commentPeriods || commentPeriods.length < 1) {
    return <div>No comment periods are currently scheduled for this project.</div>;
  }

  return (
    <>
      {commentPeriods.map((cp) => (
        <article className="card cp-card" key={cp._id}>
          <div className="cp-card__header">
            <span
              className={`cp-card__status-dot${isOpen(cp) ? ' cp-card__status-dot--open' : ''}${
                isNotStarted(cp) ? ' cp-card__status-dot--pending' : ''
              }${isClosed(cp) ? ' cp-card__status-dot--closed' : ''}`}
            ></span>
            <span className="cp-card__status-label">{cp.commentPeriodStatus}</span>
            {isOpen(cp) ? (
              <span className="cp-card__pill cp-card__pill--open">{cp.daysRemaining}</span>
            ) : isClosed(cp) ? (
              <span className="cp-card__pill cp-card__pill--closed">
                Closed {mediumDate(cp.dateCompleted)}
              </span>
            ) : isNotStarted(cp) ? (
              <span className="cp-card__pill cp-card__pill--pending">
                Starts {mediumDate(cp.dateStarted)}
              </span>
            ) : null}
          </div>
          <div className="cp-card__body">
            <h3 className="cp-card__title">
              {cp.informationLabel || cp.instructions || 'Public Comment Period'}
            </h3>
            {cp.dateStarted && (
              <p className="cp-card__dates">
                {mediumDate(cp.dateStarted)} – {mediumDate(cp.dateCompleted)}
              </p>
            )}
            {cp.additionalText && <p className="cp-card__description">{cp.additionalText}</p>}
            <button className="btn btn-epic-cta" onClick={() => goToCP(cp)}>
              {cp.commentPeriodStatus === 'Open' ? 'Share your thoughts' : 'View Engagement'}
            </button>
          </div>
        </article>
      ))}
    </>
  );
}

// src/app/project/commenting-tab/commenting-tab.component.ts
import { Component, inject, ChangeDetectionStrategy, effect, signal, DestroyRef } from '@angular/core';
import { DatePipe } from '@angular/common';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';

import { CommentPeriodService } from '../../services/commentperiod.service';
import { CommentPeriod } from '../../models/commentperiod';
import { StorageService } from '../../services/storage.service';

@Component({
  selector: 'app-commenting-tab',
  imports: [DatePipe],
  templateUrl: './commenting-tab.component.html',
  styleUrls: ['./commenting-tab.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class CommentingTabComponent {
  private router = inject(Router);
  private storageService = inject(StorageService);
  public commentPeriodService = inject(CommentPeriodService);
  private destroyRef = inject(DestroyRef);

  public readonly project = this.storageService.currentProject;
  public readonly commentPeriods = signal<CommentPeriod[]>([]);
  public readonly loading = signal(true);
  private loadedProjectId: string | null = null;
  private commentPeriodSub: Subscription | null = null;

  constructor() {
    effect(() => {
      const projectId = this.project()?._id;
      if (projectId && projectId !== this.loadedProjectId) {
        this.loadedProjectId = projectId;
        this.getCommentPeriods(projectId);
      }
    });
  }

  goToCP(commentPeriod: CommentPeriod) {
    const project = this.project();
    if (commentPeriod.isMet && commentPeriod.metURL) {
      window.open(commentPeriod.metURL, '_blank');
    } else if (project?._id) {
      this.router.navigate(['p', project._id, 'cp', commentPeriod._id]);
    }
  }

  getCommentPeriods(projectId: string) {
    this.commentPeriodSub?.unsubscribe();
    this.loading.set(true);
    this.commentPeriodSub = this.commentPeriodService.getAllByProjectId(projectId)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (res: any) => {
          if (res.data) {
            const periods = res.data.map((element: CommentPeriod) => {
              const fullText = element.instructions
                ? element.instructions.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim()
                : '';
              const match = fullText.match(/Comment Period on the (.*?) for /);
              return {
                ...element,
                instructions: match ? match[1] : '',
                additionalText: element.additionalText || fullText || element.informationLabel,
              };
            });
            this.commentPeriods.set(periods);
          }
          this.loading.set(false);
        },
        error: () => this.loading.set(false),
      });
  }

}

@if (loading()) {
  @for (i of [1, 2]; track i) {
    <div class="cp-card cp-card--skeleton">
      <div class="cp-card__header">
        <div class="skeleton-cell" style="width: 90px; height: 12px; border-radius: 4px"></div>
        <div class="skeleton-cell" style="width: 70px; height: 20px; border-radius: 999px; margin-left: auto"></div>
      </div>
      <div class="cp-card__body">
        <div class="skeleton-cell" style="width: 55%; height: 14px; border-radius: 4px; margin-bottom: 0.5rem"></div>
        <div class="skeleton-cell" style="width: 38%; height: 11px; border-radius: 4px; margin-bottom: 0.5rem"></div>
        <div class="skeleton-cell" style="width: 88%; height: 11px; border-radius: 4px"></div>
      </div>
    </div>
  }
} @else if (commentPeriods()!.length < 1) {
  <div>No comment periods are currently scheduled for this project.</div>
} @else {
  @for (cp of commentPeriods()!; track cp._id) {
    <article class="card cp-card">
      <div class="cp-card__header">
        <span class="cp-card__status-dot"
              [class.cp-card__status-dot--open]="commentPeriodService.isOpen(cp)"
              [class.cp-card__status-dot--pending]="commentPeriodService.isNotStarted(cp)"
              [class.cp-card__status-dot--closed]="commentPeriodService.isClosed(cp)">
        </span>
        <span class="cp-card__status-label">{{ cp.commentPeriodStatus }}</span>
        @if (commentPeriodService.isOpen(cp)) {
          <span class="cp-card__pill cp-card__pill--open">{{ cp.daysRemaining }}</span>
        } @else if (commentPeriodService.isClosed(cp)) {
          <span class="cp-card__pill cp-card__pill--closed">Closed {{ cp.dateCompleted | date:'MMM d, y' }}</span>
        } @else if (commentPeriodService.isNotStarted(cp)) {
          <span class="cp-card__pill cp-card__pill--pending">Starts {{ cp.dateStarted | date:'MMM d, y' }}</span>
        }
      </div>
      <div class="cp-card__body">
        <h3 class="cp-card__title">{{ cp.informationLabel || cp.instructions || 'Public Comment Period' }}</h3>
        @if (cp.dateStarted) {
          <p class="cp-card__dates">{{ cp.dateStarted | date:'MMM d, y' }} – {{ cp.dateCompleted | date:'MMM d, y' }}</p>
        }
        @if (cp.additionalText) {
          <p class="cp-card__description">{{ cp.additionalText }}</p>
        }
        <button class="btn btn-epic-cta" (click)="goToCP(cp)">
          {{ cp.commentPeriodStatus === 'Open' ? 'Share your thoughts' : 'View Engagement' }}
        </button>
      </div>
    </article>
  }
}
