// src/app/components/table/pagination.tsx
import { pageNumbers } from './table-object';

interface PaginationProps {
  currentPage?: number;
  pageSize?: number;
  totalItems?: number;
  ariaLabel?: string;
  onPageChange: (page: number) => void;
}

export function Pagination({
  currentPage = 1,
  pageSize = 10,
  totalItems = 0,
  ariaLabel = 'Pagination navigation',
  onPageChange
}: PaginationProps) {
  const totalPages = Math.ceil(totalItems / pageSize);

  if (totalPages <= 1) {
    return null;
  }

  function change(pageNum: number): void {
    if (pageNum === currentPage || pageNum < 1 || pageNum > totalPages) {
      return;
    }
    onPageChange(pageNum);
  }

  function keyActivate(event: React.KeyboardEvent, pageNum: number): void {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      change(pageNum);
    }
  }

  return (
    <nav aria-label={ariaLabel}>
      <ul className="pagination justify-content-center justify-content-md-end mb-0">
        <li className={`page-item${currentPage === 1 ? ' disabled' : ''}`}>
          <a
            className="page-link"
            role="button"
            tabIndex={0}
            onClick={() => change(currentPage - 1)}
            onKeyDown={event => keyActivate(event, currentPage - 1)}
            aria-label="Previous page"
          >
            &laquo;
          </a>
        </li>

        {pageNumbers(totalPages, currentPage).map((page, index) =>
          page === 'ellipsis' ? (
            <li className="page-item disabled" key={`ellipsis-${index}`}>
              <span className="page-link">…</span>
            </li>
          ) : (
            <li className={`page-item${page === currentPage ? ' active' : ''}`} key={page}>
              <a
                className="page-link"
                role="button"
                tabIndex={0}
                onClick={() => change(page)}
                onKeyDown={event => keyActivate(event, page)}
                aria-label={`Go to page ${page}`}
                aria-current={page === currentPage ? 'page' : undefined}
              >
                {page}
              </a>
            </li>
          )
        )}

        <li className={`page-item${currentPage >= totalPages ? ' disabled' : ''}`}>
          <a
            className="page-link"
            role="button"
            tabIndex={0}
            onClick={() => change(currentPage + 1)}
            onKeyDown={event => keyActivate(event, currentPage + 1)}
            aria-label="Next page"
          >
            &raquo;
          </a>
        </li>
      </ul>
    </nav>
  );
}

// src/app/shared/components/pagination/pagination.component.ts
import { Component, output, computed, input, ChangeDetectionStrategy } from '@angular/core';


@Component({
  selector: 'lib-pagination',
  templateUrl: './pagination.component.html',
  styleUrl: './pagination.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [],
})
export class PaginationComponent {
  // Input signals - automatically reactive
  currentPage = input<number>(1);
  pageSize = input<number>(10);
  totalItems = input<number>(0);
  ariaLabel = input<string>('Pagination navigation');

  pageChange = output<number>();

  /**
   * Computed signal for total number of pages
   */
  protected totalPages = computed(() => {
    const total = this.totalItems();
    const size = this.pageSize();
    return Math.ceil(total / size);
  });

  /**
   * Computed signal for page numbers with ellipsis logic
   */
  protected pageNumbers = computed(() => {
    const total = this.totalPages();
    const current = this.currentPage();
    
    if (total <= 7) {
      return Array.from({ length: total }, (_, i) => i + 1);
    }
    
    const pages: (number | 'ellipsis')[] = [1];
    
    let startPage = Math.max(2, current - 2);
    let endPage = Math.min(total - 1, current + 2);
    
    if (current <= 4) {
      endPage = Math.min(5, total - 1);
    }
    
    if (current >= total - 3) {
      startPage = Math.max(2, total - 4);
    }
    
    if (startPage > 2) {
      pages.push('ellipsis');
    }
    
    for (let i = startPage; i <= endPage; i++) {
      pages.push(i);
    }
    
    if (endPage < total - 1) {
      pages.push('ellipsis');
    }
    
    if (total > 1) {
      pages.push(total);
    }
    
    return pages;
  });

  /**
   * Computed signal to check if Previous button should be disabled
   */
  protected isPreviousDisabled = computed(() => {
    return this.currentPage() === 1;
  });

  /**
   * Computed signal to check if Next button should be disabled
   */
  protected isNextDisabled = computed(() => {
    return this.currentPage() >= this.totalPages();
  });

  /**
   * Handle page change with validation
   */
  public onPageChange(pageNum: number): void {
    if (pageNum === this.currentPage() || pageNum < 1 || pageNum > this.totalPages()) {
      return;
    }
    this.pageChange.emit(pageNum);
  }

  /**
   * Type guard to check if pagination item is ellipsis
   */
  public isEllipsis(item: number | 'ellipsis'): boolean {
    return item === 'ellipsis';
  }

  /**
   * Convert page item to number (for type safety in template)
   */
  public asPageNumber(item: number | 'ellipsis'): number {
    return item as number;
  }
}

@if (totalPages() > 1) {
<nav [attr.aria-label]="ariaLabel()">
  <ul class="pagination justify-content-center justify-content-md-end mb-0">
    <li class="page-item" [class.disabled]="isPreviousDisabled()">
      <a class="page-link" 
         role="button"
         tabindex="0"
         (click)="onPageChange(currentPage() - 1)"
         (keydown.enter)="onPageChange(currentPage() - 1)"
         (keydown.space)="onPageChange(currentPage() - 1)"
         aria-label="Previous page">&laquo;</a>
    </li>

    @for (page of pageNumbers(); track $index) {
      @if (isEllipsis(page)) {
        <li class="page-item disabled">
          <span class="page-link">…</span>
        </li>
      } @else {
        <li class="page-item" [class.active]="page === currentPage()">
          <a class="page-link"
             role="button"
             tabindex="0"
             (click)="onPageChange(asPageNumber(page))"
             (keydown.enter)="onPageChange(asPageNumber(page))"
             (keydown.space)="onPageChange(asPageNumber(page))"
             [attr.aria-label]="'Go to page ' + page"
             [attr.aria-current]="page === currentPage() ? 'page' : null">{{ page }}</a>
        </li>
      }
    }

    <li class="page-item" [class.disabled]="isNextDisabled()">
      <a class="page-link"
         role="button"
         tabindex="0"
         (click)="onPageChange(currentPage() + 1)"
         (keydown.enter)="onPageChange(currentPage() + 1)"
         (keydown.space)="onPageChange(currentPage() + 1)"
         aria-label="Next page">&raquo;</a>
    </li>
  </ul>
</nav>
}
