// src/app/pages/projects/projlist-map.tsx
import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import type { Project } from 'app/models/project';
import { logger } from 'app/config/logging';
import { baseLayerName, mapBounds } from 'app/state/map-ui';
import { ProjDetailPopup } from './proj-detail-popup';
import './projlist-map.css';

interface ProjlistMapProps {
  projects: Project[];
  loading: boolean;
  /** The filter bar, measured to keep markers clear of it when fitting bounds. */
  filtersRef: React.RefObject<HTMLDivElement | null>;
  hasActiveSearch: boolean;
  showSearchMobile: boolean;
  onCloseSearchMobile: () => void;
  onToggleCurrentApp: (project: Project) => void;
}

const MOBILE_BREAKPOINT = 768;
const VISIBILITY_UPDATE_DEBOUNCE_MS = 100;
const BC_CENTER: [number, number] = [55.5, -125.5];
const DEFAULT_ZOOM = 5.7;

// Built on first use rather than at module load, because L is a CDN global.
let icons: { normal: any; large: any } | null = null;
function markerIcons(): { normal: any; large: any } {
  icons ??= {
    normal: L.icon({
      iconUrl: 'assets/images/marker-icon-yellow.svg',
      iconSize: [36, 36],
      iconAnchor: [18, 36],
      tooltipAnchor: [16, -28],
      className: 'marker-icon-transition'
    }),
    large: L.icon({
      iconUrl: 'assets/images/marker-icon-yellow-lg.svg',
      iconSize: [48, 48],
      iconAnchor: [24, 48],
      className: 'marker-icon-transition'
    })
  };
  return icons;
}

function createBaseLayers(): Record<string, any> {
  return {
    'Nat Geo World Map': L.tileLayer(
      'https://server.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/tile/{z}/{y}/{x}',
      { attribution: 'Tiles &copy; Esri', maxZoom: 16, noWrap: true }
    ),
    'World Topographic': L.tileLayer(
      'https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}',
      { attribution: 'Tiles &copy; Esri', maxZoom: 16, noWrap: true }
    ),
    'World Imagery': L.tileLayer(
      'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
      { attribution: 'Tiles &copy; Esri', maxZoom: 17, noWrap: true }
    )
  };
}

/** BC only: anything outside this box is bad data, not a project somewhere else. */
function hasValidCentroid(project: Project): boolean {
  if (!project.centroid || project.centroid.length !== 2) return false;

  const [lon, lat] = project.centroid;
  if (typeof lon !== 'number' || typeof lat !== 'number') {
    logger.warn(`Invalid centroid type for project ${project._id}: [${typeof lon}, ${typeof lat}]`, 'ProjlistMap');
    return false;
  }
  if (isNaN(lon) || isNaN(lat)) {
    logger.warn(`NaN centroid for project ${project._id}`, 'ProjlistMap');
    return false;
  }
  if (lat < 48 || lat > 60 || lon < -139 || lon > -114) {
    logger.warn(`Out-of-range centroid for project ${project._id}: [${lon}, ${lat}]`, 'ProjlistMap');
    return false;
  }
  return true;
}

function expandBounds(bounds: any, percent: number): any {
  const expandLat = (bounds.getNorth() - bounds.getSouth()) * percent;
  const expandLng = (bounds.getEast() - bounds.getWest()) * percent;
  return L.latLngBounds(
    L.latLng(bounds.getSouth() - expandLat, bounds.getWest() - expandLng),
    L.latLng(bounds.getNorth() + expandLat, bounds.getEast() + expandLng)
  );
}

export function ProjlistMap({
  projects,
  loading,
  filtersRef,
  hasActiveSearch,
  showSearchMobile,
  onCloseSearchMobile,
  onToggleCurrentApp
}: ProjlistMapProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<any>(null);
  const clusterRef = useRef<any>(null);
  const markersRef = useRef(new Map<string, any>());
  const popupRef = useRef<any>(null);

  const visibilityTimeout = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const autoSelectTimeout = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const recentlyClosedTimeout = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const recentlyClosedId = useRef<string | null>(null);
  const lastAutoSelectedId = useRef<string | null>(null);
  const autoSelectInProgress = useRef(false);
  const isPopupOpening = useRef(false);
  /** Set when a fit was asked for before the container had a size; the resize observer replays it. */
  const pendingFit = useRef(false);

  // The node Leaflet renders the popup into; React fills it through a portal.
  const [popupHost] = useState(() => {
    const host = document.createElement('div');
    host.className = 'app-proj-detail-popup';
    return host;
  });
  const [popupProject, setPopupProject] = useState<Project | null>(null);
  const [singleVisibleId, setSingleVisibleId] = useState<string | null>(null);

  // Leaflet callbacks outlive the render that created them, so they read props through this ref.
  const latest = useRef({
    projects,
    filtersRef,
    hasActiveSearch,
    showSearchMobile,
    onCloseSearchMobile,
    onToggleCurrentApp,
    popupProject,
    singleVisibleId
  });
  useEffect(() => {
    latest.current = {
      projects,
      filtersRef,
      hasActiveSearch,
      showSearchMobile,
      onCloseSearchMobile,
      onToggleCurrentApp,
      popupProject,
      singleVisibleId
    };
  });

  const isMobile = (): boolean => window.innerWidth <= MOBILE_BREAKPOINT;

  /** Where the filter bar ends, so fitted bounds and popups stay below it. */
  function filterHeight(): number {
    const host = latest.current.filtersRef.current;
    const inner = host?.firstElementChild?.firstElementChild as HTMLElement | undefined;
    return host ? host.offsetTop + (inner?.clientHeight ?? 0) : 0;
  }

  function fitBounds(bounds: any): void {
    const map = mapRef.current;
    if (!map || !bounds?.isValid()) return;
    if (map.getSize().x === 0 || map.getSize().y === 0) {
      pendingFit.current = true;
      return;
    }
    pendingFit.current = false;

    const mobile = isMobile();
    map.fitBounds(expandBounds(bounds, mobile ? 0.05 : 0.08), {
      paddingTopLeft: L.point(mobile ? 20 : 100, mobile ? 50 : filterHeight() + 80),
      paddingBottomRight: L.point(mobile ? 20 : 100, mobile ? 50 : 80),
      animate: false,
      maxZoom: 10
    });
  }

  function fitToMarkers(): void {
    const cluster = clusterRef.current;
    if (cluster) fitBounds(cluster.getBounds());
  }

  /** Exactly one marker in view is the trigger for auto-opening its popup; nothing else reads this. */
  function updateVisibility(): void {
    const map = mapRef.current;
    if (!map) return;
    const bounds = map.getBounds();
    let visibleId: string | null = null;
    let count = 0;
    markersRef.current.forEach((marker, id) => {
      if (bounds.contains(marker.getLatLng())) {
        count += 1;
        visibleId = id;
      }
    });
    setSingleVisibleId(count === 1 ? visibleId : null);
  }

  function scheduleVisibilityUpdate(): void {
    if (autoSelectInProgress.current) return;
    clearTimeout(visibilityTimeout.current);
    visibilityTimeout.current = setTimeout(updateVisibility, VISIBILITY_UPDATE_DEBOUNCE_MS);
  }

  function centerMapOnMarker(marker: any): void {
    const map = mapRef.current;
    if (!map) return;
    const offset = isMobile() ? 150 : filterHeight() / 2 + 180;
    const point = map.latLngToContainerPoint(marker.getLatLng());
    map.panTo(map.containerPointToLatLng(L.point(point.x, point.y - offset)), { animate: true, duration: 0.25 });
  }

  function createProjectPopup(project: Project, marker: any): void {
    if (isPopupOpening.current) {
      logger.warn('Popup creation already in progress', 'ProjlistMap');
      return;
    }
    const map = mapRef.current;
    if (!map || !marker || !clusterRef.current?.hasLayer(marker)) {
      logger.error('Cannot create popup: map or marker not ready', 'ProjlistMap');
      return;
    }

    map.closePopup();

    const existingPopup = marker.getPopup();
    if (existingPopup?.isOpen()) {
      marker.closePopup();
      return;
    }

    try {
      isPopupOpening.current = true;
      setPopupProject(project);
      latest.current.onToggleCurrentApp(project);

      const viewportWidth = window.innerWidth;
      const isNarrow = viewportWidth < 400;
      const popup = L.popup({
        className: 'map-popup-content',
        autoPan: false,
        offset: L.point(0, -30),
        closeButton: true,
        maxWidth: isNarrow ? Math.min(viewportWidth - 40, 280) : 300,
        minWidth: isNarrow ? Math.min(viewportWidth - 60, 220) : 250
      })
        .setLatLng(marker.getLatLng())
        .setContent(popupHost)
        .on('remove', () => {
          latest.current.onToggleCurrentApp(project);
          setPopupProject(null);
          // Stops the auto-open effect from immediately reopening what was just dismissed.
          recentlyClosedId.current = project._id;
          clearTimeout(recentlyClosedTimeout.current);
          recentlyClosedTimeout.current = setTimeout(() => {
            recentlyClosedId.current = null;
          }, 500);
        });

      if (existingPopup) marker.unbindPopup();
      marker.bindPopup(popup).openPopup();
      popupRef.current = popup;

      isPopupOpening.current = false;
      autoSelectInProgress.current = false;
      updateVisibility();
    } catch (error) {
      logger.error('Failed to create popup', 'ProjlistMap', error);
      setPopupProject(null);
      isPopupOpening.current = false;
      autoSelectInProgress.current = false;
    }
  }

  function selectMarker(project: Project, marker: any, isAutoSelect = false): void {
    if (isMobile()) {
      // An auto-select while the visitor is mid-search should not close the search panel on them.
      if ((!isAutoSelect || !latest.current.hasActiveSearch) && latest.current.showSearchMobile) {
        latest.current.onCloseSearchMobile();
      }
    }

    centerMapOnMarker(marker);

    if (isAutoSelect) {
      clearTimeout(autoSelectTimeout.current);
      autoSelectTimeout.current = setTimeout(() => createProjectPopup(project, marker), 300);
    } else {
      createProjectPopup(project, marker);
    }
  }

  function createMarker(project: Project): any {
    const marker = L.marker(L.latLng(project.centroid[1], project.centroid[0]), {
      title: `${project.name}\n${project.sector}\n${project.location}`
    })
      .setIcon(markerIcons().normal)
      .on('click', () => selectMarker(project, marker, false));
    return marker;
  }

  /** Reuses the markers that survive a filter change instead of redrawing the whole layer. */
  function updateMarkers(nextProjects: Project[]): void {
    const cluster = clusterRef.current;
    if (!mapRef.current || !cluster) return;

    const valid = nextProjects.filter(hasValidCentroid);
    const ids = new Set(valid.map(project => project._id));

    const toRemove: any[] = [];
    markersRef.current.forEach((marker, id) => {
      if (!ids.has(id)) {
        toRemove.push(marker);
        markersRef.current.delete(id);
      }
    });

    const toAdd: any[] = [];
    for (const project of valid) {
      const existing = markersRef.current.get(project._id);
      if (!existing) {
        const marker = createMarker(project);
        markersRef.current.set(project._id, marker);
        toAdd.push(marker);
      } else {
        const latLng = L.latLng(project.centroid[1], project.centroid[0]);
        if (!existing.getLatLng().equals(latLng)) existing.setLatLng(latLng);
      }
    }

    if (toRemove.length > 0) cluster.removeLayers(toRemove);
    if (toAdd.length > 0) cluster.addLayers(toAdd);

    scheduleVisibilityUpdate();
  }

  // Create the map once. Everything else updates the instance in place.
  useEffect(() => {
    const element = containerRef.current;
    if (!element) {
      logger.error('Map container not found', 'ProjlistMap');
      return;
    }

    const cluster = L.markerClusterGroup({
      showCoverageOnHover: false,
      maxClusterRadius: 60,
      spiderfyOnMaxZoom: true,
      zoomToBoundsOnClick: true,
      disableClusteringAtZoom: 10,
      removeOutsideVisibleBounds: true,
      animate: true,
      animateAddingMarkers: false,
      spiderfyDistanceMultiplier: 1.5
    });
    clusterRef.current = cluster;

    const map = L.map(element, {
      center: BC_CENTER,
      zoom: DEFAULT_ZOOM,
      zoomControl: false,
      maxBounds: L.latLngBounds(L.latLng(-90, -180), L.latLng(90, 180)),
      maxZoom: 17,
      minZoom: 4,
      zoomSnap: 0.1,
      attributionControl: false
    });
    mapRef.current = map;

    map.on('moveend', () => {
      const bounds = map.getBounds();
      mapBounds.set({
        north: bounds.getNorth(),
        south: bounds.getSouth(),
        east: bounds.getEast(),
        west: bounds.getWest()
      });
      scheduleVisibilityUpdate();
    });
    map.on('baselayerchange', (event: any) => baseLayerName.set(event.name));

    map.addLayer(cluster);

    const baseLayers = createBaseLayers();
    map.addLayer(baseLayers[baseLayerName.get()] ?? baseLayers['World Topographic']);

    L.control.scale({ position: 'bottomleft' }).addTo(map);
    L.control.layers(baseLayers, undefined, { position: 'bottomleft' }).addTo(map);
    L.control.zoom({ position: 'bottomright' }).addTo(map);

    const ResetViewControl = L.Control.extend({
      options: { position: 'bottomright' },
      onAdd: () => {
        const button = L.DomUtil.create('button');
        button.title = 'Reset view';
        button.innerText = 'refresh';
        button.onclick = () => map.setView(BC_CENTER, DEFAULT_ZOOM);
        button.className = 'material-icons map-reset-control';
        L.DomEvent.disableClickPropagation(button);
        L.DomEvent.disableScrollPropagation(button);
        return button;
      }
    });
    map.addControl(new ResetViewControl());

    const initialBounds = map.getBounds();
    mapBounds.set({
      north: initialBounds.getNorth(),
      south: initialBounds.getSouth(),
      east: initialBounds.getEast(),
      west: initialBounds.getWest()
    });

    // The map is created before the flex layout has given the container its height, so Leaflet
    // needs telling once it has one. This also replays a fit that was asked for too early.
    const observer =
      typeof ResizeObserver === 'undefined'
        ? null
        : new ResizeObserver(() => {
            map.invalidateSize(true);
            if (pendingFit.current) fitToMarkers();
          });
    observer?.observe(element);

    const markers = markersRef.current;
    return () => {
      observer?.disconnect();
      clearTimeout(visibilityTimeout.current);
      clearTimeout(autoSelectTimeout.current);
      clearTimeout(recentlyClosedTimeout.current);
      cluster.clearLayers();
      markers.clear();
      map.remove();
      mapRef.current = null;
      clusterRef.current = null;
      popupRef.current = null;
      mapBounds.set(null);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Markers follow the filtered project list.
  useEffect(() => {
    if (!mapRef.current) return;
    // A new project list means new candidates for auto-select.
    lastAutoSelectedId.current = null;
    autoSelectInProgress.current = false;

    updateMarkers(projects);

    if (!latest.current.popupProject && !latest.current.singleVisibleId) {
      fitToMarkers();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projects]);

  // Open the popup by itself once filtering has narrowed the map down to a single project.
  useEffect(() => {
    if (!singleVisibleId || popupProject) return;
    if (autoSelectInProgress.current) return;
    if (lastAutoSelectedId.current === singleVisibleId) return;
    if (recentlyClosedId.current === singleVisibleId) return;

    const project = projects.find(item => item._id === singleVisibleId);
    const marker = markersRef.current.get(singleVisibleId);
    if (!project || !marker) return;

    autoSelectInProgress.current = true;
    lastAutoSelectedId.current = singleVisibleId;
    selectMarker(project, marker, true);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [singleVisibleId, popupProject, projects]);

  // The project with the open popup gets the large marker; every other marker is reset.
  useEffect(() => {
    if (!mapRef.current) return;
    const { normal, large } = markerIcons();
    markersRef.current.forEach((marker, id) => {
      marker.setIcon(id === popupProject?._id ? large : normal);
    });
    // Leaflet sized the popup around an empty node, so re-measure now that React has filled it.
    popupRef.current?.update?.();
  }, [popupProject]);

  return (
    <div className="app-map">
      <div className={`map-container${loading ? ' loading' : ''}`}>
        <div ref={containerRef} id="map" aria-label="Map of B.C. that displays EAO Projects" />
      </div>
      {popupProject && createPortal(<ProjDetailPopup project={popupProject} />, popupHost)}
    </div>
  );
}

// src/app/projects/projlist-map/projlist-map.component.ts
import {
  Component,
  AfterViewInit,
  OnDestroy,
  input,
  output,
  effect,
  untracked,
  ElementRef,
  Injector,
  ViewContainerRef,
  ViewChild,
  inject,
  computed
} from '@angular/core';
import { Subject } from 'rxjs';


import { Project } from '../../models/project';
import { ConfigService } from '../../services/config.service';
import { MapStateService } from '../../services/map-state.service';
import { LoggingService } from '../../services/logging.service';
import { LoadingStateService } from '../../services/loading-state.service';
import { FilterStateService } from '../../services/filter-state.service';
import { ProjDetailPopupComponent } from '../proj-detail-popup/proj-detail-popup.component';

const markerIconYellow = L.icon({
  iconUrl: 'assets/images/marker-icon-yellow.svg',
  iconSize: [36, 36],
  iconAnchor: [18, 36],
  tooltipAnchor: [16, -28],
  className: 'marker-icon-transition'
});

const markerIconYellowLg = L.icon({
  iconUrl: 'assets/images/marker-icon-yellow-lg.svg',
  iconSize: [48, 48],
  iconAnchor: [24, 48],
  className: 'marker-icon-transition'
});

@Component({
  selector: 'app-projlist-map',
  templateUrl: './projlist-map.component.html',
  styleUrls: ['./projlist-map.component.css'],
  standalone: true
})
export class ProjlistMapComponent implements AfterViewInit, OnDestroy {
  @ViewChild('mapContainer', { static: true }) mapContainer!: ElementRef<HTMLDivElement>;

  projects = input<Project[]>([]);
  applist = input<any>();
  appfilters = input<any>();
  reloadApps = output<void>();

  private elementRef = inject(ElementRef);
  public configService = inject(ConfigService);
  private mapStateService = inject(MapStateService);
  private filterState = inject(FilterStateService);
  private injector = inject(Injector);
  private viewContainerRef = inject(ViewContainerRef);
  private logger = inject(LoggingService);
  private loadingState = inject(LoadingStateService);

  private map: any = null;
  private markerClusterGroup!: any;
  // Map loading state - observes loading states from services that make API calls
  // - storage-preload: StorageService background preload
  // - projects-full-page-1: ProjectService.getAllFull() when cache not available
  public loading = computed(() =>
    this.loadingState.getOperationState('storage-preload')() ||
    this.loadingState.getOperationState('projects-full-page-1')()
  );
  // Constants
  private readonly MOBILE_BREAKPOINT = 768;
  private readonly VISIBILITY_UPDATE_DEBOUNCE_MS = 100;

  private destroy$ = new Subject<void>();
  private resizeObserver?: ResizeObserver;
  private isPopupOpening = false; // Guard against concurrent popup creation
  private recentlyClosedProjectId: string | null = null; // Track manual closes to prevent immediate reopen
  private recentlyClosedTimeout?: ReturnType<typeof setTimeout>;
  private autoSelectInProgress = false; // Guard against multiple auto-select calls
  private lastAutoSelectedProjectId: string | null = null; // Track last auto-selected project

  // Popup component instance for reuse
  private popupComponentRef: any = null;

  /**
   * Check if current viewport is mobile size
   */
  private isMobile(): boolean {
    return window.innerWidth <= this.MOBILE_BREAKPOINT;
  }

  /**
   * Get filter bar height for layout calculations
   */
  private getFilterHeight(): number {
    const appfiltersValue = this.appfilters();
    return appfiltersValue?.clientHeight || 0;
  }

  /**
   * Calculate padding values for map bounds fitting.
   * The goal is to center markers in the visible map area (below filters).
   */
  private calculateFitBoundsPadding(): { top: number; side: number; bottom: number; expansion: number } {
    const isMobile = this.isMobile();
    const filterHeight = this.getFilterHeight();

    // Use balanced padding for proper centering
    // Increased horizontal padding from 50 to 100 to provide better visual balance
    // and prevent markers from appearing too close to viewport edges
    const topPadding = isMobile ? 50 : filterHeight + 80;
    const bottomPadding = isMobile ? 50 : 80;

    return {
      top: topPadding,
      bottom: bottomPadding,
      side: isMobile ? 20 : 100,
      expansion: isMobile ? 0.05 : 0.08
    };
  }

  /**
   * Calculate vertical offset for centering markers with popups
   */
  private calculatePopupOffset(): number {
    const filterHeight = this.getFilterHeight();
    return (filterHeight / 2) + 180;
  }

  constructor() {
    // Watch for filter changes to reset auto-select tracking
    effect(() => {
      // Track any filter change
      this.filterState.applicantFilter();
      this.filterState.selectedRegions();
      this.filterState.selectedPhases();
      this.filterState.selectedTypes();
      
      untracked(() => {
        // Reset auto-select tracking when filters change to allow new auto-select
        this.lastAutoSelectedProjectId = null;
        this.autoSelectInProgress = false;
      });
    });

    // Watch for project changes and update markers
    effect(() => {
      const currentProjects = this.projects();

      if (!this.map || !this.markerClusterGroup) {
        return;
      }

      untracked(() => {
        this.updateMarkers(currentProjects);

        const hasActivePopup = this.mapStateService.activePopupProject();
        const singleVisible = this.mapStateService.singleVisibleProject();

        // Don't auto-fit if popup is open OR we're about to auto-open one
        if (!hasActivePopup && !singleVisible) {
          const bounds = this.markerClusterGroup.getBounds();
          if (bounds.isValid()) {
            this.fitBounds(bounds);
          }
        }
      });
    });

    // Watch for active popup changes to highlight marker
    effect(() => {
      const activeProjectId = this.mapStateService.activePopupProject();

      untracked(() => {
        this.highlightMarker(activeProjectId);
      });
    });

    // Auto-select marker when exactly one is visible
    effect(() => {
      const shouldAutoOpen = this.mapStateService.shouldAutoOpenPopup();
      const singleVisible = this.mapStateService.singleVisibleProject();

      if (shouldAutoOpen && singleVisible) {
        untracked(() => {
          // Prevent multiple auto-select calls for the same project
          if (this.autoSelectInProgress || this.lastAutoSelectedProjectId === singleVisible.projectId) {
            return;
          }

          this.autoSelectMarker();
        });
      }
    });
  }

  ngAfterViewInit(): void {
    // Wait for container to have dimensions before initializing
    this.waitForContainer();
  }

  /**
   * Incrementally update markers based on project changes.
   * Reuses existing markers when possible instead of full redraw.
   */
  private updateMarkers(projects: Project[]): void {
    if (!this.map || !this.markerClusterGroup) {
      return;
    }

    const currentMarkers = this.mapStateService.getAllMarkers();
    const projectIds = new Set(projects.filter(p => this.hasValidCentroid(p)).map(p => p._id));

    // Batch marker operations
    const markersToRemove: any[] = [];
    const markersToAdd: any[] = [];

    // Collect markers to remove
    currentMarkers.forEach((markerState, projectId) => {
      if (!projectIds.has(projectId)) {
        markersToRemove.push(markerState.marker);
        this.mapStateService.removeMarker(projectId);
      }
    });

    // Collect markers to add or update
    projects.forEach(project => {
      if (this.hasValidCentroid(project)) {
        const existingMarker = this.mapStateService.getMarker(project._id);

        if (!existingMarker) {
          const marker = this.createMarker(project);
          this.mapStateService.setMarker(project._id, marker, true);
          markersToAdd.push(marker);
        } else {
          const newLatLng = L.latLng(project.centroid[1], project.centroid[0]);
          if (!existingMarker.getLatLng().equals(newLatLng)) {
            existingMarker.setLatLng(newLatLng);
          }
        }
      }
    });

    // Apply batch operations
    if (markersToRemove.length > 0) {
      this.markerClusterGroup.removeLayers(markersToRemove);
    }
    if (markersToAdd.length > 0) {
      this.markerClusterGroup.addLayers(markersToAdd);
    }

    this.updateVisibleProjects();
  }

  /**
   * Check if project has valid centroid coordinates
   */
  private hasValidCentroid(project: Project): boolean {
    if (!project.centroid || project.centroid.length !== 2) {
      return false;
    }
    
    const lon = project.centroid[0];
    const lat = project.centroid[1];
    
    // Reject if coordinates are not numbers (e.g., DMS strings)
    if (typeof lon !== 'number' || typeof lat !== 'number') {
      this.logger.warn(
        `Invalid centroid type for project ${project._id}: [${typeof lon}, ${typeof lat}]`,
        'ProjlistMapComponent'
      );
      return false;
    }
    
    // Reject NaN values
    if (isNaN(lon) || isNaN(lat)) {
      this.logger.warn(
        `NaN centroid for project ${project._id}`,
        'ProjlistMapComponent'
      );
      return false;
    }
    
    // Reject out-of-range coordinates (BC: roughly lat 48-60, lon -139 to -114)
    if (lat < 48 || lat > 60 || lon < -139 || lon > -114) {
      this.logger.warn(
        `Out-of-range centroid for project ${project._id}: [${lon}, ${lat}]`,
        'ProjlistMapComponent'
      );
      return false;
    }
    
    return true;
  }

  readonly defaultBounds = L.latLngBounds([48, -139], [60, -114]);
  // Center of BC coordinates
  readonly bcCenter: any = [55.5, -125.5];
  readonly defaultZoom = 5.7;

  /**
   * Wait for map container to have dimensions before initializing
   * This prevents Leaflet from initializing with height: 0
   * Ref: https://github.com/Leaflet/Leaflet/issues/4835
   */
  private waitForContainer(): void {
    const container = this.mapContainer?.nativeElement;
    if (!container) {
      this.logger.error('Map container not found', 'ProjlistMapComponent');
      return;
    }

    // Check if container has dimensions
    const rect = container.getBoundingClientRect();
    if (rect.height > 0 && rect.width > 0) {
      this.initializeMap();
    } else {
      // Wait a bit and try again
      setTimeout(() => this.waitForContainer(), 50);
    }
  }

  private initializeMap(): void {
    const mapElement = this.mapContainer?.nativeElement;
    if (!mapElement) {
      this.logger.error('Map container not found', 'ProjlistMapComponent');
      return;
    }

    // Create fresh marker cluster group
    this.markerClusterGroup = L.markerClusterGroup({
      showCoverageOnHover: false,
      maxClusterRadius: 60,
      spiderfyOnMaxZoom: true,
      zoomToBoundsOnClick: true,
      disableClusteringAtZoom: 10,
      removeOutsideVisibleBounds: true,
      animate: true,
      animateAddingMarkers: false,
      spiderfyDistanceMultiplier: 1.5
    });

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    // Create reset view control
    const resetViewControl = L.Control.extend({
      options: { position: 'bottomright' },
      onAdd: function () {
        const element = L.DomUtil.create('button');
        element.title = 'Reset view';
        element.innerText = 'refresh';
        element.onclick = () => self.resetView();
        element.className = 'material-icons map-reset-control';
        L.DomEvent.disableClickPropagation(element);
        L.DomEvent.disableScrollPropagation(element);
        return element;
      },
    });

    // Define base layers
    const baseLayers = this.createBaseLayers();

    // Initialize map centered on BC
    this.map = L.map(mapElement, {
      center: this.bcCenter,
      zoom: this.defaultZoom,
      zoomControl: false,
      maxBounds: L.latLngBounds(L.latLng(-90, -180), L.latLng(90, 180)),
      maxZoom: 17,
      minZoom: 4,
      zoomSnap: 0.1,
      attributionControl: false
    });

    // Store map reference in state service
    if (this.map) {
      this.mapStateService.setMap(this.map);

      // Add event listeners
      this.map.on('moveend', () => {
        if (this.map) {
          this.mapStateService.updateBounds(this.map.getBounds());
        }
        this.updateVisibleProjects();
      });

      this.map.on('baselayerchange', (e: any) => {
        this.configService.baseLayerName = e.name;
        this.mapStateService.setBaseLayer(e.name);
      });

      // Add marker cluster group
      this.map.addLayer(this.markerClusterGroup);

      // Add default base layer
      const savedLayerName = this.configService.baseLayerName;
      const defaultLayer = baseLayers[savedLayerName] || baseLayers['World Topographic'];
      this.map.addLayer(defaultLayer);
      this.mapStateService.setBaseLayer(savedLayerName || 'World Topographic');

      // Add map controls
      L.control.scale({ position: 'bottomleft' }).addTo(this.map);
      L.control.layers(baseLayers, undefined, { position: 'bottomleft' }).addTo(this.map);
      L.control.zoom({ position: 'bottomright' }).addTo(this.map);
      this.map.addControl(new resetViewControl());

      // Initialize bounds
      this.mapStateService.updateBounds(this.map.getBounds());

      // Use whenReady to ensure map is fully initialized before adding markers
      this.map.whenReady(() => {
        if (this.map) {
          this.map.invalidateSize(true);
        }

        // Trigger marker update now that map is ready
        const currentProjects = this.projects();
        this.updateMarkers(currentProjects);

        // Auto-reposition after markers are added
        setTimeout(() => {
          if (this.markerClusterGroup) {
            const bounds = this.markerClusterGroup.getBounds();
            if (bounds.isValid()) {
              this.fitBounds(bounds);
            }
          }
        }, 100);
      });
    }
  }

  private createBaseLayers(): Record<string, any> {
    return {
      'Nat Geo World Map': L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/tile/{z}/{y}/{x}', {
        attribution: 'Tiles &copy; Esri',
        maxZoom: 16,
        noWrap: true
      }),
      'World Topographic': L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}', {
        attribution: 'Tiles &copy; Esri',
        maxZoom: 16,
        noWrap: true
      }),
      'World Imagery': L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
        attribution: 'Tiles &copy; Esri',
        maxZoom: 17,
        noWrap: true
      })
    };
  }

  private setupResizeObserver(): void {
    if (typeof ResizeObserver === 'undefined' || !this.mapContainer?.nativeElement) {
      return;
    }

    this.resizeObserver = new ResizeObserver(() => {
      if (this.map) {
        this.map.invalidateSize(true);
      }
    });

    this.resizeObserver.observe(this.mapContainer.nativeElement);
  }

  private resetView(): void {
    if (this.map) {
      this.map.setView(this.bcCenter, this.defaultZoom);
    }
  }

  ngOnDestroy(): void {
    clearTimeout(this.visibilityUpdateTimeout);
    clearTimeout(this.recentlyClosedTimeout);
    this.resizeObserver?.disconnect();

    // Clean up popup component
    if (this.popupComponentRef) {
      this.popupComponentRef.destroy();
      this.popupComponentRef = null;
    }

    // Clear marker cluster group
    this.markerClusterGroup?.clearLayers();

    // Clean up map
    if (this.map) {
      this.map.remove();
      this.map = null;
    }

    // Reset service state for clean initialization next time
    this.mapStateService.reset();

    this.destroy$.next();
    this.destroy$.complete();
  }

  private visibilityUpdateTimeout?: ReturnType<typeof setTimeout>;

  /**
   * Debounced version to update which projects are visible in the current map bounds
   */
  private updateVisibleProjects = (): void => {
    // Skip updates during auto-select to prevent state changes during pan animation
    if (this.autoSelectInProgress) {
      return;
    }
    
    clearTimeout(this.visibilityUpdateTimeout);
    this.visibilityUpdateTimeout = setTimeout(() => this.updateProjectVisibility(), this.VISIBILITY_UPDATE_DEBOUNCE_MS);
  };

  /**
   * Update which projects are visible in the current map bounds.
   * Uses MapStateService to track visibility without mutating Project objects.
   */
  private updateProjectVisibility(): void {
    if (!this.map) return;

    const mapBounds = this.map.getBounds();
    const projectsList = this.projects();
    const markers = this.mapStateService.getAllMarkers();

    // Create Map for O(1) lookups
    const projectsMap = new Map(projectsList.map(p => [p._id, p]));

    markers.forEach((markerState, projectId) => {
      const project = projectsMap.get(projectId);
      if (project) {
        const isVisible = mapBounds.contains(markerState.marker.getLatLng());
        this.mapStateService.setMarkerVisibility(projectId, isVisible);
      }
    });
  }

  private fitBounds(bounds: any = null, animate = false): void {
    if (!this.map) return;

    const padding = this.calculateFitBoundsPadding();

    // Expand bounds to ensure markers don't appear at edges
    let boundsToFit = bounds || this.defaultBounds;
    if (bounds && bounds.isValid()) {
      boundsToFit = this.expandBounds(bounds, padding.expansion);
    }

    const fitBoundsOptions = {
      paddingTopLeft: (L as any).point(padding.side, padding.top),
      paddingBottomRight: (L as any).point(padding.side, padding.bottom),
      animate: animate,
      duration: animate ? 0.5 : undefined,
      maxZoom: 10 // Prevent over-zooming when fitting to single marker or tight bounds
    };

    this.map.fitBounds(boundsToFit, fitBoundsOptions);
  }

  /**
   * Expand map bounds by a percentage to add buffer around markers
   */
  private expandBounds(bounds: any, expansionPercent: number): any {
    const latDiff = bounds.getNorth() - bounds.getSouth();
    const lngDiff = bounds.getEast() - bounds.getWest();
    const expandLat = latDiff * expansionPercent;
    const expandLng = lngDiff * expansionPercent;

    return L.latLngBounds(
      L.latLng(bounds.getSouth() - expandLat, bounds.getWest() - expandLng),
      L.latLng(bounds.getNorth() + expandLat, bounds.getEast() + expandLng)
    );
  }

  /**
   * Create a Leaflet marker for a project
   */
  private createMarker(project: Project): any {
    const title = `${project.name}\n${project.sector}\n${project.location}`;
    const marker = L.marker(
      L.latLng(project.centroid[1], project.centroid[0]),
      { title }
    )
      .setIcon(markerIconYellow)
      .on('click', (e: any) => this.onMarkerClick(project, e));

    (marker as any).projectId = project._id;
    return marker;
  }

  /**
   * Handle marker click event
   */
  private onMarkerClick(project: Project, event: any): void {
    this.selectMarker(project, event.target, false);
  }

  /**
   * Auto-select marker when exactly one is visible in map bounds
   * Reuses existing selectMarker logic but checks against recent manual closes
   */
  private autoSelectMarker(): void {
    const singleVisible = this.mapStateService.singleVisibleProject();
    if (!singleVisible) return;

    // Prevent duplicate auto-select or reopening recently closed popups
    if (this.autoSelectInProgress || 
        this.lastAutoSelectedProjectId === singleVisible.projectId ||
        this.recentlyClosedProjectId === singleVisible.projectId) {
      return;
    }

    const project = this.projects().find(p => p._id === singleVisible.projectId);
    if (!project) {
      this.logger.warn(
        `Could not find project data for auto-select: ${singleVisible.projectId}`,
        'ProjlistMapComponent'
      );
      return;
    }

    this.autoSelectInProgress = true;
    this.lastAutoSelectedProjectId = singleVisible.projectId;

    this.logger.debug(`Auto-selecting marker for project: ${project.name}`, 'ProjlistMapComponent');
    this.selectMarker(project, singleVisible.marker, true);
  }

  /**
   * Handle marker selection - opens popup and centers map
   * @param isAutoSelect - true for auto-select on page load, false for manual clicks
   */
  private selectMarker(project: Project, marker: any, isAutoSelect = false): void {
    const isMobile = this.isMobile();
    
    if (isMobile) {
      const hasActiveSearch = !!this.filterState.applicantFilter();
      if (!isAutoSelect || !hasActiveSearch) {
        this.closeMobileSearchIfOpen();
      }
    }

    this.centerMapOnMarker(marker);
    
    if (isAutoSelect) {
      setTimeout(() => this.createProjectPopup(project, marker), 300);
    } else {
      this.createProjectPopup(project, marker);
    }
  }

  /**
   * Close mobile search panel if it's open
   * @returns true if search panel was open and closed, false otherwise
   */
  private closeMobileSearchIfOpen(): boolean {
    const filters = this.appfilters();
    if (filters && typeof filters.toggleSearchMobile === 'function' && filters.showSearchMobile()) {
      filters.toggleSearchMobile();
      return true;
    }
    return false;
  }

  /**
   * Center map on a specific marker with appropriate offset for popups
   */
  private centerMapOnMarker(marker: any): void {
    if (!this.map) return;

    const isMobile = this.isMobile();
    // Apply offset for both mobile and desktop to prevent popup cutoff
    // Mobile needs more offset due to the popup card appearing above the marker
    const offset = isMobile ? 150 : this.calculatePopupOffset();
    const markerPoint = this.map.latLngToContainerPoint(marker.getLatLng());
    const targetPoint = L.point(markerPoint.x, markerPoint.y - offset);
    const targetLatLng = this.map.containerPointToLatLng(targetPoint);

    this.map.panTo(targetLatLng, { animate: true, duration: 0.25 });
  }

  /**
   * Create and display a popup for a project marker.
   * Reuses a single popup component instance for better performance.
   */
  private createProjectPopup(project: Project, marker: any): void {
    if (this.isPopupOpening) {
      this.logger.warn('Popup creation already in progress', 'ProjlistMapComponent');
      return;
    }

    if (!this.map || !marker || !this.markerClusterGroup.hasLayer(marker)) {
      this.logger.error('Cannot create popup: map or marker not ready', 'ProjlistMapComponent');
      return;
    }

    // Close any open popups on other markers first
    this.map.closePopup();

    const existingPopup = marker.getPopup();

    // If this marker's popup is already open, close it
    if (existingPopup?.isOpen()) {
      marker.closePopup();
      this.isPopupOpening = false;
      return;
    }

    try {
      this.isPopupOpening = true;

      // Update state - this will trigger marker highlighting via effect
      this.mapStateService.openPopup(project._id);
      this.applist()?.toggleCurrentApp(project);

      // Adjust popup size for narrow viewports
      const viewportWidth = window.innerWidth;
      const isNarrow = viewportWidth < 400;
      const maxWidth = isNarrow ? Math.min(viewportWidth - 40, 280) : 300;
      const minWidth = isNarrow ? Math.min(viewportWidth - 60, 220) : 250;
      
      const popupOptions = {
        className: 'map-popup-content',
        autoPan: false,
        offset: L.point(0, -30),
        closeButton: true,
        maxWidth,
        minWidth
      };

      // Create or reuse popup component
      if (!this.popupComponentRef) {
        this.popupComponentRef = this.viewContainerRef.createComponent(
          ProjDetailPopupComponent,
          { injector: this.injector }
        );
      }

      // Update component with project data
      this.popupComponentRef.instance.proj = project;
      this.popupComponentRef.changeDetectorRef.detectChanges();

      // Create new popup instance with fresh content reference
      const popup = L.popup(popupOptions)
        .setLatLng(marker.getLatLng())
        .setContent(this.popupComponentRef.location.nativeElement)
        .on('remove', () => {
          this.applist()?.toggleCurrentApp(project);
          this.mapStateService.closePopup();
          
          // Prevent auto-reopen for this project
          this.recentlyClosedProjectId = project._id;
          clearTimeout(this.recentlyClosedTimeout);
          this.recentlyClosedTimeout = setTimeout(() => {
            this.recentlyClosedProjectId = null;
          }, 500);
        });

      // Unbind old popup if exists, then bind new one
      if (existingPopup) {
        marker.unbindPopup();
      }

      marker.bindPopup(popup).openPopup();

      // Reset flags and update visibility
      this.isPopupOpening = false;
      this.autoSelectInProgress = false;
      this.updateProjectVisibility();

    } catch (error) {
      this.logger.error('Failed to create popup', 'ProjlistMapComponent', error);
      this.mapStateService.closePopup();
      this.isPopupOpening = false;
      this.autoSelectInProgress = false;
    }
  }

  /**
   * Highlight marker for active popup, reset all others to normal size
   */
  private highlightMarker(activeProjectId: string | null): void {
    const markers = this.mapStateService.getAllMarkers();

    markers.forEach((markerState, id) => {
      if (activeProjectId && id === activeProjectId) {
        markerState.marker.setIcon(markerIconYellowLg);
      } else {
        markerState.marker.setIcon(markerIconYellow);
      }
    });
  }

  /**
   * Reset map to default bounds
   */
  resetMap(): void {
    this.fitBounds();
  }


}

<div class="map-container" [class.loading]="loading()">
  <div #mapContainer id="map" name="Map of B.C. that displays EAO Projects"></div>
</div>
