// src/app/pages/projects/projlist-list.tsx
import { useMemo, useState } from 'react';
import { Link } from 'react-router';
import type { Project } from 'app/models/project';
import { isClosed, isNotOpen, isNotStarted, isOpen } from 'app/api/commentperiod';
import { LIST_PAGE_SIZE } from 'app/state/map-ui';
import './projlist-list.css';

interface ProjlistListProps {
  /** null while the projects are still loading, so "No projects found" waits for real data. */
  projects: Project[] | null;
  loading: boolean;
  currentAppId: string | null;
  onToggleCurrentApp: (project: Project) => void;
}

/** Angular's `titlecase` pipe: first letter of each word up, the rest down. */
function titleCase(value: string | undefined): string {
  return (value ?? '').replace(/\w\S*/g, word => word[0].toUpperCase() + word.slice(1).toLowerCase());
}

/** Angular's `date:'MMM d'`, e.g. "Aug 27". */
function shortDate(value: string | Date | undefined | null): string {
  if (!value) return '';
  return new Date(value).toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
}

/** Angular's `date:'mediumDate'`, e.g. "Aug 27, 2026". */
function mediumDate(value: string | Date | undefined | null): string {
  if (!value) return '';
  return new Date(value).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
}

function badgeClass(period: any): string {
  if (isOpen(period)) return 'badge-success';
  if (isClosed(period)) return 'badge-danger';
  if (isNotStarted(period)) return 'badge-primary';
  if (isNotOpen(period)) return 'badge-secondary';
  return '';
}

export function ProjlistList({ projects, loading, currentAppId, onToggleCurrentApp }: ProjlistListProps) {
  const [numToLoad, setNumToLoad] = useState(LIST_PAGE_SIZE);

  const loadedApps = useMemo(() => (projects ?? []).slice(0, numToLoad), [projects, numToLoad]);
  const numResults = useMemo(
    () => (projects ?? []).filter(project => project.centroid?.length === 2).length,
    [projects]
  );

  return (
    <div
      className="app-list app-list__container"
      id="applist-list"
      aria-label="List of EAO Projects, limited by filters and bound by map view"
    >
      <div className="app-list__body">
        {loading && loadedApps.length === 0 && (
          <div className="spinner-container">
            <div className="spinner spinner-sm rotating"></div>
            <span className="spinner__msg">Loading projects...</span>
          </div>
        )}

        {!loading && projects !== null && loadedApps.length === 0 && (
          <div className="no-results">
            <strong>No projects found</strong>
          </div>
        )}

        <div className="app-list__scroll-container">
          <ul className="app-list__list">
            {loadedApps.map(item => (
              <li
                key={item._id}
                className={`app-card list-group-item${currentAppId === item._id ? ' active' : ''}`}
                role="button"
                tabIndex={0}
                onClick={event => {
                  onToggleCurrentApp(item);
                  event.stopPropagation();
                }}
                onKeyDown={event => {
                  if (event.key !== 'Enter' && event.key !== ' ') return;
                  event.preventDefault();
                  onToggleCurrentApp(item);
                  event.stopPropagation();
                }}
              >
                <ul className="app-card__details">
                  <li>
                    <span className="key">Applicant</span>
                    <span className="value client-name">{item.client || 'Unknown Client'}</span>
                  </li>
                  <li>
                    <span className="key">Purpose / Subpurpose</span>
                    <span className="value">
                      {(item.purpose || item.subpurpose) && (
                        <span>
                          {titleCase(item.purpose)} / {titleCase(item.subpurpose)}
                        </span>
                      )}
                      {(!item.purpose || !item.subpurpose) && <span>Not Available</span>}
                    </span>
                  </li>
                  <li>
                    <span className="key">Disposition Transaction</span>
                    <span className="value">{item.tantalisID}</span>
                  </li>
                  <li>
                    <span className="key">EAO Project #</span>
                    <span className="value">{item.clFile || 'Not Available'}</span>
                  </li>
                  <li>
                    <span className="key">Status</span>
                    <span className="value">{item.currentPhaseName?.name || 'Unknown'}</span>
                  </li>
                </ul>

                <div className="app-card__actions d-flex justify-content-between">
                  <div className="badges">
                    <div className={`comment-status-badge badge ${badgeClass(item.currentPeriod)}`}>
                      <span>{item.cpStatus}</span>
                      {isNotStarted(item.currentPeriod) && (
                        <span className="date">:&nbsp;{mediumDate(item.currentPeriod?.startDate)}</span>
                      )}
                      {isClosed(item.currentPeriod) && (
                        <span className="date">:&nbsp;{mediumDate(item.currentPeriod?.endDate)}</span>
                      )}
                      {isOpen(item.currentPeriod) && (
                        <span className="date">
                          :&nbsp;{shortDate(item.currentPeriod?.startDate)} - {shortDate(item.currentPeriod?.endDate)}
                        </span>
                      )}
                    </div>
                  </div>
                  <Link
                    className="app-details-link btn"
                    onClick={event => event.stopPropagation()}
                    to={`/p/${item._id}`}
                    title="Go to project details"
                  >
                    <i className="material-icons md-24">arrow_forward</i>
                  </Link>
                </div>
              </li>
            ))}
          </ul>

          {loadedApps.length > 0 && loadedApps.length < (projects?.length ?? 0) && (
            <div className="load-more">
              <button
                className="btn btn-primary"
                type="button"
                title="Load more projects"
                onClick={event => {
                  setNumToLoad(current => current + LIST_PAGE_SIZE);
                  event.stopPropagation();
                }}
                disabled={loading}
              >
                {loading && <i className="spinner rotating"></i>}
                <span>{loading ? 'Loading...' : 'Load More'}</span>
              </button>
            </div>
          )}
        </div>
      </div>

      <div className="app-list__options">
        <div className="text-end mb-1">{numResults > 0 ? `${numResults} results on map` : 'No results'}</div>
      </div>
    </div>
  );
}

// src/app/projects/projlist-list/projlist-list.component.ts
import { Component, ElementRef, ChangeDetectionStrategy, input, output, signal, computed, effect, untracked, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

import { Project } from 'app/models/project';
import { CommentPeriodService } from 'app/services/commentperiod.service';
import { ConfigService } from 'app/services/config.service';
import { LoadingStateService } from 'app/services/loading-state.service';
import { VarDirective } from '../../shared/utils/ng-var.directive';

@Component({
  selector: 'app-projlist-list',
  templateUrl: './projlist-list.component.html',
  styleUrl: './projlist-list.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule, RouterModule, VarDirective],
})
export class ProjlistListComponent {
  // NB: this component is bound to the same list of apps as the other components
  projects = input<Project[] | null>(null); // from projects component
  setCurrentApp = output<Project>(); // to projects component
  unsetCurrentApp = output<Project>(); // to projects component

  public commentPeriodService = inject(CommentPeriodService); // used in template
  public configService = inject(ConfigService);
  private elementRef = inject(ElementRef);
  private loadingState = inject(LoadingStateService);

  private currentApp: Project | null = null; // for selecting app in list
  public loading = this.loadingState.isLoading;
  private numToLoad = signal<number>(0);

  // Computed signal for loaded projects (no mutation)
  public loadedApps = computed(() => {
    const projects = this.projects();
    if (projects === null) return [];
    const limit = this.numToLoad();
    return projects.slice(0, limit);
  });

  // Computed signal for projects with valid coordinates
  public appsWithShapes = computed(() => {
    return (this.projects() ?? []).filter(a => a.centroid?.length === 2);
  });

  get clientWidth(): number {
    return this.elementRef.nativeElement.firstElementChild?.clientWidth ?? 0;
  }

  constructor() {
    // Initialize with first page of results
    effect(() => {
      const currentProjects = this.projects();
      if (currentProjects === null) return;

      untracked(() => {
        // Clear current selection if the selected app is no longer in the list
        if (this.currentApp && !currentProjects.some(p => p._id === this.currentApp?._id)) {
          this.currentApp = null;
        }

        // Initialize page size if not set
        if (this.numToLoad() === 0 && currentProjects.length > 0) {
          this.numToLoad.set(this.configService.listPageSize);
        }
      });
    });
  }

  public isCurrentApp(item: Project): boolean {
    return item === this.currentApp;
  }

  public toggleCurrentApp(item: Project): void {
    if (this.isCurrentApp(item)) {
      this.currentApp = null;
      this.unsetCurrentApp.emit(item);
    } else {
      this.currentApp = item;
      this.setCurrentApp.emit(item);
    }
  }

  public loadMore() {
    this.numToLoad.update(n => n + this.configService.listPageSize);
  }
}

<div class="app-list__container" id="applist-list" name="List of EAO Projects, limited by filters and bound by map view">

  <div class="app-list__body">

    <!-- Initial Loading Indicator -->
    @if (loading() && loadedApps().length === 0) {
      <div class="spinner-container">
        <div class="spinner spinner-sm rotating"></div>
        <span class="spinner__msg">Loading projects...</span>
      </div>
    }

    <!-- No Results (only after data has loaded) -->
    @if (!loading() && projects() !== null && loadedApps().length === 0) {
      <div class="no-results">
        <strong>No projects found</strong>
      </div>
    }

    <!-- Scrollable Content -->
    <div class="app-list__scroll-container">
      <ul class="app-list__list">
        @for (item of loadedApps(); track item._id) {
          <li class="app-card list-group-item" [class.active]="isCurrentApp(item)"
            role="button"
            tabindex="0"
            (click)="toggleCurrentApp(item);$event.stopPropagation();"
            (keydown.enter)="toggleCurrentApp(item);$event.stopPropagation();"
            (keydown.space)="toggleCurrentApp(item);$event.stopPropagation();">

            <!-- Project Details -->
            <ul class="app-card__details">
              <li>
                <span class="key">Applicant</span>
                <span class="value client-name">{{item.client || 'Unknown Client'}}</span>
              </li>
              <li>
                <span class="key">Purpose / Subpurpose</span>
                <!-- TODO: Need a better way of handling values that are not available - see also below -->
                <span class="value">
                  @if (item.purpose || item.subpurpose) {
                    <span>{{item.purpose | titlecase}} / {{item.subpurpose | titlecase}}</span>
                  }
                    @if (!item.purpose || !item.subpurpose) {
                      <span>Not Available</span>
                    }
                  </span>
                </li>
                <li>
                  <span class="key">Disposition Transaction</span>
                  <span class="value">{{item.tantalisID}}</span>
                </li>
                <li>
                  <span class="key">EAO Project #</span>
                  <!-- TODO: Need a better way of handling values that are not available - see also above -->
                  <span class="value">{{item['clFile'] || 'Not Available'}}</span>
                </li>
                <li>
                  <span class="key">Status</span>
                  <span class="value">{{item.currentPhaseName?.name || 'Unknown'}}</span>
                </li>
              </ul>

              <!-- Project Card Actions -->
              <div class="app-card__actions d-flex justify-content-between">
                <div class="badges">
                  <div class="comment-status-badge badge"
                    [ngClass]="{
                      'badge-primary': commentPeriodService.isNotStarted(item.currentPeriod),
                      'badge-secondary': commentPeriodService.isNotOpen(item.currentPeriod),
                      'badge-danger': commentPeriodService.isClosed(item.currentPeriod),
                      'badge-success': commentPeriodService.isOpen(item.currentPeriod)}">
                    <span>{{item.cpStatus}}</span>
                    @if (commentPeriodService.isNotStarted(item.currentPeriod)) {
                      <span class="date">
                        :&nbsp;{{item.currentPeriod.startDate | date:'mediumDate'}}
                      </span>
                    }
                    @if (commentPeriodService.isClosed(item.currentPeriod)) {
                      <span class="date">
                        :&nbsp;{{item.currentPeriod.endDate | date:'mediumDate'}}
                      </span>
                    }
                    @if (commentPeriodService.isOpen(item.currentPeriod)) {
                      <span class="date">
                        :&nbsp;{{item.currentPeriod.startDate | date:'MMM d'}} - {{item.currentPeriod.endDate | date:'MMM d'}}
                      </span>
                    }
                  </div>
                </div>
                <a class="app-details-link btn" (click)="$event.stopPropagation()" [routerLink]="['/a', item._id]" title="Go to project details">
                  <i class="material-icons md-24">arrow_forward</i>
                </a>
              </div>
            </li>
        }
      </ul>

      <!-- Load More -->
      @if (loadedApps().length > 0 && loadedApps().length < (projects()?.length ?? 0)) {
        <div class="load-more">
          <button class="btn btn-primary" type="button" title="Load more projects" (click)="loadMore();$event.stopPropagation()" [disabled]="loading()">
            @if (loading()) {
              <i class="spinner rotating"></i>
            }
            <span>{{loading() ? 'Loading...':'Load More'}}</span>
          </button>
        </div>
      }

    </div>
  </div>

  <div class="app-list__options" *ngVar="appsWithShapes().length as numResults">
    <div class="text-end mb-1">
      {{numResults > 0 ? numResults + ' results on map' : 'No results'}}
    </div>
  </div>

</div>
