// src/app/search/content-result/content-result.component.ts
import { Component, ChangeDetectionStrategy, input, computed, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { Utils } from 'app/shared/utils/utils';

/**
 * One content-search result: a DOCUMENT, with the passages that matched inside it.
 *
 * The snippets arrive as markup and are bound with `[innerHTML]`. That is safe because eagle-search
 * escapes the document text BEFORE turning its highlight sentinels into `<mark>`, and balances the
 * tags per fragment — see `service/snippet.js` there. Angular's sanitizer keeps `<mark>` and strips
 * anything else, so this is belt and braces rather than the only guard.
 */
@Component({
  selector: 'app-content-result',
  templateUrl: './content-result.component.html',
  styleUrls: ['./content-result.component.css'],
  imports: [CommonModule, RouterLink],
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true
})
export class ContentResultComponent {
  private utils = inject(Utils);

  readonly result = input.required<any>();

  /**
   * The document itself. eagle-api serves PDFs inline, so this opens in the browser's viewer.
   *
   * There is deliberately no `#page=N` fragment. This card briefly rendered "Jump to page N" links
   * built from the chunk's `pageNumber`, and every one of them was wrong: `pageNumber` is a passage
   * SEQUENCE number, not a PDF page — the chunker increments it per emitted block and the extraction
   * host flattens pages before posting. Measured, a 63-chunk document carries 51 distinct values.
   * Page links come back when the extractor emits real per-page markdown, and not before.
   */
  documentUrl(): string {
    const r = this.result();
    const name = this.utils.encodeString(r.documentName || 'document', true);
    return `/api/public/document/${r._id}/download/${name}`;
  }

  /** Matches only. There is no trustworthy page count to pair it with. */
  readonly matchSummary = computed(() => {
    const matches = this.result().matchCount || 0;
    return `${matches} match${matches === 1 ? '' : 'es'}`;
  });

  download(): void {
    const r = this.result();
    this.utils.openDocumentDownload({ _id: r._id, displayName: r.documentName });
  }
}

<article class="content-result">
  <h3 class="result-title">
    <a [href]="pageUrl(result().pages?.[0])" target="_blank" rel="noopener">{{result().documentName || 'Untitled document'}}</a>
  </h3>

  <p class="result-meta">
    @if (result().project?._id) {
      <a [routerLink]="['/p', result().project._id, 'project-details']">{{result().project.name}}</a>
    } @else if (result().project?.name) {
      <span>{{result().project.name}}</span>
    }
    @if (result().documentType) { <span class="sep">·</span><span>{{result().documentType}}</span> }
    @if (result().milestone) { <span class="sep">·</span><span>{{result().milestone}}</span> }
    @if (result().datePosted && result().datePosted !== '1900-01-01T08:00:00.000Z') {
      <span class="sep">·</span><span>{{result().datePosted | date:'longDate'}}</span>
    }
    <span class="sep">·</span><span class="match-count">{{matchSummary()}}</span>
  </p>

  @for (snippet of result().snippets; track $index) {
    <!-- Escaped and mark-balanced by eagle-search before it ever reaches the browser. -->
    <p class="result-snippet" [innerHTML]="snippet"></p>
  }
  @if (!result().snippets?.length) {
    <!-- Azure returns no highlights for a fuzzy or wildcard match. An empty card reads as a bug, so
         say what happened instead of showing nothing. -->
    <p class="result-snippet no-snippet">Match found in the document text.</p>
  }

  <div class="result-actions">
    @if (result().pages?.length) {
      <span class="pages-label">Jump to page:</span>
      @for (page of result().pages; track page) {
        <a class="page-link" [href]="pageUrl(page)" target="_blank" rel="noopener"
           [attr.aria-label]="'Open page ' + page + ' of ' + result().documentName">{{page}}</a>
      }
      @if (result().morePages) { <span class="more-pages">+{{result().morePages}} more</span> }
    }
    <button type="button" class="result-download" (click)="download()"
      [attr.aria-label]="'Download ' + result().documentName">
      <span class="material-icons" aria-hidden="true">cloud_download</span> Download
    </button>
  </div>
</article>

// src/app/pages/search/content-result.tsx
import { Link } from 'react-router';
import { encodeString, longDate, openDocumentDownload } from 'app/utils/utils';
import { safeHtml } from 'app/utils/safe-html';
import './content-result.css';

/** Placeholder date the API stores for a document with no posting date; never shown. */
const NO_DATE = '1900-01-01T08:00:00.000Z';

const ESCAPES: Record<string, string> = { '&': '&amp;', '<': '&lt;', '>': '&gt;' };

/**
 * eagle-search escapes the document text before turning its highlight sentinels into `<mark>`, so
 * the snippet is already safe. Angular's sanitizer then kept `<mark>` and stripped anything else;
 * React's `dangerouslySetInnerHTML` strips nothing, so do that one job here rather than lose it.
 */
function markOnly(snippet: string): string {
  return String(snippet ?? '')
    .replace(/[&<>]/g, (character) => ESCAPES[character]!)
    .replace(/&lt;(\/?)mark&gt;/g, '<$1mark>');
}

/**
 * The document itself. eagle-api serves PDFs inline, so this opens in the browser's viewer.
 *
 * Deliberately no `#page=N` fragment: a chunk's `pageNumber` is a passage SEQUENCE number, not a
 * PDF page, so every link built from it pointed somewhere arbitrary.
 */
function documentUrl(result: any): string {
  return `/api/public/document/${result._id}/download/${encodeString(result.documentName || 'document', true)}`;
}

/** Matches only. There is no trustworthy page count to pair it with. */
function matchSummary(result: any): string {
  const matches = result.matchCount || 0;
  return `${matches} match${matches === 1 ? '' : 'es'}`;
}

/** One content-search result: a DOCUMENT, with the passages that matched inside it. */
export function ContentResult({ result }: { result: any }) {
  const snippets: string[] = result.snippets ?? [];

  return (
    <article className="content-result">
      <h3 className="result-title">
        <a href={documentUrl(result)} target="_blank" rel="noopener">
          {result.documentName || 'Untitled document'}
        </a>
      </h3>

      <p className="result-meta">
        {result.project?._id ? (
          <Link to={`/p/${result.project._id}/project-details`}>{result.project.name}</Link>
        ) : (
          result.project?.name && <span>{result.project.name}</span>
        )}
        {result.documentType && (
          <>
            <span className="sep">·</span>
            <span>{result.documentType}</span>
          </>
        )}
        {result.milestone && (
          <>
            <span className="sep">·</span>
            <span>{result.milestone}</span>
          </>
        )}
        {result.datePosted && result.datePosted !== NO_DATE && (
          <>
            <span className="sep">·</span>
            <span>{longDate(result.datePosted)}</span>
          </>
        )}
        <span className="sep">·</span>
        <span className="match-count">{matchSummary(result)}</span>
      </p>

      {snippets.map((snippet, index) => (
        <p
          className="result-snippet"
          key={index}
          dangerouslySetInnerHTML={safeHtml(markOnly(snippet))}
        />
      ))}
      {snippets.length === 0 && (
        // Azure returns no highlights for a fuzzy or wildcard match. An empty card reads as a bug.
        <p className="result-snippet no-snippet">Match found in the document text.</p>
      )}

      <div className="result-actions">
        <button
          type="button"
          className="result-download"
          onClick={() =>
            openDocumentDownload({ _id: result._id, displayName: result.documentName })
          }
          aria-label={`Download ${result.documentName}`}
        >
          <span className="material-icons" aria-hidden="true">
            cloud_download
          </span>{' '}
          Download
        </button>
      </div>
    </article>
  );
}
