// src/app/search/content-search.component.ts
import { Component, ChangeDetectionStrategy, OnInit, OnDestroy, signal, inject, Injector, runInInjectionContext } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, Params, RouterLink, RouterLinkActive } from '@angular/router';
import { takeWhile, distinctUntilChanged, skip } from 'rxjs/operators';
import { toObservable } from '@angular/core/rxjs-interop';

import { TableService } from 'app/services/table.service';
import { SearchParamObject } from 'app/services/search.service';
import { LoadingStateService } from 'app/services/loading-state.service';
import { SearchFilterTemplateComponent } from 'app/shared/components/search-filter-template/search-filter-template.component';
import { PaginationComponent } from 'app/shared/components/pagination/pagination.component';
import { HeroBannerComponent } from 'app/shared/hero-banner/hero-banner.component';
import { ContentResultComponent } from './content-result/content-result.component';
import { SEARCH_TABS } from './search.config';

/**
 * Document content search.
 *
 * NOT built on `table-list`. That was the first attempt and it was wrong: `lib-table-template`
 * lays its rows out as table cells, so a result card's title, metadata, each snippet and the page
 * links each became a narrow column — the text ended up in vertical ribbons. A result list is a
 * list, and forcing it through a table to reuse the pagination was a false economy.
 *
 * What IS reused, because these are real components rather than a layout: the hero banner, the
 * search/filter template, `lib-pagination`, and `TableService` for fetching and caching.
 */
@Component({
  selector: 'app-content-search',
  templateUrl: './content-search.component.html',
  styleUrls: ['./content-search.component.css'],
  imports: [
    CommonModule,
    RouterLink,
    RouterLinkActive,
    SearchFilterTemplateComponent,
    PaginationComponent,
    HeroBannerComponent,
    ContentResultComponent
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true
})
export class ContentSearchComponent implements OnInit, OnDestroy {
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private tableService = inject(TableService);
  private injector = inject(Injector);
  readonly loadingState = inject(LoadingStateService);

  readonly TABLE_ID = 'search-content';
  readonly tabs = SEARCH_TABS;

  readonly results = signal<any[]>([]);
  readonly currentPage = signal(1);
  readonly pageSize = signal(10);
  /**
   * Passages, not documents. Used ONLY to decide whether another page exists — never shown. Azure
   * cannot count distinct documents, and "1,128,702 results" told a reader nothing except that the
   * number was large.
   */
  readonly passageTotal = signal(0);

  readonly loading = () => this.loadingState.getOperationState(`table-${this.TABLE_ID}`)();

  private alive = true;

  ngOnInit(): void {
    runInInjectionContext(this.injector, () => {
      toObservable(this.tableService.getTableSignal(this.TABLE_ID))
        .pipe(takeWhile(() => this.alive), skip(1))
        .subscribe((res: any) => {
          if (!res || res.data === undefined || res.data === 0) return;
          this.results.set(Array.isArray(res.data) ? res.data : []);
          this.passageTotal.set(res.totalSearchCount || 0);
        });
    });

    // NO FILTER CONTROLS on this tab. Milestone, Document Type and the date range were rendered
    // here and dropped by the API on every search it makes: a chunk filter has to resolve to a
    // document id set first, and a corpus-wide value exceeds DOCUMENT_SCOPE_CAP at any cap one
    // request can fill, so the key came back in `meta.dropped` and the passages came back
    // unfiltered. The Documents tab keeps all five — they work there.
    this.fetch(this.route.snapshot.queryParams);

    this.route.queryParams
      .pipe(
        takeWhile(() => this.alive),
        skip(1),
        distinctUntilChanged((a, b) => JSON.stringify(a) === JSON.stringify(b))
      )
      .subscribe(params => this.fetch(params));
  }

  private fetch(params: Params): void {
    this.currentPage.set(+(params['currentPage'] || 1));
    this.pageSize.set(+(params['pageSize'] || 10));

    this.tableService.fetchData(new SearchParamObject(
      this.TABLE_ID,
      params['keywords'] || '',
      'DocumentChunk',
      [],
      this.currentPage(),
      this.pageSize(),
      // Relevance always. There is no meaningful field sort over passages, and `-score` is what
      // eagle-search reads as "issue no $orderby", leaving BM25's ranking in place.
      '-score',
      {},
      true,
      '',
      {}
    ));
  }

  executeSearch(searchPackage: any): void {
    this.submit({ currentPage: 1, keywords: searchPackage.keywords?.trim() || null });
  }

  onPageChange(page: number): void {
    this.submit({ ...this.route.snapshot.queryParams, currentPage: page });
  }

  /** There is no document total, so "more pages" is whether the passage window can advance. */
  get hasResults(): boolean {
    return this.results().length > 0;
  }

  private submit(params: Params): void {
    this.router.navigate([], { queryParams: params, relativeTo: this.route });
  }

  ngOnDestroy(): void {
    this.alive = false;
  }
}

<main>
  <app-hero-banner
    title="Search Inside Documents"
    description="Search the text inside documents from the Environmental Assessment Office, not just their titles. Results show the pages the match was found on and the surrounding text."
    [actions]="[{ label: 'List of Projects', icon: 'list', routerLink: '/projects-list', title: 'List of Projects' }]"
  />

  <div class="container">
    <ul class="nav nav-tabs search-tabs" role="tablist">
      @for (tab of tabs; track tab.link) {
        <li class="nav-item" role="presentation">
          <a class="nav-link" role="tab" [routerLink]="tab.link"
             routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }">{{ tab.label }}</a>
        </li>
      }
    </ul>
  </div>

  <section class="results-container">
    <div class="container">
      <section class="mb-4 pt-0 pb-0">
        <search-filter-template
          (searchEvent)="executeSearch($event)"
          [advancedFilters]="true"
          [showAdvancedFilters]="showAdvancedFilters()"
          [searchOnFilterChange]="true"
          [filters]="filters()"
          [searchHelpLinkArray]='["/search-help"]'
          [searching]="loading()">
        </search-filter-template>
      </section>

      @if (loading()) {
        <p class="results-status" role="status">Searching…</p>
      } @else if (!hasResults) {
        <p class="results-status" role="status">No documents contain that text. Try fewer or more general words.</p>
      } @else {
        <!-- Documents on this page, deliberately without a total. The only count the index can give
             is matching passages, which is not a number a reader can use. -->
        <p class="results-status" role="status">
          Showing {{ results().length }} document{{ results().length === 1 ? '' : 's' }}
          @if (currentPage() > 1) { <span>· page {{ currentPage() }}</span> }
        </p>

        <ol class="results-list">
          @for (doc of results(); track doc._id) {
            <li><app-content-result [result]="doc" /></li>
          }
        </ol>

        <lib-pagination
          [currentPage]="currentPage()"
          [pageSize]="pageSize()"
          [totalItems]="passageTotal()"
          ariaLabel="Content search pagination"
          (pageChange)="onPageChange($event)">
        </lib-pagination>
      }
    </div>
  </section>
</main>

// src/app/pages/search/content-search.tsx
import { useMemo } from 'react';
import { NavLink, useSearchParams } from 'react-router';
import { HeroBanner } from 'app/components/hero-banner';
import { SearchFilterTemplate } from 'app/components/filters/search-filter-template';
import type { SearchPackage } from 'app/components/filters/filter-object';
import { Pagination } from 'app/components/table/pagination';
import { paramsToObject, toSearchParams, type Params } from 'app/components/table/table-params';
import { useTable } from 'app/components/table/use-table';
import { contentSearchEnabled } from 'app/config/config';
import { visibleSearchTabs } from './search.config';
import { ContentResult } from './content-result';
import './content-search.css';

const CONTENT_SEARCH_TABLE_ID = 'search-content';

/**
 * Document content search.
 *
 * NOT built on `TableList`. The table template lays rows out as table cells, so a result card's
 * title, metadata and each snippet became a narrow vertical ribbon. A result list is a list.
 * Reused instead: the hero banner, the search/filter template, pagination and `useTable`.
 */
export function ContentSearch() {
  const [searchParams, setSearchParams] = useSearchParams();
  const params = useMemo(() => paramsToObject(searchParams), [searchParams]);

  const tabs = visibleSearchTabs(contentSearchEnabled());
  const currentPage = +(params['currentPage'] || 1);
  const pageSize = +(params['pageSize'] || 10);

  const table = useTable(CONTENT_SEARCH_TABLE_ID, {
    dataset: 'DocumentChunk',
    keywords: params['keywords'] || '',
    currentPage,
    pageSize,
    // Relevance always. There is no meaningful field sort over passages, and `-score` is what the
    // search API reads as "issue no $orderby", leaving BM25's ranking in place.
    sortBy: '-score',
    populate: true,
    // NO FILTER CONTROLS on this tab, and no filter keys forwarded from a stale link. A chunk
    // filter has to resolve to a document id set first, and a corpus-wide value exceeds
    // DOCUMENT_SCOPE_CAP, so the API drops the key and answers 200 with the whole corpus wearing
    // the label of a filtered result. The Documents tab keeps all five — they work there.
    filters: {},
  });

  /**
   * Passages, not documents. Used ONLY to decide whether another page exists — never shown. Azure
   * cannot count distinct documents, and "1,128,702 results" told a reader nothing.
   */
  const passageTotal = table.totalListItems;
  const results = table.data;

  function submit(next: Params): void {
    setSearchParams(toSearchParams(next), { replace: true });
  }

  function executeSearch(searchPackage: SearchPackage): void {
    // Page size is the user's choice, not part of the search.
    submit({
      pageSize: params['pageSize'],
      currentPage: 1,
      keywords: searchPackage.keywords?.trim() || null,
    });
  }

  return (
    <main className="content-search">
      <HeroBanner
        title="Search Inside Documents"
        description="Search the text inside documents from the Environmental Assessment Office, not just their titles. Results show the matching passages and the text around them."
        actions={[
          {
            label: 'List of Projects',
            icon: 'list',
            routerLink: '/projects-list',
            title: 'List of Projects',
          },
        ]}
      />

      {tabs.length > 0 && (
        <div className="container">
          <ul className="nav nav-tabs search-tabs" role="tablist">
            {tabs.map((tab) => (
              <li className="nav-item" role="presentation" key={tab.link}>
                <NavLink
                  className={({ isActive }) => `nav-link${isActive ? ' active' : ''}`}
                  role="tab"
                  to={tab.link}
                  end
                >
                  {tab.label}
                </NavLink>
              </li>
            ))}
          </ul>
        </div>
      )}

      <section className="results-container">
        <div className="container">
          <section className="mb-4 pt-0 pb-0">
            <SearchFilterTemplate
              onSearch={executeSearch}
              advancedFilters={false}
              searchHelpLink="/search-help"
            />
          </section>

          {table.loading ? (
            <p className="results-status" role="status">
              Searching…
            </p>
          ) : results.length === 0 ? (
            <p className="results-status" role="status">
              No documents contain that text. Try fewer or more general words.
            </p>
          ) : (
            <>
              {/* Documents on this page, deliberately without a total. The only count the index can
                  give is matching passages, which is not a number a reader can use. */}
              <p className="results-status" role="status">
                Showing {results.length} document{results.length === 1 ? '' : 's'}
                {currentPage > 1 && <span> · page {currentPage}</span>}
              </p>

              <ol className="results-list">
                {results.map((doc: any) => (
                  <li key={doc._id}>
                    <ContentResult result={doc} />
                  </li>
                ))}
              </ol>

              <Pagination
                currentPage={currentPage}
                pageSize={pageSize}
                totalItems={passageTotal}
                ariaLabel="Content search pagination"
                onPageChange={(page) => submit({ ...params, currentPage: page })}
              />
            </>
          )}
        </div>
      </section>
    </main>
  );
}
