// src/app/project/engage-banner/engage-banner.component.ts
import { Component, ChangeDetectionStrategy, input, computed } from '@angular/core';
import { DatePipe, LowerCasePipe } from '@angular/common';
import { CommentPeriod } from '../../models/commentperiod';

@Component({
  selector: 'app-engage-banner',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [DatePipe, LowerCasePipe],
  templateUrl: './engage-banner.component.html',
  styleUrl: './engage-banner.component.css',
  host: {
    'class': 'engage-banner',
    '[class.engage-banner--has-image]': 'data().metBannerImageUrl',
  },
})
export class EngageBannerComponent {
  data = input.required<CommentPeriod>();

  statusClass = computed(() => {
    const status = this.data().bannerState;
    return status ? `engage-banner__status-chip--${status.toLowerCase()}` : '';
  });
}

@if (data().metBannerImageUrl) {
  <img class="engage-banner__image" [src]="data().metBannerImageUrl" alt="Engagement banner" fetchpriority="high" loading="eager">
}
<div class="engage-banner__card">
  @if (data().informationLabel) {
    <h2 class="engage-banner__title">{{ data().informationLabel }}</h2>
  }
  @if (data().instructions) {
    <p class="engage-banner__description">{{ data().instructions }}</p>
  }
  @if (data().dateStarted && data().dateCompleted) {
    <p class="engage-banner__dates">
      <strong>Engagement dates: {{ data().dateStarted | date:"MMM d, yyyy":"UTC" }} to {{ data().dateCompleted | date:"MMM d, yyyy":"UTC" }}</strong>
    </p>
  }
  <div class="engage-banner__status-row">
    <strong>Status:</strong>
    <span class="engage-banner__status-chip" [class]="statusClass()">{{ data().bannerState }}</span>
  </div>
  <a class="engage-banner__cta"
     [href]="data().metURL"
     target="_blank"
     rel="noopener noreferrer">
    {{ data().bannerCTA }}
    <i class="material-icons">open_in_new</i>
  </a>
</div>

// src/app/pages/project/engage-banner.tsx
import type { CommentPeriod } from 'app/models/commentperiod';
import './engage-banner.css';

/** Angular's `date:'MMM d, yyyy':'UTC'` — engagement dates are stored as plain UTC days. */
function utcMediumDate(value: Date): string {
  return value.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric', timeZone: 'UTC' });
}

/** Banner for a comment period hosted on ENGAGE, linking out to the engagement itself. */
export function EngageBanner({ data }: { data: CommentPeriod }) {
  const status = data.bannerState;

  return (
    <div className={`engage-banner${data.metBannerImageUrl ? ' engage-banner--has-image' : ''}`}>
      {data.metBannerImageUrl && (
        <img
          className="engage-banner__image"
          src={data.metBannerImageUrl}
          alt="Engagement banner"
          fetchPriority="high"
          loading="eager"
        />
      )}
      <div className="engage-banner__card">
        {data.informationLabel && <h2 className="engage-banner__title">{data.informationLabel}</h2>}
        {data.instructions && <p className="engage-banner__description">{data.instructions}</p>}
        {data.dateStarted && data.dateCompleted && (
          <p className="engage-banner__dates">
            <strong>
              Engagement dates: {utcMediumDate(data.dateStarted)} to {utcMediumDate(data.dateCompleted)}
            </strong>
          </p>
        )}
        <div className="engage-banner__status-row">
          <strong>Status:</strong>
          <span className={`engage-banner__status-chip engage-banner__status-chip--${status.toLowerCase()}`}>
            {status}
          </span>
        </div>
        <a className="engage-banner__cta" href={data.metURL} target="_blank" rel="noopener noreferrer">
          {data.bannerCTA}
          <i className="material-icons">open_in_new</i>
        </a>
      </div>
    </div>
  );
}
