// src/app/project/featured-documents/featured-documents.component.ts

import { Component, OnInit, ChangeDetectorRef, OnDestroy } from '@angular/core';
import { Location } from '@angular/common';
import { SearchResults } from 'app/models/search';
import { IColumnObject, TableObject } from 'app/shared/components/table-template/table-object';
import { takeWhile } from 'rxjs/operators';
import { DocumentTableRowsComponent } from '../documents/project-document-table-rows/project-document-table-rows.component';
import { TableService } from 'app/services/table.service';

@Component({
  selector: 'app-featured-documents',
  templateUrl: './featured-documents.component.html',
  styleUrls: ['./featured-documents.component.scss']
})
export class FeaturedDocumentsComponent implements OnInit, OnDestroy {
  public loading = true;
  private alive = true;
  private tableId = 'featuredDocuments';

  public tableData: TableObject = new TableObject({ component: DocumentTableRowsComponent });
  public tableColumns: IColumnObject[] = [
    {
      name: '★',
      value: 'isFeatured',
      width: 'col-1',
      nosort: true
    },
    {
      name: 'Name',
      value: 'displayName',
      width: 'col-3',
      nosort: true
    },
    {
      name: 'Date',
      value: 'datePosted',
      width: 'col-2',
      nosort: true
    },
    {
      name: 'Type',
      value: 'type',
      width: 'col-2',
      nosort: true
    },
    {
      name: 'Milestone',
      value: 'milestone',
      width: 'col-2',
      nosort: true
    },
    {
      name: 'Phase',
      value: 'projectPhase',
      width: 'col-2',
      nosort: true
    }
  ];

  constructor(
    public location: Location,
    private tableService: TableService,
    private _changeDetectionRef: ChangeDetectorRef) { }

  ngOnInit() {
    this.tableData.options.showPageCountDisplay = false;
    this.tableData.options.showPagination = false;
    this.tableData.options.showPageSizePicker = false;

    this.tableData.tableId = 'documents-table';

    this.tableData.currentPage = 1;
    this.tableData.pageSize = 5;
    this.tableData.sortBy = '-datePosted';

    this.tableService.getValue(this.tableId).pipe(takeWhile(() => this.alive)).subscribe((searchResults: SearchResults) => {
      if (searchResults.data !== 0) {
        this.tableData.totalListItems = searchResults.totalSearchCount;
        this.tableData.items = searchResults.data.map(record => {
          record['showFeatured'] = true;
          return { rowData: record };
        });

        this.tableData.columns = this.tableColumns;
        this.loading = false;

        this._changeDetectionRef.detectChanges();
      }
    });
  }

  ngOnDestroy() {
    this.alive = false;
  }
}


@if (loading() || tableData().totalListItems > 0 || featuredCards().length > 0) {
  <div class="mb-4">
    <h3 class="mb-4">Featured Documents</h3>
    @if (isTypesense()) {
      @if (loading()) {
        <div aria-busy="true" aria-label="Loading featured documents">
          @for (i of [1, 2, 3]; track i) {
            <div class="skeleton-row">
              <div class="skeleton-cell" style="flex: 3"></div>
              <div class="skeleton-cell" style="flex: 2"></div>
              <div class="skeleton-cell" style="flex: 1"></div>
            </div>
          }
        </div>
      }
      @for (card of featuredCards(); track card.id) {
        <app-search-document-card [hit]="card" [showProjectLink]="false" class="d-block" />
      }
    } @else {
      <lib-table-template [data]="tableData()" [loading]="loading()"></lib-table-template>
    }
  </div>
}

// src/app/pages/project/featured-documents.tsx
import { DOWNLOAD_COLUMN } from 'app/components/table/document-row';
import { TableTemplate } from 'app/components/table/table-template';
import { tableObject, type IColumnObject } from 'app/components/table/table-object';
import { useTable } from 'app/components/table/use-table';
import { DocumentTableRow } from './document-table-rows';
import { useProjectContext } from './project-context';

const COLUMNS: IColumnObject[] = [
  { name: '★', value: 'isFeatured', width: 'col-1', nosort: true },
  { name: 'Name', value: 'displayName', width: 'col-3', nosort: true },
  { name: 'Date', value: 'datePosted', width: 'col-2', nosort: true },
  { name: 'Type', value: 'type', width: 'col-2', nosort: true },
  { name: 'Milestone', value: 'milestone', width: 'col-2', nosort: true },
  { name: 'Phase', value: 'projectPhase', width: 'col-2', nosort: true },
  DOWNLOAD_COLUMN
];

const PAGE_SIZE = 5;

/** The project's starred documents: a fixed top five, no paging or sorting. */
export function FeaturedDocuments() {
  const { projId, lists } = useProjectContext();

  const result = useTable('featuredDocuments', {
    dataset: 'Document',
    enabled: !!projId,
    fields: [{ name: 'project', value: projId }],
    currentPage: 1,
    pageSize: PAGE_SIZE,
    sortBy: '-datePosted',
    queryModifiers: { isFeatured: 'true' }
  });

  if (!result.loading && result.totalListItems === 0) {
    return null;
  }

  const data = {
    ...tableObject({
      tableId: 'documents-table',
      component: DocumentTableRow,
      columns: COLUMNS,
      currentPage: 1,
      pageSize: PAGE_SIZE,
      sortBy: '-datePosted',
      items: result.data.map(record => ({ rowData: record })),
      totalListItems: result.totalListItems,
      data: { lists, showFeatured: true }
    }),
    options: { showHeader: true, showPageCountDisplay: false, showPagination: false, showPageSizePicker: false }
  };

  return (
    <div className="mb-4">
      <h3 className="mb-4">Featured Documents</h3>
      <TableTemplate data={data} loading={result.loading} onMessage={() => undefined} />
    </div>
  );
}
