// src/app/project/pins/pins.component.ts
import { Component, OnInit, ChangeDetectorRef, OnDestroy } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { StorageService } from 'app/services/storage.service';
import { SearchResults } from 'app/models/search';
import { PinsTableRowsComponent } from './pins-table-rows/pins-table-rows.component';
import { takeWhile } from 'rxjs/operators';
import { TableTemplate } from 'app/shared/components/table-template/table-template';
import { TableObject } from 'app/shared/components/table-template/table-object';
import { PinsService } from 'app/services/pins.service';
import { ITableMessage } from 'app/shared/components/table-template/table-row-component';

@Component({
  selector: 'app-pins',
  templateUrl: './pins.component.html',
  styleUrls: ['./pins.component.scss']
})
export class PinsComponent implements OnInit, OnDestroy {
  private alive = true;
  public loading: Boolean = true;

  public tableData: TableObject = new TableObject({ component: PinsTableRowsComponent });
  public tableColumns: any[] = [
    {
      name: 'Nation Name',
      value: 'name',
      width: 'col-8'
    },
    {
      name: 'Location',
      value: 'province',
      width: 'col-4'
    }
  ];
  constructor(
    private router: Router,
    private _changeDetectionRef: ChangeDetectorRef,
    private route: ActivatedRoute,
    private storageService: StorageService,
    private tableTemplateUtils: TableTemplate,
    private pinsService: PinsService
  ) {
  }

  ngOnInit() {
    this.tableData.tableId = 'pins-table';

    // Hide table controls
    this.tableData.options.showPageCountDisplay = false;
    this.tableData.options.showPageSizePicker = false;

    this.route.queryParamMap.pipe(takeWhile(() => this.alive)).subscribe(data => {
      // Get params from route, shove into the tableTemplateUtils so that we get a new dataset to work with.
      this.tableData = this.tableTemplateUtils.updateTableObjectWithUrlParams(data['params'], this.tableData, 'Pins');
      this.tableData.sortBy = data['params'].sortByPins ? data['params'].sortByPins : '+name';
      this._changeDetectionRef.detectChanges();
    });

    this.pinsService.getValue()
      .pipe(takeWhile(() => this.alive))
      .subscribe((searchResults: SearchResults) => {
        if (searchResults.data !== 0) {
          this.tableData.totalListItems = searchResults.totalSearchCount;
          if (this.tableData.totalListItems > 0) {
            this.tableData.items = searchResults.data.map(record => {
              return { rowData: record };
            });
          } else {
            this.tableData.items = [];
          }
          this.tableData.columns = this.tableColumns;

          this.loading = false;
          this._changeDetectionRef.detectChanges();
        }
      });
  }

  onMessageOut(msg: ITableMessage) {
    let params = {};
    switch (msg.label) {
      case 'columnSort':
        if (this.tableData.sortBy.charAt(0) === '+') {
          params['sortByPins'] = '-' + msg.data;
        } else {
          params['sortByPins'] = '+' + msg.data;
        }
        this.pinsService.fetchDataConfig.sortBy = params['sortByPins'];
        break;
      case 'pageNum':
        params['currentPagePins'] = msg.data;
        this.pinsService.fetchDataConfig.currentPage = params['currentPagePins'];
        break;
      default:
        break;
    }
    this.submit(params);
  }

  submit(params) {
    this.storageService.state.scrollPosition = { type: 'scrollPosition', data: [window.scrollX, window.scrollY] };
    this.router.navigate(
      [],
      {
        queryParams: params,
        relativeTo: this.route,
        queryParamsHandling: 'merge'
      });
    this.pinsService.refreshData();
  }

  ngOnDestroy() {
    this.alive = false;
  }
}

<div class="spinner-container" *ngIf="loading">
    <div class="spinner-new rotating"></div>
</div>

<div *ngIf="tableData.totalListItems > 0">
    <div class="row">
        <div class="col-12">
            <h2>Participating Indigenous Nations</h2>
            <lib-table-template
                [data]="tableData"
                (messageOut)="onMessageOut($event)">
            </lib-table-template>
        </div>
    </div>
    <br />
</div>

// src/app/pages/project/pins.tsx
import { useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useSearchParams } from 'react-router';
import { getPins } from 'app/api/project';
import { TableTemplate } from 'app/components/table/table-template';
import {
  tableObject,
  type IColumnObject,
  type ITableMessage,
  type TableRowProps,
} from 'app/components/table/table-object';
import {
  normalizeSortBy,
  paramsToObject,
  toggleSortDirection,
  toSearchParams,
} from 'app/components/table/table-params';
import { Constants } from 'app/utils/constants';
import { useProjectContext } from './project-context';

const COLUMNS: IColumnObject[] = [
  { name: 'Nation Name', value: 'name', width: 'col-8' },
  { name: 'Location', value: 'province', width: 'col-4' },
];

const DEFAULT_SORT = '+name';

function PinsTableRow({ rowData }: TableRowProps) {
  return (
    <tr>
      <td data-label="Nation Name" className="col-8" tabIndex={0}>
        {rowData.name}
      </td>
      <td data-label="Location" className="col-4" tabIndex={0}>
        {rowData.province}
      </td>
    </tr>
  );
}

/** Participating Indigenous Nations for the project. Its own `*Pins` query params. */
export function Pins() {
  const { projId } = useProjectContext();
  const [searchParams, setSearchParams] = useSearchParams();
  const params = useMemo(() => paramsToObject(searchParams), [searchParams]);

  const currentPage = +(params['currentPagePins'] || Constants.tableDefaults.DEFAULT_CURRENT_PAGE);
  const pageSize = +(params['pageSizePins'] || Constants.tableDefaults.DEFAULT_PAGE_SIZE);
  const sortBy = params['sortByPins'] ? normalizeSortBy(params['sortByPins']) : DEFAULT_SORT;

  const { data: result, isPending } = useQuery({
    queryKey: ['pins', projId, currentPage, pageSize, sortBy],
    enabled: !!projId,
    queryFn: async () => {
      const response = await getPins(projId, currentPage, pageSize, sortBy);
      const page = response?.[0];
      return { data: page?.results ?? [], totalListItems: page?.total_items ?? 0 };
    },
  });

  const totalListItems = result?.totalListItems ?? 0;
  if (!isPending && totalListItems === 0) {
    return null;
  }

  const data = {
    ...tableObject({
      tableId: 'pins-table',
      component: PinsTableRow,
      columns: COLUMNS,
      currentPage,
      pageSize,
      sortBy,
      items: (result?.data ?? []).map((record) => ({ rowData: record })),
      totalListItems,
    }),
    options: {
      showHeader: true,
      showPagination: true,
      showPageCountDisplay: false,
      showPageSizePicker: false,
      showTopControls: true,
      disableRowHighlight: true,
    },
  };

  function onMessage(msg: ITableMessage): void {
    switch (msg.label) {
      case 'columnSort':
        setSearchParams(
          toSearchParams({
            ...params,
            sortByPins: toggleSortDirection(sortBy, msg.data),
            currentPagePins: 1,
          }),
          { replace: true },
        );
        break;
      case 'pageNum':
        setSearchParams(toSearchParams({ ...params, currentPagePins: msg.data }), {
          replace: true,
        });
        break;
    }
  }

  return (
    <div className="mb-4">
      <h3 className="mb-4">Participating Indigenous Nations</h3>
      <TableTemplate data={data} loading={isPending} onMessage={onMessage} />
    </div>
  );
}
