// src/app/project/project-details-tab/project-details-tab.component.ts
import { Component, OnInit, ElementRef } from '@angular/core';

import { StorageService } from 'app/services/storage.service';
import { Subject } from 'rxjs';
import { ConfigService } from 'app/services/config.service';
import { NgbModalRef } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'app-project-details-tab',
  templateUrl: './project-details-tab.component.html',
  styleUrls: ['./project-details-tab-sm.component.scss', './project-details-tab-md-lg.component.scss'],
})
export class ProjectDetailsTabComponent implements OnInit {
  public project;
  public commentPeriod = null;

  constructor(
    private storageService: StorageService,
    public configService: ConfigService
  ) { }

  ngOnInit() {
    this.project = this.storageService.state.currentProject.data;
    this.commentPeriod = this.project.commentPeriodForBanner;
  }
}

<h2 class="visually-hidden">Project Details</h2>

  <div class="row">
    <div class="col-12">
      <div class="location-info">
          <p class="desc mb-4" [innerHTML]="(project()?.description?.toString() || '-') | newlines"></p>
          <dl class="row g-3 mb-4">
            <div class="col-sm-6 col-md-4 col-lg-3">
              <dt class="fw-bold text-primary mb-0 lh-sm">Proponent</dt>
              <dd class="mb-1">{{project()?.proponent?.name || "-" }}</dd>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
              <dt class="fw-bold text-primary mb-0 lh-sm">Type</dt>
              <dd class="mb-1">{{project()?.type || "-" }}</dd>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
              <dt class="fw-bold text-primary mb-0 lh-sm">Sub-type</dt>
              <dd class="mb-1">{{project()?.sector || "-" }}</dd>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
              <dt class="fw-bold text-primary mb-0 lh-sm">Nature</dt>
              <dd class="mb-1">{{project()?.nature || "No nature description available" }}</dd>
            </div>
            @if (project()) {
              <div class="col-sm-6 col-md-4 col-lg-3">
                <dt class="fw-bold text-primary mb-0 lh-sm">IAAC Involvement</dt>
                @if (project()?.CEAAInvolvement?.name==='None') {
                  <dd class="mb-1">
                    {{project()?.CEAAInvolvement?.name || "-" }}
                  </dd>
                }
                @if (project()?.CEAAInvolvement?.name!=='None') {
                  <dd class="mb-1">
                    <a target="_blank" rel="noopener" href="{{project()?.CEAALink}}">
                      {{project()?.CEAAInvolvement?.name || "-" }}
                      <i class="material-icons" style="font-size: 0.875rem; vertical-align: middle;" aria-hidden="true">open_in_new</i>
                      <span class="visually-hidden">(opens in new tab)</span>
                    </a>
                  </dd>
                }
              </div>
            }
            @if (project()?.currentPhaseName) {
              <div class="col-sm-6 col-md-4 col-lg-3">
                <dt class="fw-bold text-primary mb-0 lh-sm">Project Status</dt>
                <dd class="mb-1">{{project()?.currentPhaseName?.name || "-"}}</dd>
              </div>
            }
            @if (project()?.eacDecision) {
              <div class="col-sm-6 col-md-4 col-lg-3">
                <dt class="fw-bold text-primary mb-0 lh-sm">EAC Status</dt>
                @if (project()?.eacDecision?.name === 'Regulatory Transfer') {
                  <dd class="mb-1">
                    <a [href]="project()?.applicableRegulation?.item || 'https://www.bc-er.ca/data-reports/data-centre/'" target="_blank" rel="noopener noreferrer">
                      {{ project()?.applicableRegulation?.name || 'BC Energy Regulator' }}
                    </a>
                  </dd>
                } @else if (project()?.decisionDate) {
                  <dd class="mb-1">{{project()?.eacDecision?.name || '-'}} |
                    {{project()?.decisionDate?.toString() | date: 'longDate'}}</dd>
                } @else {
                  <dd class="mb-1">{{project()?.eacDecision?.name || '-'}}</dd>
                }
              </div>
            }
            @if (project()?.operational) {
              <div class="col-sm-6 col-md-4 col-lg-3">
                <dt class="fw-bold text-primary mb-0 lh-sm">Active Phase</dt>
                @if (project()?.operational?.date) {
                  <dd class="mb-1">{{project()?.operational?.label || '-'}} |
                    {{project()?.operational?.date?.toString() | date: 'longDate'}}</dd>
                }
                @if (!project()?.operational?.date) {
                  <dd class="mb-1">{{project()?.operational?.label || '-'}}</dd>
                }
              </div>
            }
          </dl>
        </div>
      </div>
    </div>
    <app-featured-documents></app-featured-documents>
    <app-pins></app-pins>
    <app-project-activites></app-project-activites>

// src/app/pages/project/project-details-tab.tsx
import { newlines } from 'app/utils/newlines';
import { safeHtml } from 'app/utils/safe-html';
import { longDate } from 'app/utils/utils';
import { FeaturedDocuments } from './featured-documents';
import { Pins } from './pins';
import { ProjectActivites } from './project-activites';
import { useProjectContext } from './project-context';
import './project-details-tab.css';

const BC_ENERGY_REGULATOR_LINK = 'https://www.bc-er.ca/data-reports/data-centre/';

export function ProjectDetailsTab() {
  const { project } = useProjectContext();

  return (
    <>
      <h2 className="visually-hidden">Project Details</h2>

      <div className="row">
        <div className="col-12">
          <div className="location-info">
            <p
              className="desc mb-4"
              dangerouslySetInnerHTML={safeHtml(newlines(project?.description?.toString() || '-'))}
            ></p>
            <dl className="row g-3 mb-4">
              <div className="col-sm-6 col-md-4 col-lg-3">
                <dt className="fw-bold text-primary mb-0 lh-sm">Proponent</dt>
                <dd className="mb-1">{project?.proponent?.name || '-'}</dd>
              </div>
              <div className="col-sm-6 col-md-4 col-lg-3">
                <dt className="fw-bold text-primary mb-0 lh-sm">Type</dt>
                <dd className="mb-1">{project?.type || '-'}</dd>
              </div>
              <div className="col-sm-6 col-md-4 col-lg-3">
                <dt className="fw-bold text-primary mb-0 lh-sm">Sub-type</dt>
                <dd className="mb-1">{project?.sector || '-'}</dd>
              </div>
              <div className="col-sm-6 col-md-4 col-lg-3">
                <dt className="fw-bold text-primary mb-0 lh-sm">Nature</dt>
                <dd className="mb-1">{project?.nature || 'No nature description available'}</dd>
              </div>

              {project && (
                <div className="col-sm-6 col-md-4 col-lg-3">
                  <dt className="fw-bold text-primary mb-0 lh-sm">IAAC Involvement</dt>
                  {project.CEAAInvolvement?.name === 'None' ? (
                    <dd className="mb-1">{project.CEAAInvolvement?.name || '-'}</dd>
                  ) : (
                    <dd className="mb-1">
                      <a target="_blank" rel="noopener" href={project.CEAALink}>
                        {project.CEAAInvolvement?.name || '-'}
                        <i
                          className="material-icons"
                          style={{ fontSize: '0.875rem', verticalAlign: 'middle' }}
                          aria-hidden="true"
                        >
                          open_in_new
                        </i>
                        <span className="visually-hidden">(opens in new tab)</span>
                      </a>
                    </dd>
                  )}
                </div>
              )}

              {project?.currentPhaseName && (
                <div className="col-sm-6 col-md-4 col-lg-3">
                  <dt className="fw-bold text-primary mb-0 lh-sm">Project Status</dt>
                  <dd className="mb-1">{project.currentPhaseName?.name || '-'}</dd>
                </div>
              )}

              {project?.eacDecision && (
                <div className="col-sm-6 col-md-4 col-lg-3">
                  <dt className="fw-bold text-primary mb-0 lh-sm">EAC Status</dt>
                  {project.eacDecision?.name === 'Regulatory Transfer' ? (
                    <dd className="mb-1">
                      <a
                        href={project.applicableRegulation?.item || BC_ENERGY_REGULATOR_LINK}
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        {project.applicableRegulation?.name || 'BC Energy Regulator'}
                      </a>
                    </dd>
                  ) : project.decisionDate ? (
                    <dd className="mb-1">
                      {project.eacDecision?.name || '-'} | {longDate(project.decisionDate)}
                    </dd>
                  ) : (
                    <dd className="mb-1">{project.eacDecision?.name || '-'}</dd>
                  )}
                </div>
              )}

              {project?.operational && (
                <div className="col-sm-6 col-md-4 col-lg-3">
                  <dt className="fw-bold text-primary mb-0 lh-sm">Active Phase</dt>
                  {project.operational?.date ? (
                    <dd className="mb-1">
                      {project.operational?.label || '-'} | {longDate(project.operational.date)}
                    </dd>
                  ) : (
                    <dd className="mb-1">{project.operational?.label || '-'}</dd>
                  )}
                </div>
              )}
            </dl>
          </div>
        </div>
      </div>

      <FeaturedDocuments />
      <Pins />
      <ProjectActivites />
    </>
  );
}
