// src/app/project/project-activites/project-activites.component.ts
import { Component, OnInit, OnDestroy, ViewChild, ElementRef, inject, signal, effect } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { CommonModule } from '@angular/common';
import { takeWhile } from 'rxjs/operators';

import { ActivitiesListTableRowsComponent } from './activities-list-table-rows/activities-list-table-rows.component';
import { IColumnObject, TableObject } from 'app/shared/components/table-template/table-object';
import { TableTemplate } from 'app/shared/components/table-template/table-template';
import { ITableMessage } from 'app/shared/components/table-template/table-row-component';
import { StorageService } from 'app/services/storage.service';
import { TableService } from 'app/services/table.service';
import { SearchParamObject } from 'app/services/search.service';
import { TableTemplateComponent } from 'app/shared/components/table-template/table-template.component';
import { SearchFilterTemplateComponent } from 'app/shared/components/search-filter-template/search-filter-template.component';

@Component({
  selector: 'app-project-activites',
  templateUrl: './project-activites.component.html',
  styleUrls: ['./project-activites.component.css'],
  imports: [CommonModule, TableTemplateComponent, SearchFilterTemplateComponent],
  standalone: true
})
export class ProjectActivitesComponent implements OnInit, OnDestroy {
  @ViewChild('activitiesHeader', { static: true }) activitiesHeader!: ElementRef;

  private router = inject(Router);
  private route = inject(ActivatedRoute);
  private tableTemplateUtils = inject(TableTemplate);
  private tableService = inject(TableService);
  private storageService = inject(StorageService);

  private alive = true;
  private readonly tableId = 'projectActivities';
  private projId = '';
  private tableSignal = this.tableService.getTableSignal(this.tableId);

  public loading = signal(true);
  public queryParams: Params = {};

  public tableData = signal<TableObject>(new TableObject({ component: ActivitiesListTableRowsComponent }));
  public tableColumns: IColumnObject[] = [
    {
      name: 'Headline',
      value: 'headine',
      width: 'col-10',
      nosort: true
    },
    {
      name: 'Date',
      value: 'dateAdded',
      width: 'col-2',
      nosort: true
    }
  ];

  constructor() {
    // Watch for table data changes from service
    effect(() => {
      const searchResults = this.tableSignal();
      
      // Only process when we have actual API results (not initial null value)
      if (searchResults !== null && searchResults !== undefined) {
        const updatedTableData = this.tableData();
        if (searchResults.data && Array.isArray(searchResults.data) && searchResults.data.length > 0) {
          updatedTableData.totalListItems = searchResults.totalSearchCount;
          updatedTableData.items = searchResults.data.map((record: any) => {
            return { rowData: record };
          });
          updatedTableData.columns = this.tableColumns;
          updatedTableData.options.showAllPicker = true;
        } else {
          updatedTableData.totalListItems = 0;
          updatedTableData.items = [];
        }
        this.tableData.set(updatedTableData);
        this.loading.set(false);
      }
    });
  }

  ngOnInit() {
    // Get project ID from parent route
    this.projId = this.route.parent?.snapshot.params['projId'] || '';

    const currentTableData = this.tableData();
    currentTableData.options.showPageCountDisplay = true;
    currentTableData.options.showPagination = true;
    currentTableData.tableId = 'activities-table';
    this.tableData.set(currentTableData);

    this.route.queryParamMap.pipe(takeWhile(() => this.alive)).subscribe(data => {
      const params: any = {};
      data.keys.forEach(key => params[key] = data.get(key));
      this.queryParams = { ...params };
      
      const updatedTableData = this.tableTemplateUtils.updateTableObjectWithUrlParams(params, this.tableData(), 'Activities');

      if (!params.sortBy) {
        updatedTableData.sortBy = '-dateAdded';
      }

      this.tableData.set(updatedTableData);
      
      // Fetch data
      this.tableService.fetchData(new SearchParamObject(
        this.tableId,
        params['keywordsActivities'] || '',
        'RecentActivity',
        [],
        updatedTableData.currentPage,
        updatedTableData.pageSize,
        updatedTableData.sortBy,
        { project: this.projId },
        true
      ));
    });
  }

  onMessageOut(msg: ITableMessage) {
    let params: any = {};
    switch (msg.label) {
      case 'pageNum':
        params['currentPageActivities'] = msg.data;
        break;
      case 'pageSize':
        params['pageSizeActivities'] = msg.data.value;
        if (params['pageSizeActivities'] === this.tableData().totalListItems) {
          this.loading.set(true);
        }
        params['currentPageActivities'] = 1;
        break;
    }
    this.submit(params);
  }

  executeSearch(searchPackage: any) {
    let params: any = {};
    if (searchPackage.keywords) {
      params['keywordsActivities'] = searchPackage.keywords;
      if (searchPackage.keywordsChanged) {
        params['sortByActivities'] = '-score';
      }
    } else {
      params['keywordsActivities'] = null;
      params['sortByActivities'] = '-dateAdded';
    }
    params['currentPageActivities'] = 1;
    this.submit(params);
  }

  submit(params: any) {
    this.storageService.state.scrollPosition = {
      type: 'scrollPosition',
      data: [window.scrollX, this.activitiesHeader.nativeElement.offsetTop - (this.activitiesHeader.nativeElement.clientHeight * 2)]
    };
    this.router.navigate(
      [],
      {
        queryParams: params,
        relativeTo: this.route,
        queryParamsHandling: 'merge'
      });
  }

  ngOnDestroy() {
    this.alive = false;
  }
}

@if (loading()) {
  <div class="spinner-container">
    <div class="spinner-new rotating"></div>
  </div>
}

<h2 #activitiesHeader>Activities and Updates</h2>

<section>
  <search-filter-template
    #explorePanel
    [keywordOverride]='queryParams["keywordsActivities"]'
    (searchEvent)='executeSearch($event)'>
  </search-filter-template>
</section>

<section class="tab-section">
  @if (tableData().totalListItems === 0) {
    <div>
      No recent activities.
    </div>
  }

  @if (!loading() && tableData().totalListItems > 0) {
    <lib-table-template
      [data]="tableData()"
      (messageOut)="onMessageOut($event)">
    </lib-table-template>
  }
</section>

// src/app/pages/project/project-activites.tsx
import { useMemo } from 'react';
import { useSearchParams } from 'react-router';
import { ActivityCard } from 'app/components/activity-card';
import { SearchFilterTemplate } from 'app/components/filters/search-filter-template';
import { TableTemplate } from 'app/components/table/table-template';
import { tableObject, type IColumnObject, type ITableMessage, type TableRowProps } from 'app/components/table/table-object';
import {
  paramsToObject,
  toSearchParams,
  updateTableObjectWithUrlParams
} from 'app/components/table/table-params';
import { useTable } from 'app/components/table/use-table';
import { useProjectContext } from './project-context';

const COLUMNS: IColumnObject[] = [
  { name: 'Headline', value: 'headine', width: 'col-10', nosort: true },
  { name: 'Date', value: 'dateAdded', width: 'col-2', nosort: true }
];

const DEFAULT_SORT = '-dateAdded';

function ActivityRow({ rowData }: TableRowProps) {
  return <ActivityCard rowData={rowData} tableMode showProjectInfo={false} />;
}

/** Recent activities for this project. Its own `*Activities` query params. */
export function ProjectActivites() {
  const { projId } = useProjectContext();
  const [searchParams, setSearchParams] = useSearchParams();
  const params = useMemo(() => paramsToObject(searchParams), [searchParams]);

  const base = useMemo(() => {
    const table = updateTableObjectWithUrlParams(params, tableObject({ tableId: 'activities-table', component: ActivityRow }), 'Activities');
    return params['sortByActivities'] ? table : { ...table, sortBy: DEFAULT_SORT };
  }, [params]);

  const result = useTable('projectActivities', {
    dataset: 'RecentActivity',
    enabled: !!projId,
    keywords: params['keywordsActivities'] || '',
    currentPage: base.currentPage,
    pageSize: base.pageSize,
    sortBy: base.sortBy,
    queryModifiers: { project: projId },
    populate: true
  });

  const data = {
    ...base,
    columns: COLUMNS,
    items: result.data.map(record => ({ rowData: record })),
    totalListItems: result.totalListItems,
    options: { ...base.options, showAllPicker: true, disableRowHighlight: true }
  };

  function submit(next: Record<string, any>): void {
    setSearchParams(toSearchParams(next), { replace: true });
  }

  function onMessage(msg: ITableMessage): void {
    switch (msg.label) {
      case 'pageNum':
        submit({ ...params, currentPageActivities: msg.data });
        break;
      case 'pageSize':
        submit({ ...params, pageSizeActivities: msg.data.value, currentPageActivities: 1 });
        break;
    }
  }

  return (
    <>
      <h3 className="mb-4">Activities and Updates</h3>

      <SearchFilterTemplate
        keywordOverride={params['keywordsActivities']}
        searching={result.loading}
        onSearch={searchPackage => {
          const hasKeywords = searchPackage.keywords?.trim();
          submit({
            ...params,
            keywordsActivities: hasKeywords || null,
            sortByActivities: hasKeywords && searchPackage.keywordsChanged ? '-score' : DEFAULT_SORT,
            currentPageActivities: 1
          });
        }}
      />

      <section className="tab-section">
        {data.totalListItems === 0 && !result.loading ? (
          <div>No recent activities.</div>
        ) : (
          <TableTemplate data={data} loading={result.loading} onMessage={onMessage} />
        )}
      </section>
    </>
  );
}
