// src/app/pages/project-notifications/project-notifications-table-rows.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router';
import { useQuery } from '@tanstack/react-query';
import { getAllByProjectId, isClosed, isNotStarted, isOpen } from 'app/api/commentperiod';
import { CommentPeriod } from 'app/models/commentperiod';
import type { TableRowProps } from 'app/components/table/table-object';
import { useResponsive } from 'app/state/responsive';
import { mediumDate } from 'app/utils/utils';
import { ProjectNotificationDocumentsTable } from './project-notification-documents-table';
import { ProjectNotificationDocumentsTableDetails } from './project-notification-documents-table-details';
import './project-notifications-table-rows.css';

type Tab = 'details' | 'documents' | 'commenting';

function cpStatus(pcp: string): string {
  if (!pcp || pcp === 'none') return '';
  if (pcp === 'pending') return 'Upcoming';
  return pcp.charAt(0).toUpperCase() + pcp.slice(1);
}

/**
 * Legacy comment periods carry the period name inside the instructions HTML, so it is pulled out
 * and the raw text kept as the description. Duplicates by id, and by MET URL for MET periods.
 */
function normalizePeriods(raw: CommentPeriod[]): CommentPeriod[] {
  const seenIds = new Set<string>();
  const seenUrls = new Set<string>();

  return raw
    .map((element) => {
      const fullText = element.instructions
        ? element.instructions
            .replace(/<[^>]*>/g, ' ')
            .replace(/\s+/g, ' ')
            .trim()
        : '';
      const match = fullText.match(/Comment Period on the (.*?) for /);
      element.additionalText = element.additionalText || fullText || element.informationLabel;
      element.instructions = match ? match[1] : '';
      return element;
    })
    .filter((period) => {
      if (seenIds.has(period._id)) return false;
      seenIds.add(period._id);
      if (period.isMet && period.metURL) {
        if (seenUrls.has(period.metURL)) return false;
        seenUrls.add(period.metURL);
      }
      return true;
    });
}

/** Stands in for a notification whose comment period only exists as fields on the row itself. */
function fallbackPeriod(rowData: any): CommentPeriod {
  const period = new CommentPeriod({
    _id: rowData._id,
    project: rowData._id,
    isMet: rowData.isMet,
    metURL: rowData.metURL,
    dateStarted: rowData.dateStarted,
    dateCompleted: rowData.dateCompleted,
    instructions: 'Public Comment Period',
    additionalText: '',
  });

  period.commentPeriodStatus = cpStatus(rowData.pcp);
  if (
    period.commentPeriodStatus === 'Open' &&
    (!period.daysRemaining ||
      period.daysRemaining === 'Completed' ||
      period.daysRemaining === 'None')
  ) {
    period.daysRemaining = 'Active';
  }
  return period;
}

export function ProjectNotificationsTableRow({ rowData }: TableRowProps) {
  const [activeTab, setActiveTab] = useState<Tab>('details');
  const [documentsTabLoaded, setDocumentsTabLoaded] = useState(false);
  const { isMobile } = useResponsive();
  const navigate = useNavigate();

  const hasPcp = !!rowData?.pcp && rowData.pcp !== 'none';
  // Records predating the pcp field need a lookup to know whether they have any comment periods.
  // One query serves both that check and the tab body, so opening the tab costs no second request.
  const needsLookup = !!rowData?._id && (rowData.pcp === undefined || activeTab === 'commenting');

  const { data: periods, isPending } = useQuery({
    queryKey: ['commentPeriods', rowData?._id],
    enabled: needsLookup,
    queryFn: async () => {
      const res: any = await getAllByProjectId(rowData._id);
      const list: CommentPeriod[] = Array.isArray(res) ? res : (res?.data ?? []);
      const deduped = normalizePeriods(list);
      return deduped.length === 0 && hasPcp ? [fallbackPeriod(rowData)] : deduped;
    },
  });

  const showCommentingTab = hasPcp || (periods?.length ?? 0) > 0;
  const commentPeriods = needsLookup && isPending ? null : (periods ?? []);

  function selectTab(tab: Tab): void {
    setActiveTab(tab);
    if (tab === 'documents') {
      setDocumentsTabLoaded(true);
    }
  }

  function goToCP(commentPeriod: CommentPeriod): void {
    if (commentPeriod.isMet && commentPeriod.metURL) {
      window.open(commentPeriod.metURL, '_blank');
    } else if (rowData?.associatedProjectId) {
      navigate(`/p/${rowData.associatedProjectId}/cp/${commentPeriod._id}`);
    } else if (rowData?._id) {
      navigate(`/pn/${rowData._id}/cp/${commentPeriod._id}`);
    }
  }

  function tabPaneClass(tab: Tab): string {
    return `tab-pane fade${activeTab === tab ? ' show active' : ''}`;
  }

  return (
    <tr>
      <td className="pn-location-info">
        <div className="pn-content-wrapper">
          <div className="tabs-container">
            <ul className="nav nav-tabs" role="tablist">
              <li className="nav-item" role="presentation">
                <button
                  className={`nav-link${activeTab === 'details' ? ' active' : ''}`}
                  onClick={() => selectTab('details')}
                  type="button"
                  role="tab"
                  aria-selected={activeTab === 'details'}
                >
                  {isMobile ? 'Details' : 'Project Notification Details'}
                </button>
              </li>
              <li className="nav-item" role="presentation">
                <button
                  className={`nav-link${activeTab === 'documents' ? ' active' : ''}`}
                  onClick={() => selectTab('documents')}
                  type="button"
                  role="tab"
                  aria-selected={activeTab === 'documents'}
                >
                  Documents
                </button>
              </li>
              {showCommentingTab && (
                <li className="nav-item" role="presentation">
                  <button
                    className={`nav-link${activeTab === 'commenting' ? ' active' : ''}`}
                    onClick={() => selectTab('commenting')}
                    type="button"
                    role="tab"
                    aria-selected={activeTab === 'commenting'}
                  >
                    Engagement
                  </button>
                </li>
              )}
            </ul>

            <div className="tab-content">
              <div className={tabPaneClass('details')} role="tabpanel">
                <div className="tab-section">
                  <ProjectNotificationDocumentsTableDetails rowData={rowData} />
                </div>
              </div>

              <div className={tabPaneClass('documents')} role="tabpanel">
                {documentsTabLoaded && (
                  <div className="tab-section">
                    <ProjectNotificationDocumentsTable
                      header={rowData.name?.toUpperCase() || '-'}
                      tableId={rowData._id}
                      backgroundColor="transparent"
                      rowBackgroundColor="#F7F8FA"
                    />
                  </div>
                )}
              </div>

              {showCommentingTab && (
                <div className={tabPaneClass('commenting')} role="tabpanel">
                  <div className="tab-section pn-info-block py-2">
                    {commentPeriods === null ? (
                      <div className="cp-card cp-card--skeleton">
                        <div className="cp-card__header">
                          <div
                            className="skeleton-cell"
                            style={{ width: '90px', height: '12px', borderRadius: '4px' }}
                          ></div>
                          <div
                            className="skeleton-cell"
                            style={{
                              width: '70px',
                              height: '20px',
                              borderRadius: '999px',
                              marginLeft: 'auto',
                            }}
                          ></div>
                        </div>
                        <div className="cp-card__body">
                          <div
                            className="skeleton-cell"
                            style={{
                              width: '55%',
                              height: '14px',
                              borderRadius: '4px',
                              marginBottom: '0.5rem',
                            }}
                          ></div>
                          <div
                            className="skeleton-cell"
                            style={{
                              width: '38%',
                              height: '11px',
                              borderRadius: '4px',
                              marginBottom: '0.5rem',
                            }}
                          ></div>
                          <div
                            className="skeleton-cell"
                            style={{ width: '88%', height: '11px', borderRadius: '4px' }}
                          ></div>
                        </div>
                      </div>
                    ) : commentPeriods.length < 1 ? (
                      <div className="py-2 px-3">
                        No comment periods are currently scheduled for this project notification.
                      </div>
                    ) : (
                      commentPeriods.map((cp) => (
                        <article className="card cp-card" key={cp._id}>
                          <div className="cp-card__header">
                            <span
                              className={`cp-card__status-dot${isOpen(cp) ? ' cp-card__status-dot--open' : ''}${
                                isNotStarted(cp) ? ' cp-card__status-dot--pending' : ''
                              }${isClosed(cp) ? ' cp-card__status-dot--closed' : ''}`}
                            ></span>
                            <span className="cp-card__status-label">{cp.commentPeriodStatus}</span>
                            {isOpen(cp) ? (
                              <span className="cp-card__pill cp-card__pill--open">
                                {cp.daysRemaining}
                              </span>
                            ) : isClosed(cp) ? (
                              <span className="cp-card__pill cp-card__pill--closed">
                                Closed {mediumDate(cp.dateCompleted)}
                              </span>
                            ) : isNotStarted(cp) ? (
                              <span className="cp-card__pill cp-card__pill--pending">
                                Starts {mediumDate(cp.dateStarted)}
                              </span>
                            ) : null}
                          </div>
                          <div className="cp-card__body">
                            <h3 className="cp-card__title">
                              {cp.informationLabel || cp.instructions || 'Public Comment Period'}
                            </h3>
                            {cp.dateStarted && (
                              <p className="cp-card__dates">
                                {mediumDate(cp.dateStarted)} – {mediumDate(cp.dateCompleted)}
                              </p>
                            )}
                            {cp.additionalText && (
                              <p className="cp-card__description">{cp.additionalText}</p>
                            )}
                            <button className="btn btn-epic-cta" onClick={() => goToCP(cp)}>
                              {cp.commentPeriodStatus === 'Open'
                                ? 'Share your thoughts'
                                : 'View Engagement'}
                            </button>
                          </div>
                        </article>
                      ))
                    )}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </td>
    </tr>
  );
}

// src/app/project-notifications/project-notifications-table-rows/project-notifications-table-rows.component.ts
import { Component, OnInit, ViewEncapsulation, ChangeDetectionStrategy, inject, signal, EventEmitter } from '@angular/core';
import { DatePipe } from '@angular/common';
import { Router } from '@angular/router';
import { take } from 'rxjs/operators';

import { ResponsiveService } from '../../services/responsive.service';

import { TableRowComponent, ITableMessage } from '../../shared/components/table-template/table-row-component';
import { TableObject } from '../../shared/components/table-template/table-object';
import { ProjectNotificationDocumentsTableDetailsComponent } from '../project-notification-documents-table-details/project-notification-documents-table-details.component';
import { ProjectNotificationDocumentsTableComponent } from '../project-notification-documents-table/project-notification-documents-table.component';
import { CommentPeriodService } from '../../services/commentperiod.service';
import { CommentPeriod } from '../../models/commentperiod';

@Component({
  selector: 'tr[app-project-notifications-table-rows]',
  templateUrl: './project-notifications-table-rows.component.html',
  styleUrls: ['./project-notifications-table-rows.component.css'],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ProjectNotificationDocumentsTableDetailsComponent,
    ProjectNotificationDocumentsTableComponent,
    DatePipe
],
  standalone: true
})
export class ProjectNotificationsTableRowsComponent implements TableRowComponent, OnInit {
  rowData: any;
  tableData!: TableObject;
  messageOut = new EventEmitter<ITableMessage>();
  messageIn = new EventEmitter<ITableMessage>();
  
  private responsive = inject(ResponsiveService);
  private router = inject(Router);
  public commentPeriodService = inject(CommentPeriodService);

  isMobile = this.responsive.isMobile;
  activeTab = signal<'details' | 'documents' | 'commenting'>('details');
  documentsTabLoaded = signal(false);
  commentPeriods = signal<CommentPeriod[] | null>(null);
  showCommentingTab = signal(false);

  ngOnInit() {
    if (this.rowData?.pcp && this.rowData.pcp !== 'none') {
      this.showCommentingTab.set(true);
    } else if (this.rowData && this.rowData.pcp === undefined && this.rowData._id) {
      // Check if legacy DB has any comment periods for this old record
      this.commentPeriodService.getAllByProjectId(this.rowData._id)
        .pipe(take(1))
        .subscribe({
          next: (res: any) => {
            if (res && res.data && res.data.length > 0) {
              this.showCommentingTab.set(true);
            }
          }
        });
    }
  }

  setActiveTab(tab: 'details' | 'documents' | 'commenting') {
    this.activeTab.set(tab);
    if (tab === 'documents' && !this.documentsTabLoaded()) {
      this.documentsTabLoaded.set(true);
    }
    if (tab === 'commenting' && this.commentPeriods() === null) {
      this.getCommentPeriods();
    }
  }

  cpStatus(pcp: string): string {
    if (!pcp || pcp === 'none') return '';
    if (pcp === 'pending') return 'Upcoming';
    return pcp.charAt(0).toUpperCase() + pcp.slice(1);
  }

  getCommentPeriods() {
    if (!this.rowData?._id) {
      this.commentPeriods.set([]);
      return;
    }
    this.commentPeriodService.getAllByProjectId(this.rowData._id)
      .pipe(take(1))
      .subscribe({
        next: (res: any) => {
          let deduped: CommentPeriod[] = [];
          if (res && res.data && res.data.length > 0) {
            const periods = res.data.map((element: CommentPeriod) => {
              const fullText = element.instructions
                ? element.instructions.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim()
                : '';
              const match = fullText.match(/Comment Period on the (.*?) for /);
              // Update in place: a spread copy drops the CommentPeriod getters (isEngage, ctaLabel).
              element.instructions = match ? match[1] : '';
              element.additionalText = element.additionalText || fullText || element.informationLabel;
              return element;
            });
            const seenIds = new Set<string>();
            const seenUrls = new Set<string>();
            deduped = periods.filter((p: CommentPeriod) => {
              if (seenIds.has(p._id)) return false;
              seenIds.add(p._id);
              if (p.isEngage) {
                if (seenUrls.has(p.metURL)) return false;
                seenUrls.add(p.metURL);
              }
              return true;
            });
          }

          if (deduped.length === 0 && this.rowData.pcp && this.rowData.pcp !== 'none') {
            const fallback = new CommentPeriod({
              _id: this.rowData._id,
              project: this.rowData._id,
              isMet: this.rowData.isMet,
              metURL: this.rowData.metURL,
              dateStarted: this.rowData.dateStarted,
              dateCompleted: this.rowData.dateCompleted,
              instructions: 'Public Comment Period',
              additionalText: ''
            });
            if (this.rowData.pcp) {
              fallback.commentPeriodStatus = this.cpStatus(this.rowData.pcp);
              if (fallback.commentPeriodStatus === 'Open') {
                if (!fallback.daysRemaining || fallback.daysRemaining === 'Completed' || fallback.daysRemaining === 'None') {
                  fallback.daysRemaining = 'Active';
                }
              }
            }
            deduped = [fallback];
          }

          this.commentPeriods.set(deduped);
        },
        error: () => {
          if (this.rowData.pcp && this.rowData.pcp !== 'none') {
            const fallback = new CommentPeriod({
              _id: this.rowData._id,
              project: this.rowData._id,
              isMet: this.rowData.isMet,
              metURL: this.rowData.metURL,
              dateStarted: this.rowData.dateStarted,
              dateCompleted: this.rowData.dateCompleted,
              instructions: 'Public Comment Period',
              additionalText: ''
            });
            if (this.rowData.pcp) {
              fallback.commentPeriodStatus = this.cpStatus(this.rowData.pcp);
              if (fallback.commentPeriodStatus === 'Open') {
                if (!fallback.daysRemaining || fallback.daysRemaining === 'Completed' || fallback.daysRemaining === 'None') {
                  fallback.daysRemaining = 'Active';
                }
              }
            }
            this.commentPeriods.set([fallback]);
          } else {
            this.commentPeriods.set([]);
          }
        }
      });
  }

  goToCP(commentPeriod: CommentPeriod) {
    if (commentPeriod.isEngage) {
      window.open(commentPeriod.metURL, '_blank');
    } else if (this.rowData?.associatedProjectId) {
      this.router.navigate(['p', this.rowData.associatedProjectId, 'cp', commentPeriod._id]);
    } else if (this.rowData?._id) {
      this.router.navigate(['pn', this.rowData._id, 'cp', commentPeriod._id]);
    }
  }
}

<td class="pn-location-info">
  <div class="pn-content-wrapper">
    <div class="tabs-container">
    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item" role="presentation">
        <button 
          class="nav-link" 
          [class.active]="activeTab() === 'details'"
          (click)="setActiveTab('details')"
          type="button" 
          role="tab"
          [attr.aria-selected]="activeTab() === 'details'">
          @if (isMobile()) {
            Details
          } @else {
            Project Notification Details
          }
        </button>
      </li>
      <li class="nav-item" role="presentation">
        <button 
          class="nav-link" 
          [class.active]="activeTab() === 'documents'"
          (click)="setActiveTab('documents')"
          type="button" 
          role="tab"
          [attr.aria-selected]="activeTab() === 'documents'">
          Documents
        </button>
      </li>
      @if (showCommentingTab()) {
        <li class="nav-item" role="presentation">
          <button 
            class="nav-link" 
            [class.active]="activeTab() === 'commenting'"
            (click)="setActiveTab('commenting')"
            type="button" 
            role="tab"
            [attr.aria-selected]="activeTab() === 'commenting'">
            Engagement
          </button>
        </li>
      }
    </ul>
    <div class="tab-content">
      <div 
        class="tab-pane fade" 
        [class.show]="activeTab() === 'details'"
        [class.active]="activeTab() === 'details'"
        role="tabpanel">
        <div class="tab-section">
          <app-project-notification-documents-table-details [rowData]="rowData">
          </app-project-notification-documents-table-details>
        </div>
      </div>
      <div 
        class="tab-pane fade" 
        [class.show]="activeTab() === 'documents'"
        [class.active]="activeTab() === 'documents'"
        role="tabpanel">
        @if (documentsTabLoaded()) {
          <div class="tab-section">
            <app-project-notification-documents-table [header]="rowData.name.toUpperCase() || '-'"
              [tableId]="rowData._id"
              backgroundColor="transparent"
              rowBackgroundColor="#F7F8FA">
            </app-project-notification-documents-table>
          </div>
        }
      </div>
      @if (showCommentingTab()) {
        <div 
          class="tab-pane fade" 
          [class.show]="activeTab() === 'commenting'"
          [class.active]="activeTab() === 'commenting'"
          role="tabpanel">
          <div class="tab-section pn-info-block py-2">
            @if (commentPeriods() === null) {
              @for (i of [1]; track i) {
                <div class="cp-card cp-card--skeleton">
                  <div class="cp-card__header">
                    <div class="skeleton-cell" style="width: 90px; height: 12px; border-radius: 4px"></div>
                    <div class="skeleton-cell" style="width: 70px; height: 20px; border-radius: 999px; margin-left: auto"></div>
                  </div>
                  <div class="cp-card__body">
                    <div class="skeleton-cell" style="width: 55%; height: 14px; border-radius: 4px; margin-bottom: 0.5rem"></div>
                    <div class="skeleton-cell" style="width: 38%; height: 11px; border-radius: 4px; margin-bottom: 0.5rem"></div>
                    <div class="skeleton-cell" style="width: 88%; height: 11px; border-radius: 4px"></div>
                  </div>
                </div>
              }
            } @else if (commentPeriods()!.length < 1) {
              <div class="py-2 px-3">No comment periods are currently scheduled for this project notification.</div>
            } @else {
              @for (cp of commentPeriods(); track cp._id) {
                <article class="card cp-card">
                  <div class="cp-card__header">
                    <span class="cp-card__status-dot"
                          [class.cp-card__status-dot--open]="commentPeriodService.isOpen(cp)"
                          [class.cp-card__status-dot--pending]="commentPeriodService.isNotStarted(cp)"
                          [class.cp-card__status-dot--closed]="commentPeriodService.isClosed(cp)">
                    </span>
                    <span class="cp-card__status-label">{{ cp.commentPeriodStatus }}</span>
                    @if (commentPeriodService.isOpen(cp)) {
                      <span class="cp-card__pill cp-card__pill--open">{{ cp.daysRemaining }}</span>
                    } @else if (commentPeriodService.isClosed(cp)) {
                      <span class="cp-card__pill cp-card__pill--closed">Closed {{ cp.dateCompleted | date:'MMM d, y' }}</span>
                    } @else if (commentPeriodService.isNotStarted(cp)) {
                      <span class="cp-card__pill cp-card__pill--pending">Starts {{ cp.dateStarted | date:'MMM d, y' }}</span>
                    }
                  </div>
                  <div class="cp-card__body">
                    <h3 class="cp-card__title">{{ cp.informationLabel || cp.instructions || 'Public Comment Period' }}</h3>
                    @if (cp.dateStarted) {
                      <p class="cp-card__dates">{{ cp.dateStarted | date:'MMM d, y' }} – {{ cp.dateCompleted | date:'MMM d, y' }}</p>
                    }
                    @if (cp.additionalText) {
                      <p class="cp-card__description">{{ cp.additionalText }}</p>
                    }
                    <button class="btn btn-epic-cta" (click)="goToCP(cp)">
                      {{ cp.commentPeriodStatus === 'Open' ? 'Share your thoughts' : 'View Engagement' }}
                    </button>
                  </div>
                </article>
              }
            }
          </div>
        </div>
      }
    </div>
  </div>
  </div>
</td>
