// src/app/pages/search-help.tsx
import { HeroBanner } from 'app/components/hero-banner';
import './search-help.css';

export function SearchHelp() {
  return (
    <div className="search-help">
      <HeroBanner
        title="Advanced Search Help"
        description="Learn some tips to improve your search results on our documents."
      />

      <section>
        <div className="container static-content" id="anchor-point">
          <div className="row">
            <main className="col-md-12">
              <br />
              <h3>Quotes</h3>
              <p>
                When searching for something specific, try using quotes. When search parameters are
                in quotes the search engine will search for the whole phrase rather than the
                individual words. For instance, if you search Certificate Extension, the engine will
                return content that contains those two words in any order – i.e. returning all
                results that include the word certificate, or extension. However, if you search
                “Certificate Extension”, it will search for that phrase exactly as you typed it.
                (Note: when using quotes upper- and lower-case letters count.) Using quotes can help
                locate specific information that may be buried under other content. To refine a
                search further try using a string of parameters within quotes. For example, if you
                search “Certificate Extension” “2013” it will return only certificate extensions
                that occurred in 2013.
              </p>
              <hr />
              <h3>Hyphens</h3>
              <p>
                Sometimes words are ambiguous or found in multiple situations, which makes searching
                for specific items which use these words difficult. For example, the word
                Application has many meanings and is found in various types of documents. But you
                may want to find all the documents that include the word Application except any
                “Application Information Requirements” documents. The hyphen tells the search to
                remove any results that include the words which follow it. It is like an
                “ignore/except” button. Using the hyphen, this is how you would search for all
                Applications except Application Information Requirement Documents:
              </p>
              <ul>
                <li>Application –Information Requirements</li>
              </ul>
              <p>
                This tells the search engine to search for the word Application but to remove any
                results that have the word “Information Requirements”. This tool can be wildly
                helpful when searching for information about one topic while removing all the known,
                unwanted results. This is how you would write a search to find Applications, -not
                including information requirements “in 2013”
              </p>
              <ul>
                <li>Application -Information Requirements “2013”</li>
              </ul>
              <p>
                To search by the folder structure that was in our previous site please see the list
                below for a reference:
              </p>
              <hr />
              <section>
                {/* TODO: upload the folder list PDF to MinIO and link it here */}
                <div className="row">
                  <div className="col-6">
                    <h4>Pre-Application folder Search</h4>
                    <ul>
                      <li>
                        "Pre-Application" "Application Terms of Reference/Information Requirements"
                      </li>
                      <li>"Pre-Application" "EAO Generated Documents"</li>
                      <li>"Pre-Application" "Federal Comments/Submissions"</li>
                      <li>"Pre-Application" "Notices - News Releases"</li>
                      <li>"Pre-Application" "Public Comments/Submissions"</li>
                    </ul>
                  </div>
                  <div className="col-6">
                    <h4>Certificate Extension folder Search</h4>
                    <ul>
                      <li>"Certificate Extension"</li>
                      <li>"Certificate Extension" "Proponent Comments/Correspondence"</li>
                    </ul>
                    <br />
                    <h4>Certificates Decision (Refused) Search</h4>
                    <ul>
                      <li>"Certificate Decision" "Ministers Referral Package"</li>
                    </ul>
                  </div>
                </div>
                <hr />
                <div className="row">
                  <div className="col-6">
                    <h4>Application Review folder Search</h4>
                    <ul>
                      <li>"Under Review" "Aboriginal Comments/Submissions"</li>
                      <li>"Under Review" "Application and Supporting Studies"</li>
                      <li>"Under Review" "Concurrent Permitting"</li>
                      <li>"Under Review" "EAO Generated Documents"</li>
                      <li>"Under Review" "Federal Comments/Submissions"</li>
                      <li>"Under Review" "Local Government Comments/Submissions"</li>
                      <li>"Under Review" "Notices - News Releases"</li>
                      <li>"Under Review" "Other Jurisdictions Comments/Submissions"</li>
                      <li>"Under Review" "Proponent Comments/Correspondence"</li>
                      <li>"Under Review" "Public Comments/Submissions"</li>
                    </ul>
                  </div>
                  <div className="col-6">
                    <h4>Certificate Issued folder Search</h4>
                    <ul>
                      <li>"Certificate Issued" "EA Certificate Documentation"</li>
                      <li>"Certificate Issued" "EAO Generated Documents"</li>
                      <li>"Certificate Issued" "Notices - News Releases"</li>
                      <li>"Certificate Issued" "Substantially Started Documentation"</li>
                    </ul>
                    <br />
                    <h4>Certificate Amendments folder Search</h4>
                    <ul>
                      <li>"Certificate Amendment" "Amendment - Application"</li>
                      <li>"Certificate Amendment" "Amendment Certificate"</li>
                      <li>"Certificate Amendment" "EAO Generated Documents"</li>
                    </ul>
                  </div>
                </div>
                <hr />
                <div className="row">
                  <div className="col-6">
                    <h4>Compliance &amp; Enforcement folder Search</h4>
                    <ul>
                      <li>"Compliance &amp; Enforcement" "Compliance Self-Reports:</li>
                      <li>"Compliance &amp; Enforcement" "Inspection Records"</li>
                      <li>"Compliance &amp; Enforcement" "Enforcement Actions"</li>
                    </ul>
                  </div>
                  <div className="col-6">
                    <h4>Other folder Searches</h4>
                    <ul>
                      <li>"Substantially Started Determination"</li>
                      <li>"Further Assessment"</li>
                      <li>"Projects that do no require and EA Certificate"</li>
                      <li>"Certificate Expired"</li>
                    </ul>
                  </div>
                </div>
                <hr />
                <div className="row">
                  <div className="col-6">
                    <h4>Newer folder structure Pre-Application Search</h4>
                    <ul>
                      <li>"Assessment Information" "Determination" "Project Description"</li>
                      <li>"Assessment Information" "Concurrent Permitting"</li>
                      <li>
                        "Assessment Information" "Scope" "Application Information Requirements"
                      </li>
                      <li>"Assessment Information" "Scope" "Comment Period"</li>
                      <li>"Assessment Information" "Scope" "Correspondence"</li>
                      <li>
                        "Assessment Information" "Scope" "Draft Application Information
                        Requirements"
                      </li>
                      <li>"Assessment Information" "Scope" "Fees"</li>
                      <li>"Assessment Information" "Scope" "Section 11"</li>
                      <li>"Assessment Information" "Scope" "Section 13"</li>
                      <li>"Assessment Information" "Evaluation"</li>
                      <li>"Assessment Information" "Review"</li>
                    </ul>
                  </div>
                  <div className="col-6">
                    <h4>Newer folder structure Application Review</h4>
                    <ul>
                      <li>"Assessment Information" "Review" "Application"</li>
                      <li>"Assessment Information" "Review" "Comment Period"</li>
                      <li>"Assessment Information" "Review" "Comments &amp; Submissions"</li>
                      <li>"Assessment Information" "Review" "Correspondence"</li>
                      <li>"Assessment Information" "Review" "Proponent Consultation Reports"</li>
                      <li>"Assessment Information" "Review" "Time Limit Extension"</li>
                      <li>"Assessment Information" "Review" "Time Limit Suspension"</li>
                    </ul>
                    <br />
                    <h4>Newer folder Structure EA Decision</h4>
                    <ul>
                      <li>"EA Certificate Issued" "Decision Documentation"</li>
                      <li>"EA Certificate Issued" "Notifications/News Releases"</li>
                      <li>"EA Certificate Issued" "Separate Submissions"</li>
                    </ul>
                  </div>
                </div>
              </section>
            </main>
          </div>
        </div>
      </section>
    </div>
  );
}

// src/app/search-help/search-help.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-search-help',
  templateUrl: './search-help.component.html',
  styleUrl: './search-help.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule]
})
export class SearchHelpComponent {}

<app-hero-banner
  title="Advanced Search Help"
  description="Learn some tips to improve your search results on our documents."
/>

<section>
    <div class="container static-content" id="anchor-point">
        <div class="row">
            <main class="col-md-12">
                <br>
                <h3>Quotes</h3>
                <p>
                    When searching for something specific, try using quotes. When search parameters are in quotes the search engine will search for the whole phrase rather than the individual words.
                    For instance, if you search Certificate Extension, the engine will return content that contains those two words in any order – i.e. returning all results that include the word certificate, or extension.
                    However, if you search “Certificate Extension”, it will search for that phrase exactly as you typed it. (Note: when using quotes upper- and lower-case letters count.)
                    Using quotes can help locate specific information that may be buried under other content.
                    To refine a search further try using a string of parameters within quotes. For example, if you search “Certificate Extension” “2013” it will return only certificate extensions that occurred in 2013.
                </p>
                <hr>
                <h3>Hyphens</h3>
                <p>
                    Sometimes words are ambiguous or found in multiple situations, which makes searching for specific items which use these words difficult.
                    For example, the word Application has many meanings and is found in various types of documents.
                    But you may want to find all the documents that include the word Application except any “Application Information Requirements” documents.
                    The hyphen tells the search to remove any results that include the words which follow it. It is like an “ignore/except” button.
                    Using the hyphen, this is how you would search for all Applications except Application Information Requirement Documents:
                </p>
                <ul>
                    <li>Application –Information Requirements</li>
                </ul>
                <p>
                    This tells the search engine to search for the word Application but to remove any results that have the word “Information Requirements”.
                    This tool can be wildly helpful when searching for information about one topic while removing all the known, unwanted results.
                    This is how you would write a search to find Applications, -not including information requirements “in 2013”
                </p>
                <ul>
                    <li>Application -Information Requirements “2013”</li>
                </ul>
                <p>To search by the folder structure that was in our previous site please see the list below for a reference:</p>
                <hr>
                <section>
                    <!--
                        spent some time trying to link a pdf containing the information below
                        TODO: Upload document to minio and link the document download
                        <strong>
                        <a href="~/assets/images/search-folders.pdf" >
                            folder list
                        </a>
                    </strong> -->
                    <div class="row">
                        <div class="col-6">
                            <h4>Pre-Application folder Search</h4>
                            <ul>
                                <li>"Pre-Application" "Application Terms of Reference/Information Requirements"</li>
                                <li>"Pre-Application" "EAO Generated Documents"</li>
                                <li>"Pre-Application" "Federal Comments/Submissions"</li>
                                <li>"Pre-Application" "Notices - News Releases"</li>
                                <li>"Pre-Application" "Public Comments/Submissions"</li>
                            </ul>
                        </div>
                        <div class="col-6">
                            <h4>Certificate Extension folder Search</h4>
                            <ul>
                                <li>"Certificate Extension"</li>
                                <li>"Certificate Extension" "Proponent Comments/Correspondence"</li>
                            </ul>
                            <br>
                            <h4>Certificates Decision (Refused) Search</h4>
                            <ul>
                                <li>"Certificate Decision" "Ministers Referral Package"</li>
                            </ul>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-6">
                            <h4>Application Review folder Search</h4>
                            <ul>
                                <li>"Under Review" "Aboriginal Comments/Submissions"</li>
                                <li>"Under Review" "Application and Supporting Studies"</li>
                                <li>"Under Review" "Concurrent Permitting"</li>
                                <li>"Under Review" "EAO Generated Documents"</li>
                                <li>"Under Review" "Federal Comments/Submissions"</li>
                                <li>"Under Review" "Local Government Comments/Submissions"</li>
                                <li>"Under Review" "Notices - News Releases"</li>
                                <li>"Under Review" "Other Jurisdictions Comments/Submissions"</li>
                                <li>"Under Review" "Proponent Comments/Correspondence"</li>
                                <li>"Under Review" "Public Comments/Submissions"</li>
                            </ul>
                        </div>
                        <div class="col-6">
                            <h4>Certificate Issued folder Search</h4>
                            <ul>
                                <li>"Certificate Issued" "EA Certificate Documentation"</li>
                                <li>"Certificate Issued" "EAO Generated Documents"</li>
                                <li>"Certificate Issued" "Notices - News Releases"</li>
                                <li>"Certificate Issued" "Substantially Started Documentation"</li>
                            </ul>
                            <br>
                            <h4>Certificate Amendments folder Search</h4>
                            <ul>
                                <li>"Certificate Amendment" "Amendment - Application"</li>
                                <li>"Certificate Amendment" "Amendment Certificate"</li>
                                <li>"Certificate Amendment" "EAO Generated Documents"</li>
                            </ul>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-6">
                            <h4>Compliance &amp; Enforcement folder Search</h4>
                            <ul>
                                <li>"Compliance &amp; Enforcement" "Compliance Self-Reports:</li>
                                <li>"Compliance &amp; Enforcement" "Inspection Records"</li>
                                <li>"Compliance &amp; Enforcement" "Enforcement Actions"</li>
                            </ul>
                        </div>
                        <div class="col-6">
                            <h4>Other folder Searches</h4>
                            <ul>
                                <li>"Substantially Started Determination"</li>
                                <li>"Further Assessment"</li>
                                <li>"Projects that do no require and EA Certificate"</li>
                                <li>"Certificate Expired"</li>
                            </ul>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-6">
                            <h4>Newer folder structure Pre-Application Search</h4>
                            <ul>
                                <li>"Assessment Information" "Determination" "Project Description"</li>
                                <li>"Assessment Information" "Concurrent Permitting"</li>
                                <li>"Assessment Information" "Scope" "Application Information Requirements"</li>
                                <li>"Assessment Information" "Scope" "Comment Period"</li>
                                <li>"Assessment Information" "Scope" "Correspondence"</li>
                                <li>"Assessment Information" "Scope" "Draft Application Information Requirements"</li>
                                <li>"Assessment Information" "Scope" "Fees"</li>
                                <li>"Assessment Information" "Scope" "Section 11"</li>
                                <li>"Assessment Information" "Scope" "Section 13"</li>
                                <li>"Assessment Information" "Evaluation"</li>
                                <li>"Assessment Information" "Review"</li>
                            </ul>
                        </div>
                        <div class="col-6">
                            <h4>Newer folder structure Application Review</h4>
                            <ul>
                                <li>"Assessment Information" "Review" "Application"</li>
                                <li>"Assessment Information" "Review" "Comment Period"</li>
                                <li>"Assessment Information" "Review" "Comments &amp; Submissions"</li>
                                <li>"Assessment Information" "Review" "Correspondence"</li>
                                <li>"Assessment Information" "Review" "Proponent Consultation Reports"</li>
                                <li>"Assessment Information" "Review" "Time Limit Extension"</li>
                                <li>"Assessment Information" "Review" "Time Limit Suspension"</li>
                            </ul>
                            <br>
                            <h4>Newer folder Structure EA Decision</h4>
                            <ul>
                                <li>"EA Certificate Issued" "Decision Documentation"</li>
                                <li>"EA Certificate Issued" "Notifications/News Releases"</li>
                                <li>"EA Certificate Issued" "Separate Submissions"</li>
                            </ul>
                        </div>
                    </div>
                </section>
            </main>
        </div>
    </div>
<section>
