// src/app/components/hero-banner.tsx
import { Link } from 'react-router';
import './hero-banner.css';

export interface HeroBannerAction {
  label: string;
  routerLink?: string;
  href?: string;
  icon?: string;
  target?: string;
  rel?: string;
  title?: string;
}

interface HeroBannerProps {
  title: string;
  description: string;
  actions?: HeroBannerAction[];
  backgroundImage?: string;
}

// Remove focus from the link after clicking to prevent a stuck hover state
function blurOnClick(event: React.MouseEvent<HTMLAnchorElement>): void {
  const target = event.currentTarget;
  setTimeout(() => target.blur(), 0);
}

export function HeroBanner({ title, description, actions = [], backgroundImage }: HeroBannerProps) {
  return (
    <div className="hero-banner" style={{ backgroundImage: backgroundImage ? `url(${backgroundImage})` : '' }}>
      <div className="container">
        <div className="container-inner">
          <div className="hero-banner__content">
            <div tabIndex={0}>
              <h1>{title}</h1>
              <p>{description}</p>
            </div>
            {actions.length > 0 && (
              <div className="hero-banner__actions d-flex flex-column flex-sm-row gap-3">
                {actions.map(action => (
                  action.routerLink ? (
                    <Link
                      key={action.label}
                      className="btn hero-banner-btn slide-l-btn"
                      to={action.routerLink}
                      title={action.title || action.label}
                    >
                      {action.icon && <i className="material-icons">{action.icon}</i>}
                      <span>{action.label}</span>
                    </Link>
                  ) : action.href ? (
                    <a
                      key={action.label}
                      className="btn hero-banner-btn slide-l-btn"
                      href={action.href}
                      target={action.target || '_self'}
                      rel={action.rel || ''}
                      title={action.title || action.label}
                      onClick={blurOnClick}
                    >
                      {action.icon && <i className="material-icons">{action.icon}</i>}
                      <span>{action.label}</span>
                    </a>
                  ) : null
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// src/app/shared/hero-banner/hero-banner.component.ts
import { Component, ChangeDetectionStrategy, input, computed } from '@angular/core';

import { RouterModule } from '@angular/router';

export interface HeroBannerAction {
  label: string;
  routerLink?: string;
  href?: string;
  icon?: string;
  target?: string;
  rel?: string;
  title?: string;
}

@Component({
  selector: 'app-hero-banner',
  templateUrl: './hero-banner.component.html',
  styleUrl: './hero-banner.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterModule],
  standalone: true
})
export class HeroBannerComponent {
  title = input.required<string>();
  description = input.required<string>();
  actions = input<HeroBannerAction[]>([]);
  backgroundImage = input<string>();
  
  backgroundStyle = computed(() => {
    const bgImage = this.backgroundImage();
    return bgImage ? `url(${bgImage})` : '';
  });
  
  onExternalLinkClick(event: MouseEvent): void {
    // Remove focus from the link after clicking to prevent stuck hover state
    const target = event.currentTarget as HTMLElement;
    setTimeout(() => target.blur(), 0);
  }
}

<div class="hero-banner" [style.backgroundImage]="backgroundStyle()">
  <div class="container">
    <div class="container-inner">
      <div class="hero-banner__content">
        <div tabindex="0">
          <h1>{{ title() }}</h1>
          <p>{{ description() }}</p>
        </div>
        @if (actions().length > 0) {
          <div class="hero-banner__actions d-flex flex-column flex-sm-row gap-3">
            @for (action of actions(); track action.label) {
              @if (action.routerLink) {
                <a 
                  class="btn hero-banner-btn slide-l-btn" 
                  [routerLink]="action.routerLink"
                  [title]="action.title || action.label">
                  @if (action.icon) {
                    <i class="material-icons">{{ action.icon }}</i>
                  }
                  <span>{{ action.label }}</span>
                </a>
              } @else if (action.href) {
                <a 
                  class="btn hero-banner-btn slide-l-btn" 
                  [href]="action.href"
                  [target]="action.target || '_self'"
                  [rel]="action.rel || ''"
                  [title]="action.title || action.label"
                  (click)="onExternalLinkClick($event)">
                  @if (action.icon) {
                    <i class="material-icons">{{ action.icon }}</i>
                  }
                  <span>{{ action.label }}</span>
                </a>
              }
            }
          </div>
        }
      </div>
    </div>
  </div>
</div>
