// src/app/pages/news.tsx
import { useMemo } from 'react';
import { useSearchParams } from 'react-router';
import { ActivityCard } from 'app/components/activity-card';
import { HeroBanner } from 'app/components/hero-banner';
import { SearchFilterTemplate } from 'app/components/filters/search-filter-template';
import { TableTemplate } from 'app/components/table/table-template';
import { tableObject, type IColumnObject, type ITableMessage, type TableRowProps } from 'app/components/table/table-object';
import {
  paramsToObject,
  toggleSortDirection,
  toSearchParams,
  updateTableObjectWithUrlParams
} from 'app/components/table/table-params';
import { useTable } from 'app/components/table/use-table';

const TABLE_ID = 'news';

const TABLE_COLUMNS: IColumnObject[] = [
  { name: 'Headline', value: 'headline', width: 'col-10', nosort: true },
  { name: 'Date', value: 'dateAdded', width: 'col-2', nosort: false }
];

function NewsRow({ rowData }: TableRowProps) {
  return <ActivityCard rowData={rowData} tableMode />;
}

export function News() {
  const [searchParams, setSearchParams] = useSearchParams();
  const params = useMemo(() => paramsToObject(searchParams), [searchParams]);

  const base = useMemo(() => {
    const table = updateTableObjectWithUrlParams(params, tableObject({ component: NewsRow }));
    // The shared default is the document field; activities are dated with dateAdded.
    return table.sortBy === '-datePosted' ? { ...table, sortBy: '-dateAdded' } : table;
  }, [params]);

  const result = useTable(TABLE_ID, {
    dataset: 'RecentActivity',
    keywords: params['keywords'] || '',
    currentPage: base.currentPage,
    pageSize: base.pageSize,
    sortBy: base.sortBy,
    populate: true
  });

  const data = {
    ...base,
    columns: TABLE_COLUMNS,
    items: result.data.map(record => ({ rowData: record })),
    totalListItems: result.totalListItems,
    options: {
      ...base.options,
      showPageCountDisplay: true,
      showPagination: true,
      showAllPicker: true,
      disableRowHighlight: true
    }
  };

  function submit(next: Record<string, any>): void {
    setSearchParams(toSearchParams(next), { replace: true });
  }

  function onMessage(msg: ITableMessage): void {
    switch (msg.label) {
      case 'columnSort':
        submit({ ...params, sortBy: toggleSortDirection(base.sortBy, msg.data, '-'), currentPage: 1 });
        break;
      case 'pageNum':
        submit({ ...params, currentPage: msg.data });
        break;
      case 'pageSize':
        submit({ ...params, pageSize: msg.data.value, currentPage: 1 });
        break;
    }
  }

  return (
    <main>
      <HeroBanner
        title="Activities & Updates"
        description="Find activities and updates for environmental assessment projects in British Columbia. Click on the project info button to view the project details page."
        backgroundImage="/assets/images/hero-banner.jpg"
      />

      <section className="project-list table-container">
        <div className="container">
          <section className="mb-4 pt-0 pb-0">
            <SearchFilterTemplate
              onSearch={searchEvent =>
                submit({ ...params, currentPage: 1, keywords: searchEvent.keywords || null })
              }
              searching={result.loading}
            />
          </section>
          {!result.loading && data.totalListItems === 0 ? (
            <div className="text-center my-5">
              <p className="text-muted">No activities found</p>
            </div>
          ) : (
            <TableTemplate data={data} loading={result.loading} onMessage={onMessage} />
          )}
        </div>
      </section>
    </main>
  );
}

// src/app/news/news.component.ts
import { Component, OnInit, OnDestroy, ChangeDetectionStrategy, signal, inject, effect, untracked } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { takeWhile } from 'rxjs/operators';

import { SearchParamObject } from 'app/services/search.service';
import { TableService } from 'app/services/table.service';
import { LoadingStateService } from 'app/services/loading-state.service';
import { IColumnObject, TableObject } from 'app/shared/components/table-template/table-object';
import { ITableMessage } from 'app/shared/components/table-template/table-row-component';
import { TableTemplate } from 'app/shared/components/table-template/table-template';
import { TableTemplateComponent } from 'app/shared/components/table-template/table-template.component';
import { NewsListTableRowsComponent } from './news-list-table-rows/news-list-table-rows.component';
import { HeroBannerComponent } from 'app/shared/hero-banner/hero-banner.component';
import { SearchFilterTemplateComponent } from 'app/shared/components/search-filter-template/search-filter-template.component';

@Component({
  selector: 'app-news',
  templateUrl: './news.component.html',
  styleUrl: './news.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule, TableTemplateComponent, HeroBannerComponent, SearchFilterTemplateComponent],
  standalone: true
})
export class NewsListComponent implements OnInit, OnDestroy {
  private router = inject(Router);
  private route = inject(ActivatedRoute);
  private tableTemplateUtils = inject(TableTemplate);
  private tableService = inject(TableService);
  private loadingState = inject(LoadingStateService);

  private tableId = 'news';
  private alive = true;

  loading = this.loadingState.getOperationState('table-news');
  tableData = signal<TableObject>(new TableObject({ component: NewsListTableRowsComponent }));
  
  tableColumns: IColumnObject[] = [
    {
      name: 'Headline',
      value: 'headline',
      width: 'col-10',
      nosort: true
    },
    {
      name: 'Date',
      value: 'dateAdded',
      width: 'col-2',
      nosort: false
    }
  ];

  constructor() {
    // Watch for table data changes from service
    const tableSignal = this.tableService.getTableSignal(this.tableId);
    effect(() => {
      const searchResults = tableSignal();
      
      // Only process if we have valid data and it's not the initial null state
      if (searchResults && searchResults.data && searchResults.totalSearchCount !== undefined) {
        // Use untracked to read current tableData without creating a dependency
        const currentTableData = untracked(() => this.tableData());
        const newTableData = new TableObject({
          component: NewsListTableRowsComponent,
          pageSize: currentTableData.pageSize,
          currentPage: currentTableData.currentPage,
          sortBy: currentTableData.sortBy
        });

        newTableData.totalListItems = searchResults.totalSearchCount;
        newTableData.items = searchResults.data.map((record: any) => ({ rowData: record }));
        newTableData.columns = this.tableColumns;
        newTableData.options.showPageCountDisplay = true;
        newTableData.options.showPagination = true;
        newTableData.options.showAllPicker = true;

        this.tableData.set(newTableData);
      }
    });
  }

  ngOnInit(): void {
    // Subscribe to query params and fetch data
    this.route.queryParamMap.pipe(takeWhile(() => this.alive)).subscribe(data => {
      const params = (data as any)['params'] || {};
      
      let updatedTableData = this.tableTemplateUtils.updateTableObjectWithUrlParams(params, this.tableData());

      if (updatedTableData.sortBy === '-datePosted') {
        updatedTableData.sortBy = '-dateAdded';
      }

      this.tableData.set(updatedTableData);

      // Fetch data with current params
      this.tableService.fetchData(new SearchParamObject(
        this.tableId,
        params['keywords'] || '',
        'RecentActivity',
        [],
        updatedTableData.currentPage,
        updatedTableData.pageSize,
        updatedTableData.sortBy,
        {},
        true
      ));
    });
  }

  onMessageOut(msg: ITableMessage): void {
    const params: Params = {};
    const currentTableData = this.tableData();
    const currentParams = this.route.snapshot.queryParams;
    
    switch (msg.label) {
      case 'columnSort':
        params['sortBy'] = this.toggleSortDirection(msg.data);
        params['currentPage'] = 1;
        break;
      case 'pageNum':
        params['currentPage'] = msg.data;
        break;
      case 'pageSize':
        params['pageSize'] = msg.data.value;
        params['currentPage'] = 1;
        break;
    }
    
    this.submit({ ...currentParams, ...params });
  }

  private toggleSortDirection(field: string): string {
    const currentSort = this.tableData().sortBy;
    
    // If we're sorting by the same field, toggle direction
    if (currentSort?.includes(field)) {
      return (currentSort?.[0] === '+' ? '-' : '+') + field;
    }
    
    // Default to descending for new field
    return '-' + field;
  }

  submit(params: Params): void {
    this.router.navigate([], {
      queryParams: params,
      relativeTo: this.route
    });
  }

  ngOnDestroy(): void {
    this.alive = false;
  }

  executeSearch(searchEvent: any): void {
    const params: Params = {
      ...this.route.snapshot.queryParams,
      currentPage: 1
    };
    
    if (searchEvent.keywords) {
      params['keywords'] = searchEvent.keywords;
    } else {
      delete params['keywords'];
    }
    
    this.submit(params);
  }
}

<main>
  <app-hero-banner [title]="'Activities & Updates'"
    [description]="'Find activities and updates for environmental assessment projects in British Columbia. Click on the project info button to view the project details page.'"
    [backgroundImage]="'/assets/images/hero-banner.jpg'">
  </app-hero-banner>

  <section class="project-list table-container">
    <div class="container">
      <section class="mb-4 pt-0 pb-0">
        <search-filter-template (searchEvent)='executeSearch($event)' [searching]="loading()">
        </search-filter-template>
      </section>
      @if (!loading() && tableData().totalListItems === 0) {
      <div class="text-center my-5">
        <p class="text-muted">No activities found</p>
      </div>
      } @else {
      <lib-table-template [data]="tableData()" [loading]="loading()" (messageOut)="onMessageOut($event)">
      </lib-table-template>
      }
    </div>
  </section>
</main>
