// src/app/gate/gate.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  ElementRef,
  afterNextRender,
  inject,
  signal,
  viewChild
} from '@angular/core';
import { GateService } from 'app/services/gate.service';

/** Password curtain shown instead of the app while ACCESS_GATE is true. */
@Component({
  selector: 'app-gate',
  templateUrl: './gate.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true
})
export class GateComponent {
  private gate = inject(GateService);
  private passwordInput = viewChild.required<ElementRef<HTMLInputElement>>('password');

  error = signal('');
  busy = signal(false);

  constructor() {
    afterNextRender(() => this.passwordInput().nativeElement.focus());
  }

  async submit(event: Event): Promise<void> {
    event.preventDefault();
    if (this.busy()) {
      return;
    }
    this.busy.set(true);
    this.error.set('');
    try {
      if (!(await this.gate.unlock(this.passwordInput().nativeElement.value))) {
        this.error.set('Incorrect password');
      }
    } catch {
      this.error.set('Could not check the password. Please try again.');
    } finally {
      this.busy.set(false);
    }
  }
}

<section class="container static-content">
  <div class="row">
    <main class="col-md-6">
      <h1>EPIC is not open to the public yet</h1>
      <p>Enter the access password to continue.</p>
      <form (submit)="submit($event)">
        <div class="form-group">
          <label for="gate-password" class="control-label">Password</label>
          <input
            #password
            id="gate-password"
            name="password"
            class="form-control"
            type="password"
            autocomplete="current-password"
            [attr.aria-invalid]="error() ? 'true' : null"
            [attr.aria-describedby]="error() ? 'gate-error' : null"
          />
        </div>
        @if (error()) {
          <p id="gate-error" class="text-danger" role="alert">{{ error() }}</p>
        }
        <button type="submit" class="btn btn-primary" [disabled]="busy()">Continue</button>
      </form>
    </main>
  </div>
</section>

// src/app/layout/gate.tsx
import { useRef, useState } from 'react';
import { unlock } from 'app/state/gate';

/** Password curtain shown instead of the app while ACCESS_GATE is true. */
export function Gate() {
  const password = useRef<HTMLInputElement>(null);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);

  async function submit(event: React.FormEvent): Promise<void> {
    event.preventDefault();
    if (busy) {
      return;
    }
    setBusy(true);
    setError('');
    try {
      if (!(await unlock(password.current?.value ?? ''))) {
        setError('Incorrect password');
      }
    } catch {
      setError('Could not check the password. Please try again.');
    } finally {
      setBusy(false);
    }
  }

  return (
    <section className="container static-content">
      <div className="row">
        <main className="col-md-6">
          <h1>EPIC is not open to the public yet</h1>
          <p>Enter the access password to continue.</p>
          <form onSubmit={submit}>
            <div className="form-group">
              <label htmlFor="gate-password" className="control-label">Password</label>
              <input
                ref={password}
                id="gate-password"
                name="password"
                className="form-control"
                type="password"
                autoComplete="current-password"
                autoFocus
                aria-invalid={error ? 'true' : undefined}
                aria-describedby={error ? 'gate-error' : undefined}
              />
            </div>
            {error && (
              <p id="gate-error" className="text-danger" role="alert">{error}</p>
            )}
            <button type="submit" className="btn btn-primary" disabled={busy}>Continue</button>
          </form>
        </main>
      </div>
    </section>
  );
}
