// src/app/header/header.component.ts
import { Component, ChangeDetectionStrategy, signal, inject, PLATFORM_ID, effect, computed } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { Router, RouterModule, NavigationEnd } from '@angular/router';
import { ApiService } from '../services/api';
import { ConfigService } from '../services/config.service';
import { LoadingStateService } from '../services/loading-state.service';
import { filter, fromEvent } from 'rxjs';
import { debounceTime } from 'rxjs/operators';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrl: './header.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterModule],
})
export class HeaderComponent {
  private apiService = inject(ApiService);
  private configService = inject(ConfigService);
  private platformId = inject(PLATFORM_ID);
  public router = inject(Router);
  
  // Public access to loading state service
  public loadingState = inject(LoadingStateService);
  
  // Reactive banner values - update when config changes
  envName = computed(() => this.configService.config().ENVIRONMENT || 'local');
  bannerColour = computed(() => this.configService.config().BANNER_COLOUR ?? 'red');
  showBanner = computed(() => {
    const env = this.envName();
    const colour = this.bannerColour();
    const hasValidColor = !!colour && colour !== 'no-banner-colour-set';
    return env === 'local' || (!!env && hasValidColor);
  });
  
  currentUrl = signal<string>('');
  
  constructor() {
    // Update header height when banner visibility changes
    effect(() => {
      this.showBanner();
      if (isPlatformBrowser(this.platformId)) {
        this.updateHeaderHeight();
      }
    });

    if (isPlatformBrowser(this.platformId)) {
      // Track current URL and update header height on navigation
      this.currentUrl.set(this.router.url);
      this.router.events
        .pipe(filter(event => event instanceof NavigationEnd), takeUntilDestroyed())
        .subscribe(() => {
          this.currentUrl.set(this.router.url);
          this.updateHeaderHeight();
        });
      
      // Update header height on window resize
      fromEvent(window, 'resize')
        .pipe(debounceTime(100), takeUntilDestroyed())
        .subscribe(() => this.updateHeaderHeight());
    }
  }

  private updateHeaderHeight(): void {
    setTimeout(() => {
      const headerElement = document.querySelector('.app-header') as HTMLElement;
      const totalHeight = headerElement ? `${headerElement.offsetHeight}px` : '0px';
      document.documentElement.style.setProperty('--header-total-height', totalHeight);
    }, 0);
  }

  // ngOnInit not needed - banner values are computed signals that react to config changes

  closeMenus(): void {
    if (isPlatformBrowser(this.platformId)) {
      const mainNav = document.getElementById('mainNav');
      mainNav?.classList.remove('show');
      
      // Close any open Bootstrap dropdowns
      const dropdowns = document.querySelectorAll('.dropdown-menu.show');
      dropdowns.forEach(dropdown => dropdown.classList.remove('show'));
    }
  }
}

<header class="app-header"
  id="header"
  [ngClass]="{
    'app-header--flex': (router.url.startsWith('/projects')),
    'app-header--solid': (router.url.startsWith('/p/'))}">
  <nav class="navbar navbar-expand-md justify-content-between">
    <a class="navbar-brand"
      title="Environmental Assessment Office Project Information Centre"
      tabindex="0"
      routerLink="/home">
      <span class="navbar-brand__title">EPIC</span>
    </a>
    <div *ngIf="showBanner"
      class="env-banner"
      tabindex="0"
      [ngClass]="bannerColour">
      This is the&nbsp;<strong>{{envName}}</strong>&nbsp;environment. The content you are viewing is not final and
      subject to change.
    </div>
    <button class="navbar-toggler"
      tabindex="0"
      type="button"
      title="Toggle Main Navigation"
      data-toggle="collapse"
      data-target="#mainNav"
      aria-controls="navbarText"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <i class="material-icons">menu</i>
      <span>MENU</span>
    </button>
    <div class="collapse navbar-collapse"
      id="mainNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link"
            tabindex="0"
            (focus)="projectInfoFocused = false;"
            title="Find EAO Projects in British Columbia"
            routerLink="/projects">
            <span class="icon align-middle"><i class="material-icons">pin_drop</i></span>
            <span>Map View</span>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle"
            id="searchProjects"
            tabindex="0"
            data-trigger="manual"
            (click)="projectInfoFocused = false"
            (focus)="onFocus('projectInfo')"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"><span>Project Information</span><span class="caret"></span>
          </a>
          <div class="dropdown-menu dropdown-menu-right"
            [class.show]="projectInfoFocused === true"
            aria-labelledby="searchProjects">
            <a class="dropdown-item"
              href="/projects-list"
              [routerLink]="['/projects-list']"
              tabindex="0"
              title="List Projects">
              <span class="icon align-middle"><i class="material-icons">list</i></span>
              <strong>List of Projects</strong>
              <span class="dd-item-desc">Access all information relating to projects that have been involved with an
                environmental assessment in British Columbia</span>
            </a>
            <a class="dropdown-item"
              href="/project-notifications"
              [routerLink]="['/project-notifications']"
              tabindex="0"
              title="Project Notifications">
              <span class="icon align-middle"><i class="material-icons">view_list</i></span>
              <strong>List of Project Notifications</strong>
              <span class="dd-item-desc">Access information related to Project Notifications</span>
            </a>
            <a class="dropdown-item"
              href="/search"
              [routerLink]="['/search']"
              tabindex="0"
              title="Search Documents">
              <span class="icon align-middle"><i class="material-icons">search</i></span>
              <strong>All Documents</strong>
              <span class="dd-item-desc">Access a list of all documents associated with any projects involved with an
                environmental assessment in British Columbia</span>
            </a>
          </div>

        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle"
            id="aboutMMTI"
            tabindex="0"
            data-toggle="dropdown"
            aria-haspopup="true"
            (click)="eaProcessFocused = false"
            (focus)="onFocus('eaProcess')"
            aria-expanded="false"><span>The EA Process</span><span class="caret"></span>
          </a>
          <div class="dropdown-menu dropdown-menu-right"
            [class.show]="eaProcessFocused === true"
            aria-labelledby="aboutMMTI">
            <a class="dropdown-item"
              href="/legislation"
              [routerLink]="['/legislation']"
              tabindex="0">
              <strong>Legislation</strong>
              <span class="dd-item-desc">Learn about the legislation and regulations that apply to environmental
                assessments in the province of British Columbia.</span>
            </a>
            <a class="dropdown-item"
              href="/process"
              [routerLink]="['/process']"
              tabindex="0">
              <strong>Process & Procedures</strong>
              <span class="dd-item-desc">Learn more about how the Environmental Assessment Office neutrally administers
                a process that holds all participants accountable.</span>
            </a>
            <a class="dropdown-item"
              href="/compliance-oversight"
              [routerLink]="['/compliance-oversight']"
              tabindex="0">
              <strong>Compliance Oversight</strong>
              <span class="dd-item-desc">Learn about how we collaborate with other agencies to coordinate oversight of
                environmental assessment projects.</span>
            </a>
            <a class="dropdown-item"
              href="https://www2.gov.bc.ca/gov/content?id=525CA0BFCC5441C2B8FABCCF7B14004D"
              target="_blank"
              rel="noopener"
              tabindex="0">
              <strong>Dispute Resolution</strong>
              <span class="dd-item-desc">Learn about dispute resolution between First Nations and the Province.</span>
            </a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link"
            tabindex="0"
            (focus)="eaProcessFocused = false"
            title="Contact Us"
            routerLink="/contact">
            <span>Contact Us</span>
          </a>
        </li>
      </ul>
    </div>
  </nav>
  <div hidden
    class="alert alert-danger alert-dismissible"
    id="browser-alert">
    <i class="material-icons">error</i><strong> Attention: </strong>This website is not supported by Internet Explorer
    and Microsoft Edge, please use Google Chrome or Firefox.
    <button type="button"
      class="close"
      data-dismiss="alert"
      aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</header>

// src/app/layout/header.tsx
import { useEffect, useState } from 'react';
import { Link, useLocation } from 'react-router';
import { getConfig } from 'app/config/config';
import { useIsLoading } from 'app/state/loading-state';
import './header.css';

function updateHeaderHeight(): void {
  const headerElement = document.querySelector('.app-header') as HTMLElement | null;
  const totalHeight = headerElement ? `${headerElement.offsetHeight}px` : '0px';
  document.documentElement.style.setProperty('--header-total-height', totalHeight);
}

function closeMenus(): void {
  document.getElementById('mainNav')?.classList.remove('show');
  document.querySelectorAll('.dropdown-menu.show').forEach(dropdown => dropdown.classList.remove('show'));
}

export function Header() {
  const { pathname } = useLocation();
  const isLoading = useIsLoading();
  const [config] = useState(getConfig);

  const envName = config.ENVIRONMENT || 'local';
  const bannerColour = config.BANNER_COLOUR ?? 'red';
  const hasValidColour = !!bannerColour && bannerColour !== 'no-banner-colour-set';
  const showBanner = envName === 'local' || (!!envName && hasValidColour);

  useEffect(() => {
    updateHeaderHeight();
    let timeout: ReturnType<typeof setTimeout>;
    const onResize = () => {
      clearTimeout(timeout);
      timeout = setTimeout(updateHeaderHeight, 100);
    };
    window.addEventListener('resize', onResize);
    return () => {
      clearTimeout(timeout);
      window.removeEventListener('resize', onResize);
    };
  }, [pathname, showBanner]);

  return (
    <header
      className={`app-header${pathname.startsWith('/projects') ? ' app-header--flex' : ''}${pathname.startsWith('/p/') ? ' app-header--solid' : ''}`}
      id="header"
    >
      <nav className={`navbar navbar-expand-md justify-content-between${isLoading ? ' navbar-loading' : ''}`}>
        <Link
          className="navbar-brand"
          title="Environmental Assessment Office Project Information Centre"
          tabIndex={0}
          to="/"
        >
          <span className="navbar-brand__title">EPIC</span>
        </Link>
        <button
          className="navbar-toggler"
          tabIndex={0}
          type="button"
          title="Toggle Main Navigation"
          data-bs-toggle="collapse"
          data-bs-target="#mainNav"
          aria-controls="navbarText"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i className="material-icons">menu</i>
          <span>MENU</span>
        </button>
        <div className="collapse navbar-collapse" id="mainNav">
          <ul className="navbar-nav">
            <li className="nav-item">
              <Link className="nav-link" to="/projects" title="Find EAO Projects in British Columbia" onClick={closeMenus}>
                <span>Map View</span>
              </Link>
            </li>
            <li className="nav-item dropdown">
              <a
                className="nav-link dropdown-toggle"
                id="searchProjects"
                role="button"
                data-bs-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                <span>Project Information</span><span className="caret"></span>
              </a>
              <div className="dropdown-menu dropdown-menu-end" aria-labelledby="searchProjects">
                <Link className="dropdown-item" to="/projects-list" title="List Projects" onClick={closeMenus}>
                  <div className="dd-item-header">
                    <span className="icon align-middle"><i className="material-icons">list</i></span>
                    <strong>List of Projects</strong>
                  </div>
                  <span className="dd-item-desc">Access all information relating to projects that have been involved with an
                    environmental assessment in British Columbia</span>
                </Link>
                <Link className="dropdown-item" to="/project-notifications" title="Project Notifications" onClick={closeMenus}>
                  <div className="dd-item-header">
                    <span className="icon align-middle"><i className="material-icons">view_list</i></span>
                    <strong>List of Project Notifications</strong>
                  </div>
                  <span className="dd-item-desc">Access information related to Project Notifications</span>
                </Link>
                <Link className="dropdown-item" to="/search" title="Search Documents" onClick={closeMenus}>
                  <div className="dd-item-header">
                    <span className="icon align-middle"><i className="material-icons">search</i></span>
                    <strong>All Documents</strong>
                  </div>
                  <span className="dd-item-desc">Access a list of all documents associated with any projects involved with an
                    environmental assessment in British Columbia</span>
                </Link>
              </div>
            </li>
            <li className="nav-item dropdown">
              <a
                className="nav-link dropdown-toggle"
                id="aboutMMTI"
                role="button"
                data-bs-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                <span>The EA Process</span><span className="caret"></span>
              </a>
              <div className="dropdown-menu dropdown-menu-end" aria-labelledby="aboutMMTI">
                <Link className="dropdown-item" to="/legislation" onClick={closeMenus}>
                  <strong>Legislation</strong>
                  <span className="dd-item-desc">Learn about the legislation and regulations that apply to environmental
                    assessments in the province of British Columbia.</span>
                </Link>
                <Link className="dropdown-item" to="/process" onClick={closeMenus}>
                  <strong>Process &amp; Procedures</strong>
                  <span className="dd-item-desc">Learn more about how the Environmental Assessment Office neutrally administers
                    a process that holds all participants accountable.</span>
                </Link>
                <Link className="dropdown-item" to="/compliance-oversight" onClick={closeMenus}>
                  <strong>Compliance Oversight</strong>
                  <span className="dd-item-desc">Learn about how we collaborate with other agencies to coordinate oversight of
                    environmental assessment projects.</span>
                </Link>
                <a
                  className="dropdown-item"
                  href="https://www2.gov.bc.ca/gov/content?id=525CA0BFCC5441C2B8FABCCF7B14004D"
                  target="_blank"
                  rel="noopener"
                  onClick={closeMenus}
                >
                  <strong>Dispute Resolution</strong>
                  <span className="dd-item-desc">Learn about dispute resolution between First Nations and the Province.</span>
                </a>
              </div>
            </li>
            <li className="nav-item">
              <Link className="nav-link" to="/contact" title="Contact Us" onClick={closeMenus}>
                <span>Contact Us</span>
              </Link>
            </li>
          </ul>
        </div>
      </nav>
      {showBanner && (
        <div className={`env-banner ${bannerColour}`} tabIndex={0}>
          This is the&nbsp;<strong>{envName}</strong>&nbsp;environment. The content you are viewing is not final and
          subject to change.
        </div>
      )}
    </header>
  );
}
