// src/app/projects/projlist-filters/projlist-filters.component.ts
import { Component, OnInit, OnDestroy, ElementRef, signal, ChangeDetectionStrategy, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';
import { DateTime } from 'luxon';
import { CustomMultiSelectComponent } from '../../shared/components/custom-multi-select/custom-multi-select.component';

import { Constants } from '../../shared/utils/constants';
import { ConfigService } from '../../services/config.service';
import { FilterStateService } from '../../services/filter-state.service';

@Component({
  selector: 'app-projlist-filters',
  templateUrl: './projlist-filters.component.html',
  styleUrls: ['./projlist-filters.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule, FormsModule, CustomMultiSelectComponent],
  standalone: true
})
export class ProjlistFiltersComponent implements OnInit, OnDestroy {
  private configService = inject(ConfigService);
  private filterState = inject(FilterStateService);
  private elementRef = inject(ElementRef);

  readonly minDate = DateTime.fromISO('2018-03-23').toJSDate();
  readonly maxDate = DateTime.now().toJSDate();

  // Metadata for dropdowns
  public projectTypes: Array<any> = [];
  public projectRegions: Array<any> = [];
  public projectPhases: Array<any> = [];

  // UI state
  public showFilters = false;
  public showSearchMobile = signal(false);
  
  // Local filter models bound to template
  public regions = signal<any[]>([]);
  public phases = signal<any[]>([]);
  public types = signal<any[]>([]);
  public applicant = signal<string>('');
  public clFile = signal<string>('');
  public dispId = signal<string>('');
  public publishFrom = signal<Date | null>(null);
  public publishTo = signal<Date | null>(null);

  private destroy$ = new Subject<void>();

  get filterCount(): number {
    const filters = this.filterState.allFilters();
    return filters.regions.length + 
           filters.phases.length + 
           filters.types.length +
           (filters.applicant ? 1 : 0) +
           (filters.clFile ? 1 : 0) +
           (filters.dispId ? 1 : 0) +
           (filters.publishFrom ? 1 : 0) +
           (filters.publishTo ? 1 : 0);
  }

  get clientHeight(): number {
    return this.elementRef.nativeElement.offsetTop + 
      this.elementRef.nativeElement.firstElementChild.firstElementChild.clientHeight;
  }

  public ngOnInit() {
    // Load metadata (regions, phases, types)
    this.configService.lists
      .pipe(
        takeUntil(this.destroy$)
      )
      .subscribe(list => {
        list.forEach((item: any) => {
          switch (item.type) {
            case 'region':
              this.projectRegions.push({ ...item });
              break;
            case 'projectPhase':
              this.projectPhases.push({ ...item });
              break;
          }
        });

        this.projectTypes = Constants.PROJECT_TYPE_COLLECTION;
        
        // Initialize local models from FilterStateService
        this.syncFromService();
      });
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  /**
   * Sync local UI models from FilterStateService
   */
  private syncFromService(): void {
    const filters = this.filterState.allFilters();
    
    // Helper to map IDs to objects, filtering out any not found
    const mapToObjects = <T extends { _id?: string; code?: string }>(ids: string[], collection: T[], key: '_id' | 'code'): T[] => {
      return ids.map(id => collection.find(item => item[key] === id)).filter((item): item is T => !!item);
    };
    
    this.regions.set(mapToObjects(filters.regions, this.projectRegions, '_id'));
    this.phases.set(mapToObjects(filters.phases, this.projectPhases, '_id'));
    this.types.set(mapToObjects(filters.types, this.projectTypes, 'code'));
    
    this.applicant.set(filters.applicant || '');
    this.clFile.set(filters.clFile || '');
    this.dispId.set(filters.dispId || '');
    this.publishFrom.set(filters.publishFrom);
    this.publishTo.set(filters.publishTo);
    
    this.showFilters = this.filterState.hasActiveFilters();
  }

  /**
   * Apply current filter values to FilterStateService
   */
  public applyFilters(): void {
    const applicantValue = this.applicant().trim();
    const clFileValue = this.clFile().trim();
    const dispIdValue = this.dispId().trim();
    
    this.filterState.updateFilters({
      regions: this.regions().map((r: any) => r._id),
      phases: this.phases().map((p: any) => p._id),
      types: this.types().map((t: any) => t.code),
      applicant: applicantValue || null,
      clFile: clFileValue || null,
      dispId: dispIdValue || null,
      publishFrom: this.publishFrom(),
      publishTo: this.publishTo(),
      purpose: null
    });
  }

  /**
   * Clear all filters
   */
  public clearAllFilters(): void {
    this.filterState.clearAll();
    this.syncFromService();
  }

  public clearSearch(): void {
    this.applicant.set('');
    this.applyFilters();
  }

  public toggleFilters(): void {
    this.showFilters = !this.showFilters;
  }

  public toggleSearchMobile(): void {
    this.showSearchMobile.set(!this.showSearchMobile());
  }


}

<div class="app-filters__container d-flex flex-column">
  <button class="mobile-search-toggle" (click)="toggleSearchMobile()" aria-label="Toggle search">
    <i class="material-icons">{{ showSearchMobile() ? 'close' : 'search' }}</i>
  </button>
  <div class="search-container" [class.show-mobile]="showSearchMobile()" id="applist-filters">
    <div class="additional-filters">
      <div class="mobile-header">
        <label class="header-label" for="applicantInput">Search Environmental Assessment Projects</label>
        <button type="button" class="btn-close" (click)="toggleSearchMobile()" aria-label="Close search"></button>
      </div>
      <div class="search-box position-relative">
        <input type="text" class="form-control gtm-filter-applicant" placeholder="Start typing a project name" id="applicantInput"
        [ngModel]="applicant()" 
        (ngModelChange)="applicant.set($event); applyFilters()">
        @if (applicant()) {
          <button type="button" class="btn-clear" (click)="clearSearch()" aria-label="Clear search">
            <i class="material-icons">close</i>
          </button>
        }
      </div>
      <div class="toggle-container">
        <div class="toggle-btn" (click)="toggleFilters()">
          <span>{{ showFilters ? 'Hide' : 'Show' }} Advanced Filters</span>
          <i class="material-icons">{{ showFilters ? 'keyboard_arrow_up' : 'keyboard_arrow_down' }}</i>
        </div>
      </div>
      @if (showFilters) {
        <div class="filters-container">
          <div class="filter-container">
            <label for="type">
              Project Type
            </label>
            <div class="filter-select">
              <app-custom-multi-select
                  id="type"
                  name="type"
                  [multiple]="true"
                  bindLabel="name"
                  placeholder="Type Project Type"
                  [items]="projectTypes"
                  [closeOnSelect]="false"
                  [ngModel]="types()"
                  (ngModelChange)="types.set($event); applyFilters()"
              >
              </app-custom-multi-select>
            </div>
          </div>
          <div class="filter-container">
            <label for="region">
              Region
            </label>
            <div class="filter-select">
              <app-custom-multi-select
                  id="region"
                  name="region"
                  [multiple]="true"
                  bindLabel="name"
                  placeholder="Type Project Region"
                  [items]="projectRegions"
                  [closeOnSelect]="false"
                  [ngModel]="regions()"
                  (ngModelChange)="regions.set($event); applyFilters()"
              >
              </app-custom-multi-select>
            </div>
          </div>
          <div class="filter-container">
            <label for="phase">
              Project Phase
            </label>
            <div class="filter-select">
              <app-custom-multi-select
                  id="phase"
                  name="phase"
                  [multiple]="true"
                  bindLabel="name"
                  [groupBy]="'legislation'"
                  placeholder="Type Project Phase"
                  [items]="projectPhases"
                  [closeOnSelect]="false"
                  [markFirst]="false"
                  [ngModel]="phases()"
                  (ngModelChange)="phases.set($event); applyFilters()"
              >
              </app-custom-multi-select>
            </div>
          </div>
        </div>
      }
    </div>
  </div>
</div>

// src/app/pages/projects/projlist-filters.tsx
import { useMemo, useState } from 'react';
import { CustomMultiSelect, type CustomMultiSelectOption } from 'app/components/filters/custom-multi-select';
import { Constants } from 'app/utils/constants';
import { track } from 'app/analytics/analytics';
import { countFilters, hasActiveFilters, type FilterCriteria } from './filter-state';
import './projlist-filters.css';

interface ProjlistFiltersProps {
  ref?: React.Ref<HTMLDivElement>;
  filters: FilterCriteria;
  updateFilters: (next: Partial<FilterCriteria>) => void;
  regions: CustomMultiSelectOption[];
  phases: CustomMultiSelectOption[];
  showSearchMobile: boolean;
  onToggleSearchMobile: () => void;
}

const PROJECT_TYPES = Constants.PROJECT_TYPE_COLLECTION as CustomMultiSelectOption[];

/** Selected ids back to the option objects the multi-select renders; unknown ids drop out. */
function optionsFor(
  ids: string[],
  collection: CustomMultiSelectOption[],
  key: '_id' | 'code'
): CustomMultiSelectOption[] {
  return ids.map(id => collection.find(item => item[key] === id)).filter((item): item is CustomMultiSelectOption => !!item);
}

export function ProjlistFilters({
  ref,
  filters,
  updateFilters,
  regions,
  phases,
  showSearchMobile,
  onToggleSearchMobile
}: ProjlistFiltersProps) {
  const [showFilters, setShowFilters] = useState(() => hasActiveFilters(filters));
  // Kept locally so typing a space between words survives; only the trimmed value reaches the URL.
  const [applicantInput, setApplicantInput] = useState(filters.applicant ?? '');

  const selectedTypes = useMemo(() => optionsFor(filters.types, PROJECT_TYPES, 'code'), [filters.types]);
  const selectedRegions = useMemo(() => optionsFor(filters.regions, regions, '_id'), [filters.regions, regions]);
  const selectedPhases = useMemo(() => optionsFor(filters.phases, phases, '_id'), [filters.phases, phases]);

  function applyFilters(next: Partial<FilterCriteria>): void {
    const applied = { ...filters, ...next };
    updateFilters(next);
    track('Project Filters Applied', {
      regions_count: applied.regions.length,
      phases_count: applied.phases.length,
      types_count: applied.types.length,
      has_applicant: !!applied.applicant,
      has_cl_file: !!applied.clFile,
      has_disp_id: !!applied.dispId,
      has_date_range: !!(applied.publishFrom || applied.publishTo),
      total_filters: countFilters(applied)
    });
  }

  function toggleFilters(): void {
    setShowFilters(open => {
      track('Project Filters Panel Toggled', { is_open: !open, current_filter_count: countFilters(filters) });
      return !open;
    });
  }

  return (
    <div className="app-filters" ref={ref}>
      <div className="app-filters__container d-flex flex-column">
        <button className="mobile-search-toggle" onClick={onToggleSearchMobile} aria-label="Toggle search">
          <i className="material-icons">{showSearchMobile ? 'close' : 'search'}</i>
        </button>
        <div className={`search-container${showSearchMobile ? ' show-mobile' : ''}`} id="applist-filters">
          <div className="additional-filters">
            <div className="mobile-header">
              <label className="header-label" htmlFor="applicantInput">
                Search Environmental Assessment Projects
              </label>
              <button type="button" className="btn-close" onClick={onToggleSearchMobile} aria-label="Close search"></button>
            </div>
            <div className="search-box position-relative">
              <input
                type="text"
                className="form-control gtm-filter-applicant"
                placeholder="Start typing a project name"
                id="applicantInput"
                value={applicantInput}
                onChange={event => {
                  setApplicantInput(event.target.value);
                  applyFilters({ applicant: event.target.value.trim() || null });
                }}
              />
              {applicantInput && (
                <button
                  type="button"
                  className="btn-clear"
                  onClick={() => {
                    setApplicantInput('');
                    applyFilters({ applicant: null });
                  }}
                  aria-label="Clear search"
                >
                  <i className="material-icons">close</i>
                </button>
              )}
            </div>
            <div className="toggle-container">
              <div
                className="toggle-btn"
                role="button"
                tabIndex={0}
                onClick={toggleFilters}
                onKeyDown={event => {
                  if (event.key === 'Enter' || event.key === ' ') {
                    event.preventDefault();
                    toggleFilters();
                  }
                }}
                aria-expanded={showFilters}
              >
                <span>{showFilters ? 'Hide' : 'Show'} Advanced Filters</span>
                <i className="material-icons">{showFilters ? 'keyboard_arrow_up' : 'keyboard_arrow_down'}</i>
              </div>
            </div>
            {showFilters && (
              <div className="filters-container">
                <div className="filter-container">
                  <label htmlFor="type">Project Type</label>
                  <div className="filter-select">
                    <CustomMultiSelect
                      id="type"
                      bindLabel="name"
                      placeholder="Type Project Type"
                      items={PROJECT_TYPES}
                      selected={selectedTypes}
                      onChange={selected => applyFilters({ types: selected.map(item => item['code']) })}
                    />
                  </div>
                </div>
                <div className="filter-container">
                  <label htmlFor="region">Region</label>
                  <div className="filter-select">
                    <CustomMultiSelect
                      id="region"
                      bindLabel="name"
                      placeholder="Type Project Region"
                      items={regions}
                      selected={selectedRegions}
                      onChange={selected => applyFilters({ regions: selected.map(item => item['_id']) })}
                    />
                  </div>
                </div>
                <div className="filter-container">
                  <label htmlFor="phase">Project Phase</label>
                  <div className="filter-select">
                    <CustomMultiSelect
                      id="phase"
                      bindLabel="name"
                      groupBy="legislation"
                      placeholder="Type Project Phase"
                      items={phases}
                      selected={selectedPhases}
                      onChange={selected => applyFilters({ phases: selected.map(item => item['_id']) })}
                    />
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
