// src/app/components/activity-card.tsx
import { Link, useNavigate } from 'react-router';
import { track } from 'app/analytics/analytics';
import { sanitizeWordHtml } from 'app/utils/word-html-sanitizer';
import { safeHtml } from 'app/utils/safe-html';
import { longDate } from 'app/utils/utils';
import './activity-card.css';

interface ActivityCardProps {
  rowData: any;
  /** Renders the date in its own column, as the table layout does. */
  tableMode?: boolean;
  /** Controls "Project Info" button visibility. */
  showProjectInfo?: boolean;
}

function isSingleDoc(item: any): boolean {
  return item !== '' && item !== null && item !== undefined;
}

export function ActivityCard({ rowData, tableMode = false, showProjectInfo = true }: ActivityCardProps) {
  const navigate = useNavigate();

  function goToCP(activity: any): void {
    track('News Item Clicked', {
      activity_type: activity.type,
      project_id: activity.project?._id,
      project_name: activity.project?.name,
      has_comment_period: !!activity.pcp,
      is_met: activity.pcp?.isMet || false
    });
    if (activity.pcp?.isMet && activity.pcp?.metURL) {
      window.open(activity.pcp.metURL, '_blank');
    } else {
      navigate(`/p/${activity.project._id}/cp/${activity.pcp._id}`);
    }
  }

  return (
    <tr>
      <td className="activity-card col-10" tabIndex={0}>
        <div className="activity-card__meta mb-2">
          {rowData?.project?.name && <div className="activity-card__project-name">{rowData.project.name}</div>}
          {rowData?.notificationName && <div className="activity-card__project-name">{rowData.notificationName}</div>}
          {rowData?.projectNotification?.name && (
            <div className="activity-card__project-name">{rowData.projectNotification.name}</div>
          )}
          <div className="activity-card__headline">{rowData?.headline}</div>
        </div>

        {!tableMode && <small className="d-block text-muted mb-3">{longDate(rowData?.dateAdded)}</small>}

        <div className="mb-3 lh-base" dangerouslySetInnerHTML={safeHtml(sanitizeWordHtml(rowData?.content))}></div>

        <div className="d-flex flex-wrap gap-2">
          {rowData?.type === 'Project Notification News' && (
            <Link className="btn btn-sm btn-outline-primary" to="/project-notifications">
              View Project Notifications Page
            </Link>
          )}
          {showProjectInfo && rowData?.type !== 'Project Notification News' && rowData?.project?._id && (
            <Link
              className="btn btn-sm btn-outline-primary"
              to={`/p/${rowData.project._id}`}
              title={`View more information about ${rowData.project.name}`}
            >
              Project Info
            </Link>
          )}
          {rowData?.pcp && rowData?.type === 'Public Comment Period' && (
            <button className="btn btn-sm btn-outline-primary" onClick={() => goToCP(rowData)}>
              View Engagement
            </button>
          )}
          {isSingleDoc(rowData?.documentUrl) && !rowData?.documentUrl?.includes('docs?folder') && (
            rowData?.notificationName && rowData?.type === 'Project Notification Public Comment Period' ? (
              <a className="btn btn-sm btn-outline-primary" href={rowData.documentUrl} target="_blank" rel="noopener">
                View Project Notification Public Comment Period
              </a>
            ) : !rowData?.notificationName ? (
              <a className="btn btn-sm btn-outline-primary" href={rowData.documentUrl} target="_blank" rel="noopener">
                View Document(s)
              </a>
            ) : null
          )}
        </div>
      </td>

      {tableMode && (
        <td className="col-2 activity-card__date" tabIndex={0}>
          {longDate(rowData?.dateAdded)}
        </td>
      )}
    </tr>
  );
}

// src/app/shared/components/activity-card/activity-card.component.ts
import { Component, EventEmitter, Input, ChangeDetectionStrategy, inject } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

import { TableRowComponent, ITableMessage } from 'app/shared/components/table-template/table-row-component';
import { TableObject } from 'app/shared/components/table-template/table-object';
import { AnalyticsService } from 'app/services/analytics/analytics.service';
import { sanitizeWordHtml } from 'app/shared/utils/word-html-sanitizer';

/**
 * Shared activity card component. Renders a single RecentActivity item in the
 * home page card style (project name → headline → date → content → buttons).
 *
 * Works in two contexts:
 *  - Table rows (lib-table-template): used as TableRowComponent. tableData is set by
 *    TableRowDirective; tableMode is true → renders two <td> cells with date in the
 *    second column. showProjectInfo is read from tableData.data.showProjectInfo.
 *  - Home page standalone: tableData is null → tableMode is false → renders single
 *    <td> with inline date. showProjectInfo uses the @Input binding directly.
 */
@Component({
  selector: 'tr[app-activity-card]',
  templateUrl: './activity-card.component.html',
  styleUrl: './activity-card.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule, RouterModule, DatePipe],
  standalone: true
})
export class ActivityCardComponent implements TableRowComponent {
  private router = inject(Router);
  private sanitizer = inject(DomSanitizer);
  private analytics = inject(AnalyticsService);

  // TableRowComponent interface — set by TableRowDirective in table context
  @Input() rowData: any = null;
  tableData: TableObject = null as any;
  messageOut = new EventEmitter<ITableMessage>();
  messageIn = new EventEmitter<ITableMessage>();

  /** Controls "Project Info" button visibility when used standalone (home page). */
  @Input() showProjectInfo = true;

  /**
   * True when rendered inside lib-table-template (tableData injected by TableRowDirective).
   * False on home page (tableData is null).
   */
  get tableMode(): boolean {
    return this.tableData != null;
  }

  /**
   * Effective showProjectInfo value. In table context, tableData.data.showProjectInfo
   * takes precedence (allows per-table configuration). Falls back to @Input binding.
   */
  get showProjectInfoEffective(): boolean {
    if (this.tableData?.data?.showProjectInfo !== undefined) {
      return this.tableData.data.showProjectInfo;
    }
    return this.showProjectInfo;
  }

  getSafeHtml(content: string): SafeHtml {
    return this.sanitizer.bypassSecurityTrustHtml(sanitizeWordHtml(content));
  }

  goToCP(activity: any): void {
    this.analytics.track('News Item Clicked', {
      activity_type: activity.type,
      project_id: activity.project?._id,
      project_name: activity.project?.name,
      has_comment_period: !!activity.pcp,
      is_met: activity.pcp?.isMet || false
    });
    if (activity.pcp?.isMet && activity.pcp?.metURL) {
      window.open(activity.pcp.metURL, '_blank');
    } else {
      this.router.navigate(['p', activity.project._id, 'cp', activity.pcp._id]);
    }
  }

  isSingleDoc(item: any): boolean {
    return item !== '' && item !== null && item !== undefined;
  }
}

<ng-template #cardContent>
  <div class="activity-card__top-meta d-flex align-items-center gap-2 mb-2">
    @if (activityBadge(); as badge) {
      <span class="badge" [ngClass]="badge.cls">{{ badge.label }}</span>
    }
    @if (!tableMode) {
      <small class="text-muted ms-auto">{{ rowData?.dateAdded | date: 'longDate' }}</small>
    }
  </div>

  <div class="activity-card__meta mb-2">
    @if (rowData?.project?.name) {
      <div class="activity-card__project-name">{{ rowData.project.name }}</div>
    }
    @if (rowData?.notificationName) {
      <div class="activity-card__project-name">{{ rowData.notificationName }}</div>
    }
    @if (rowData?.projectNotification?.name) {
      <div class="activity-card__project-name">{{ rowData.projectNotification.name }}</div>
    }
    <div class="activity-card__headline" [innerHTML]="getSafeHtml(rowData?.headline || '')"></div>
  </div>

  <div class="activity-card__body mb-3 lh-base" [innerHTML]="getSafeHtml(rowData?.content)"></div>

  <div class="activity-card__actions d-flex flex-wrap gap-2">
    @if (rowData?.type === 'Project Notification News') {
      <a class="btn btn-sm btn-outline-primary" [routerLink]="['/project-notifications']">
        View Project Notifications Page
      </a>
    }
    @if (showProjectInfoEffective && rowData?.type !== 'Project Notification News' && rowData?.project?._id) {
      <a class="btn btn-sm btn-outline-primary"
         [routerLink]="['/p', rowData.project._id]"
         [title]="'View more information about ' + rowData.project.name">
        Project Info
      </a>
    }
    @if (rowData?.pcp && rowData?.type === 'Public Comment Period') {
      <button class="btn btn-sm btn-outline-primary" type="button" (click)="goToCP(rowData)">
        View Engagement
      </button>
    }
    @if (isSingleDoc(rowData?.documentUrl)) {
      @if (rowData?.notificationName && rowData?.type === 'Project Notification Public Comment Period') {
        <a class="btn btn-sm btn-outline-primary"
           [href]="getDocUrl(rowData.documentUrl)"
           target="_blank"
           rel="noopener noreferrer">
          View Project Notification Public Comment Period
        </a>
      } @else if (isExternalUrl()) {
        <a class="btn btn-sm btn-outline-primary"
           [href]="getDocUrl(rowData.documentUrl)"
           target="_blank"
           rel="noopener noreferrer">
          View Documents
        </a>
      } @else if (!rowData?.notificationName && hasDocContent()) {
        <button class="btn btn-sm btn-outline-primary" type="button" (click)="toggleDocs()">
          {{ expanded() ? 'Hide Documents' : 'View Documents' }}
        </button>
      }
    }
  </div>

  @if (expanded() && hasDocContent()) {
    <hr class="my-3">
    @if (isFolderDocUrl()) {
      <div class="d-flex align-items-center gap-3 py-2 border-bottom search-doc-row">
        <span class="flex-fill fw-semibold small search-doc-name">All project documents</span>
        <a class="d-flex align-items-center justify-content-center text-primary search-doc-action"
           [href]="'/p/' + rowData.project._id + '/documents'">
          <i class="material-icons md-18" aria-hidden="true">open_in_new</i>
        </a>
      </div>
    } @else {
      <div class="d-none d-md-flex gap-3 px-2 py-1 small fw-semibold rounded-1 mb-2 search-doc-header">
        <span class="flex-fill">Document Name</span>
        <span class="search-doc-action"></span>
      </div>
      <div class="d-flex flex-column flex-md-row align-items-md-center gap-1 gap-md-3 py-2 border-bottom search-doc-row">
        <span class="flex-fill fw-semibold small search-doc-name">{{ docFilename() || 'Document' }}</span>
        <a class="d-flex align-items-center justify-content-center text-primary search-doc-action"
           [href]="'/api/document/' + docId() + '/fetch'"
           target="_blank"
           rel="noopener noreferrer"
           title="Download">
          <i class="material-icons md-18" aria-hidden="true">file_download</i>
        </a>
      </div>
    }
  }
</ng-template>

@if (tableMode) {
  <td class="activity-card col-10" tabindex="0">
    <ng-container [ngTemplateOutlet]="cardContent" />
  </td>
  <td class="col-2 activity-card__date" [class.align-top]="expanded()" tabindex="0">
    {{ rowData?.dateAdded | date: 'longDate' }}
  </td>
} @else {
  <ng-container [ngTemplateOutlet]="cardContent" />
}
