// src/app/comments/comments-table-rows/comments-table-rows.component.ts
import { Component, inject, EventEmitter, AfterViewInit, ElementRef, ChangeDetectorRef, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ApiService } from '../../services/api';
import { TableRowComponent, ITableMessage } from '../../shared/components/table-template/table-row-component';
import { TableObject } from '../../shared/components/table-template/table-object';

@Component({
  selector: 'tr[app-comments-table-rows]',
  imports: [CommonModule],
  templateUrl: './comments-table-rows.component.html',
  styleUrls: ['./comments-table-rows.component.css'],
  standalone: true,
  host: {
    'class': 'border',
    '[style.cursor]': '"default"'
  }
})
export class CommentsTableRowsComponent implements TableRowComponent, AfterViewInit {
  private api = inject(ApiService);
  private elementRef = inject(ElementRef);
  private cdr = inject(ChangeDetectorRef);
  
  rowData: any;
  tableData: any;
  messageOut = new EventEmitter<ITableMessage>();
  messageIn = new EventEmitter<ITableMessage>();
  hasOverflow = signal(false);

  ngAfterViewInit() {
    setTimeout(() => {
      const truncatedP = this.elementRef.nativeElement.querySelector('.comment-truncated');
      if (!truncatedP) return;
      
      // Temporarily disable line-clamp to measure full height
      truncatedP.style.webkitLineClamp = 'unset';
      const fullHeight = truncatedP.scrollHeight;
      truncatedP.style.webkitLineClamp = '';
      
      this.hasOverflow.set(fullHeight > truncatedP.clientHeight);
    }, 0);
  }

  toggle(comment: any) {
    comment.expanded = !comment.expanded;

  }

  openAttachment(file: any) {
    this.api.openDocument(file);
  }
}

<td class="p-3">
  <div class="d-flex justify-content-between mb-3">
    <div>
      <b *ngIf="rowData.author && rowData.Anonymous !== true">
        {{rowData.author}}<span *ngIf="rowData.location">, {{rowData.location}}</span>
      </b>
      <b *ngIf="rowData.author == null || rowData.Anonymous">Anonymous</b>
    </div>
    <div>
      {{(rowData.dateAdded | date:'longDate') || "-"}}
    </div>
  </div>

  <div *ngIf="rowData.comment">
    <p *ngIf="rowData.expanded">{{rowData.comment}}</p>
    <p *ngIf="!rowData.expanded" class="comment-truncated">{{rowData.comment}}</p>
    <button *ngIf="!rowData.expanded && hasOverflow()" class="btn btn-link clickable p-0" (click)="toggle(rowData); $event.stopPropagation()">
      Read More
    </button>
    <button *ngIf="rowData.expanded" class="btn btn-link clickable p-0" (click)="toggle(rowData); $event.stopPropagation()">
      Read Less
    </button>
  </div>

  <div *ngIf="rowData.documents && rowData.documents.length > 0" class="mt-2">
    <div class="attachment clickable" *ngFor="let file of rowData.documents" (click)="openAttachment(file); $event.stopPropagation()">
      <i class="material-icons">attach_file</i>{{file.internalOriginalName}}
    </div>
  </div>
</td>

// src/app/pages/comments/comments-table-rows.tsx
import { useLayoutEffect, useRef, useState } from 'react';
import type { TableRowProps } from 'app/components/table/table-object';
import { openDocument } from 'app/api/api';
import { longDate } from 'app/utils/utils';

export function CommentsTableRow({ rowData }: TableRowProps) {
  const [expanded, setExpanded] = useState(false);
  const [hasOverflow, setHasOverflow] = useState(false);
  const truncatedRef = useRef<HTMLParagraphElement>(null);

  useLayoutEffect(() => {
    const truncated = truncatedRef.current;
    if (!truncated) return;

    // Line clamping hides the overflow, so measure the unclamped height to decide whether a
    // "Read More" button is warranted at all.
    truncated.style.webkitLineClamp = 'unset';
    const fullHeight = truncated.scrollHeight;
    truncated.style.webkitLineClamp = '';

    setHasOverflow(fullHeight > truncated.clientHeight);
  }, []);

  return (
    <tr className="border" style={{ cursor: 'default' }}>
      <td className="p-3">
        <div className="mb-2">
          {rowData.author && rowData.Anonymous !== true && (
            <b>
              {rowData.author}
              {rowData.location && <span>, {rowData.location}</span>}
            </b>
          )}
          {(rowData.author === null || rowData.Anonymous) && <b>Anonymous</b>}
        </div>

        <div className="text-muted mb-3">{longDate(rowData.dateAdded) || '-'}</div>

        {rowData.comment && (
          <div>
            {expanded && <p>{rowData.comment}</p>}
            {!expanded && <p className="comment-truncated" ref={truncatedRef}>{rowData.comment}</p>}
            {!expanded && hasOverflow && (
              <button className="btn btn-link clickable p-0" onClick={event => { setExpanded(true); event.stopPropagation(); }}>
                Read More
              </button>
            )}
            {expanded && (
              <button className="btn btn-link clickable p-0" onClick={event => { setExpanded(false); event.stopPropagation(); }}>
                Read Less
              </button>
            )}
          </div>
        )}

        {rowData.documents && rowData.documents.length > 0 && (
          <div className="mt-2">
            {rowData.documents.map((file: any) => (
              <div
                key={file._id}
                className="attachment clickable"
                role="button"
                tabIndex={0}
                onClick={event => { openDocument(file); event.stopPropagation(); }}
                onKeyDown={event => {
                  if (event.key === 'Enter' || event.key === ' ') {
                    openDocument(file);
                    event.stopPropagation();
                  }
                }}
              >
                <i className="material-icons">attach_file</i>{file.internalOriginalName}
              </div>
            ))}
          </div>
        )}
      </td>
    </tr>
  );
}
