// src/app/comments/comments.component.ts
import { Component, inject, signal, OnDestroy, ChangeDetectorRef, ViewEncapsulation, computed } from '@angular/core';
import { DatePipe } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { DomSanitizer } from '@angular/platform-browser';
import { Subject, from } from 'rxjs';
import { takeUntil, switchMap } from 'rxjs/operators';
import { NgbModal, NgbModalRef } from '@ng-bootstrap/ng-bootstrap';
import { ToastService } from '../services/toast.service';
import { CommentPeriod } from '../models/commentperiod';
import { CommentPeriodService } from '../services/commentperiod.service';
import { ProjectService } from '../services/project.service';
import { CommentService } from '../services/comment.service';
import { AddCommentComponent } from './add-comment/add-comment.component';
import { Project } from '../models/project';
import { DocumentService } from '../services/document.service';
import { ApiService } from '../services/api';
import { LoadingStateService } from '../services/loading-state.service';
import { StorageService } from '../services/storage.service';
import { CommentsTableRowsComponent } from './comments-table-rows/comments-table-rows.component';
import { TableObject } from '../shared/components/table-template/table-object';
import { TableTemplateComponent } from '../shared/components/table-template/table-template.component';
import { LoggingService } from '../services/logging.service';
import { AnalyticsService } from '../services/analytics/analytics.service';

@Component({
  selector: 'app-comments',
  imports: [DatePipe, TableTemplateComponent, AddCommentComponent],
  templateUrl: './comments.component.html',
  styleUrls: ['./comments.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class CommentsComponent implements OnDestroy {
  private toastService = inject(ToastService);
  private route = inject(ActivatedRoute);
  private api = inject(ApiService);
  private commentService = inject(CommentService);
  private commentPeriodService = inject(CommentPeriodService);
  private projectService = inject(ProjectService);
  private documentService = inject(DocumentService);
  private changeDetectionRef = inject(ChangeDetectorRef);
  private modalService = inject(NgbModal);
  private router = inject(Router);
  private loadingState = inject(LoadingStateService);
  private logger = inject(LoggingService);
  private sanitizer = inject(DomSanitizer);
  private analytics = inject(AnalyticsService);
  private storageService = inject(StorageService);

  loading = this.loadingState.getOperationState('comments');
  // True while project or comment period are not yet loaded
  pageLoading = computed(() => !this.project() || !this.commentPeriod());
  commentPeriod = signal<CommentPeriod | null>(null);
  project = signal<Project | null>(null);
  comments = signal<any[]>([]);
  commentPeriodDocs = signal<any[]>([]);
  
  // Sanitized instructions for safe HTML rendering
  sanitizedInstructions = computed(() => {
    const instructions = this.commentPeriod()?.instructions;
    return instructions ? this.sanitizer.bypassSecurityTrustHtml(String(instructions)) : '';
  });
  
  tableData = signal<TableObject>(new TableObject({ component: CommentsTableRowsComponent }));
  commentPeriodHeader = signal('');

  private ngUnsubscribe = new Subject<boolean>();
  private commentPeriodId: string | null = null;
  private ngbModal: NgbModalRef | null = null;

  type = signal<'PROJECT' | 'PROJECT-NOTIFICATION'>('PROJECT');

  constructor() {
    // Initialize table options
    const initialTableData = this.tableData();
    initialTableData.options.showPageCountDisplay = true;
    initialTableData.options.showPagination = true;
    initialTableData.options.showPageSizePicker = true;
    initialTableData.options.showTopControls = true;
    initialTableData.options.showHeader = false;
    initialTableData.options.disableRowHighlight = true;
    initialTableData.currentPage = 1;
    initialTableData.pageSize = 10;
    initialTableData.totalListItems = 0;
    this.tableData.set(initialTableData);

    // Load data from route params (modern pattern - no resolvers)
    this.route.paramMap
      .pipe(takeUntil(this.ngUnsubscribe))
      .subscribe(params => {
        const projId = params.get('projId');
        const commentPeriodId = params.get('commentPeriodId');
        
        if (!projId || !commentPeriodId) {
          this.logger.error('Missing route parameters', 'CommentsComponent', { projId, commentPeriodId });
          this.router.navigate(['/projects']);
          return;
        }

        // Determine if this is a project notification by checking the URL
        const isProjectNotification = this.router.url.includes('/pn/');
        this.type.set(isProjectNotification ? 'PROJECT-NOTIFICATION' : 'PROJECT');

        // Load project data — use StorageService if already loaded (in-page navigation),
        // otherwise fall back to API (direct navigation / bookmark).
        const storedProject = this.storageService.currentProject();
        if (storedProject && storedProject._id === projId && storedProject.name) {
          this.project.set(storedProject);
        } else {
          this.projectService.getById(projId)
            .pipe(takeUntil(this.ngUnsubscribe))
            .subscribe({
              next: (project) => this.project.set(project),
              error: (error) => this.logger.error('Error loading project', 'CommentsComponent', error)
            });
        }

        // Load comment period data
        this.commentPeriodService.getById(commentPeriodId)
          .pipe(takeUntil(this.ngUnsubscribe))
          .subscribe({
            next: (period) => {
              if (!period) {
                this.toastService.show('Comment period not found', '', { duration: 3000, type: 'error' });
                this.router.navigate(['/projects']);
                return;
              }

              this.commentPeriod.set(period);
              this.commentPeriodId = period._id;
              
              if (period.commentPeriodStatus === 'Closed') {
                this.commentPeriodHeader.set('Public Comment Period is Now Closed');
              } else if (period.commentPeriodStatus === 'Pending') {
                this.commentPeriodHeader.set('Public Comment Period is Pending');
              } else if (period.commentPeriodStatus === 'Open') {
                this.commentPeriodHeader.set('Public Comment Period is Now Open');
              }

              if (period.relatedDocuments && period.relatedDocuments.length > 0) {
                this.documentService.getByMultiId(period.relatedDocuments)
                  .pipe(takeUntil(this.ngUnsubscribe))
                  .subscribe(docs => {
                    this.commentPeriodDocs.set(docs);
                    this.changeDetectionRef.detectChanges();
                  });
              }

              this.loadComments();
            },
            error: (error) => {
              this.logger.error('Error loading comment period', 'CommentsComponent', error);
              this.toastService.show('Failed to load comment period', '', { duration: 3000, type: 'error' });
              this.router.navigate(['/projects']);
            }
          });
      });
  }

  private loadComments() {
    if (!this.commentPeriodId) return;

    const currentTableData = this.tableData();
    this.commentService.getByPeriodId(this.commentPeriodId, currentTableData.currentPage, currentTableData.pageSize, true)
      .pipe(
        takeUntil(this.ngUnsubscribe),
        switchMap((res: any) => from(this.enrichWithDocuments(res)))
      )
      .subscribe(({ res, currentComments }) => {
        this.comments.set(currentComments);

        const snapshotTableData = this.tableData();
        const newTableData = new TableObject({ component: CommentsTableRowsComponent });
        newTableData.options = snapshotTableData.options;
        newTableData.currentPage = snapshotTableData.currentPage;
        newTableData.pageSize = snapshotTableData.pageSize;
        newTableData.totalListItems = res.totalCount;
        newTableData.items = currentComments.map((comment: any) => ({ rowData: comment }));

        this.logger.debug(`Loaded ${currentComments.length} comments, totalListItems: ${newTableData.totalListItems}`, 'CommentsComponent');

        this.tableData.set(newTableData);
        this.changeDetectionRef.detectChanges();
      });
  }

  private async enrichWithDocuments(res: any): Promise<{ res: any; currentComments: any[] }> {
    const currentComments = res.currentComments;

    currentComments.forEach((comment: any) => {
      comment.expanded = false;
    });

    const allDocIds: string[] = [];
    const commentDocMap = new Map<string, string[]>();

    currentComments.forEach((comment: any, index: number) => {
      if (comment.documents && comment.documents.length > 0) {
        const docIds = comment.documents.map((doc: any) =>
          typeof doc === 'string' ? doc : (doc._id || doc)
        );
        commentDocMap.set(index.toString(), docIds);
        allDocIds.push(...docIds);
      }
    });

    if (allDocIds.length > 0) {
      try {
        const allDocs = await this.documentService.getByMultiId(allDocIds).toPromise();
        const docMap = new Map<string, any>();
        allDocs?.forEach((doc: any) => {
          if (doc && doc._id) docMap.set(doc._id, doc);
        });

        currentComments.forEach((comment: any, index: number) => {
          const docIds = commentDocMap.get(index.toString());
          if (docIds) {
            comment.documents = docIds.map(id => docMap.get(id)).filter(doc => doc !== undefined);
          }
        });
      } catch (error) {
        this.logger.error('Error loading documents for comments', 'CommentsComponent', error);
        currentComments.forEach((comment: any) => {
          if (comment.documents) comment.documents = [];
        });
      }
    }

    return { res, currentComments };
  }

  onMessageOut(msg: any) {
    // Handle table messages like pagination
    if (msg.label === 'pageNum') {
      this.getPaginatedComments(msg.data);
    } else if (msg.label === 'pageSize') {
      this.onUpdatePageSize(msg.data.value);
    }
  }

  downloadDocument(document: any) {
    this.api.downloadDocument(document)
      .then(() => {
        this.toastService.show('Downloading document', '', { duration: 2000, type: 'info' });
      })
      .catch(() => {
        this.toastService.show('Error opening document! Please try again later', '', { duration: 2000, type: 'error' });
      });
  }

  addComment() {
    if (this.commentPeriodId) {
      // open modal
      this.ngbModal = this.modalService.open(AddCommentComponent, { backdrop: 'static', size: 'lg' });
      // set input parameters
      const modalInstance = this.ngbModal.componentInstance as any;
      modalInstance.currentPeriod = this.commentPeriod();
      modalInstance.project = this.project();
      
      // Store current page for tracking on dismiss
      const currentPage = modalInstance.currentPage?.() || 1;
      
      // check result
      this.ngbModal.result.then(
        value => {
          this.logger.debug('Modal closed with success', 'CommentsComponent', { value });
        },
        reason => {
          this.logger.debug('Modal cancelled', 'CommentsComponent', { reason });
          
          // Track modal dismissal
          const proj = this.project();
          if (proj) {
            this.analytics.track('Comment Modal Dismissed', {
              project_id: proj._id,
              project_name: proj.name,
              comment_period_id: this.commentPeriodId,
              page: currentPage,
              reason: String(reason || 'unknown')
            });
          }
        }
      );
    }
  }

  goBackToProjectDetails() {
    const proj = this.project();
    if (this.type() === 'PROJECT' && proj) {
      this.router.navigate(['/p', proj._id]);
    } else {
      this.router.navigate(['/project-notifications']);
    }
  }

  getPaginatedComments(pageNumber: number) {
    const currentTableData = this.tableData();
    currentTableData.currentPage = pageNumber;
    this.tableData.set(currentTableData);
    this.loadComments();
  }

  onUpdatePageSize(newPageSize: number) {
    const currentTableData = this.tableData();
    currentTableData.pageSize = Number(newPageSize);
    currentTableData.currentPage = 1; // Reset to first page when changing page size
    this.tableData.set(currentTableData);
    this.getPaginatedComments(1);
    this.changeDetectionRef.detectChanges();
  }

  ngOnDestroy() {
    this.ngUnsubscribe.next(true);
    this.ngUnsubscribe.complete();
  }
}

<div class="project">
  <main class="project-info">
    <div class="hero-banner-alt">
      <div class="container">
        <div class="hero-banner__content">

          @if (pageLoading()) {
            <div class="d-flex justify-content-center align-items-center py-5">
              <div class="spinner-border" role="status">
                <span class="visually-hidden">Loading...</span>
              </div>
            </div>
          } @else {

          <h1>{{project()?.name || '-'}}</h1>
        
          @if (commentPeriod() !== null && commentPeriod()?._id) {
            <h2>{{commentPeriodHeader() || '-'}}</h2>
            <h2>{{commentPeriod()!.dateStarted | date:'mediumDate'}} - {{commentPeriod()!.endDateDisplay}}</h2>
            <hr class="comment-period-divider">
            
            <div class="header-section">
              <div>
                <div id="instructions" [innerHTML]="sanitizedInstructions()"></div>
                @if (commentPeriod()!.additionalText) {
                  <p>{{commentPeriod()!.additionalText}}</p>
                }
                @if (commentPeriod()!.informationLabel) {
                  <p>{{commentPeriod()!.informationLabel}}</p>
                }
              </div>

            </div>
          }

          @if (type() === 'PROJECT') {
            <span class="ea-decision">{{project()?.eacDecision?.name || "-"}}</span>
            <div class="basic-info">
              <div>
                <span class="info-label">Proponent</span>
                <p class="value">{{project()?.proponent?.name || "-"}}</p>
              </div>
              <div>
                <span class="info-label">Type</span>
                <p class="value">{{project()?.type || "-"}}</p>
              </div>
              <div>
                <span class="info-label">Sub-type</span>
                <p class="value">{{project()?.sector || "-"}}</p>
              </div>
            </div>
          }

          <!-- Related Documents -->
          @if (commentPeriodDocs() && commentPeriodDocs().length > 0) {
            <div class="mb-3">
              <div class="card-header">Related Documents</div>
              <ul class="doc-list mb-0">
                @for (doc of commentPeriodDocs(); track doc) {
                  <li class="clickable-row" 
                      role="button"
                      tabindex="0"
                      (click)="downloadDocument(doc)"
                      (keydown.enter)="downloadDocument(doc)"
                      (keydown.space)="downloadDocument(doc)">
                    <span class="cell icon">
                      <i class="material-icons">insert_drive_file</i>
                    </span>
                    <span class="cell name" [title]="doc.displayName || ''">
                      {{doc.displayName}}
                    </span>
                  </li>
                }
              </ul>
            </div>
          }

          <!-- Open Houses -->
          @if (commentPeriod() && commentPeriod()!.openHouses && commentPeriod()!.openHouses.length > 0) {
            <div class="mb-3">
              <div class="card border-0">
                <div class="card-header">Open Houses</div>
                <ul class="list-group mb-0">
                  @for (openHouse of commentPeriod()!.openHouses; track openHouse) {
                    <li class="list-group-item">
                      <h6 class="mb-2"><b>Date:</b>&nbsp;{{openHouse.eventDate | date}}</h6>
                      <h6 class="mb-0"><b>Description:</b>&nbsp;{{openHouse.description}}</h6>
                    </li>
                  }
                </ul>
              </div>
            </div>
          }

          <button class="btn btn-sm inverted" (click)="goBackToProjectDetails()" type="button">
            {{type() === 'PROJECT' ? 'Back to Project Details' : 'Back to Project Notifications'}}
          </button>

          } <!-- end @else (pageLoading) -->

        </div>
      </div>
    </div>
  </main>
</div>

<div class="container comments">
  @if (loading()) {
    <div class="d-flex justify-content-center my-5">
      <div class="spinner-border" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>
  } @else {
    @if (commentPeriod() && commentPeriod()!.commentPeriodStatus === 'Open') {
      <div class="mb-3 d-flex justify-content-end">
        <button class="btn btn-warning" (click)="addComment()" type="button">Submit Comment</button>
      </div>
    }
    
    @if (tableData().totalListItems > 0) {
      <div>
        <lib-table-template 
          [data]="tableData()" 
          (messageOut)="onMessageOut($event)">
        </lib-table-template>
      </div>
    }
    @if (tableData().totalListItems < 1) {
      <div>
        There are no comments.
      </div>
    }
  }
</div>

// src/app/pages/comments/comments.tsx
import { useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router';
import { useQuery } from '@tanstack/react-query';
import { downloadDocument, searchKeywords } from 'app/api/api';
import * as commentApi from 'app/api/comment';
import * as commentPeriodApi from 'app/api/commentperiod';
import * as documentApi from 'app/api/document';
import * as projectApi from 'app/api/project';
import { logger } from 'app/config/logging';
import { track } from 'app/analytics/analytics';
import type { Comment } from 'app/models/comment';
import type { Document } from 'app/models/document';
import type { Project } from 'app/models/project';
import { showToast } from 'app/state/toast';
import { TableTemplate } from 'app/components/table/table-template';
import { tableObject, type ITableMessage } from 'app/components/table/table-object';
import { mediumDate } from 'app/utils/utils';
import { safeHtml } from 'app/utils/safe-html';
import { AddComment } from './add-comment';
import { CommentsTableRow } from './comments-table-rows';
import './comments.css';

type CommentsType = 'PROJECT' | 'PROJECT-NOTIFICATION';

const COMMENT_PERIOD_HEADERS: Record<string, string> = {
  Closed: 'Public Comment Period is Now Closed',
  Upcoming: 'Public Comment Period is Upcoming',
  Open: 'Public Comment Period is Now Open',
};

/** Project notifications have no project endpoint, so their name comes out of search. */
async function getNotificationProject(projId: string): Promise<Project | null> {
  try {
    const raw = await searchKeywords(
      '',
      'ProjectNotification',
      [],
      1,
      1,
      '',
      '',
      { _id: projId },
      false,
      null,
      {},
      false,
    );
    const hit = (raw as any)?.[0]?.searchResults?.[0];
    return hit ? ({ name: hit.name } as Project) : null;
  } catch {
    // the notification name is non-critical
    return null;
  }
}

async function loadComments(periodId: string, pageNum: number, pageSize: number) {
  const res = await commentApi.getByPeriodId(periodId, pageNum, pageSize, true);
  const comments: Comment[] = res?.currentComments ?? [];

  // Every comment's attachments come back in one request rather than one request per comment.
  const allDocIds: string[] = [];
  comments.forEach((comment) => {
    if (comment.documents && comment.documents.length > 0) {
      // documents arrive as ids or as objects carrying one
      comment.documents = comment.documents.map((doc: any) =>
        typeof doc === 'string' ? doc : doc._id || doc,
      );
      allDocIds.push(...comment.documents);
    }
  });

  if (allDocIds.length > 0) {
    try {
      const docMap = new Map<string, Document>();
      (await documentApi.getByMultiId(allDocIds)).forEach((doc) => {
        if (doc?._id) docMap.set(doc._id, doc);
      });
      comments.forEach((comment) => {
        if (comment.documents) {
          comment.documents = comment.documents.map((id: string) => docMap.get(id)).filter(Boolean);
        }
      });
    } catch (error) {
      logger.error('Error loading documents for comments', 'Comments', error);
      comments.forEach((comment) => {
        if (comment.documents) comment.documents = [];
      });
    }
  }

  return { totalCount: Number(res?.totalCount ?? 0), comments };
}

export function Comments() {
  const { projId, commentPeriodId } = useParams();
  const { pathname } = useLocation();
  const navigate = useNavigate();
  const isProjectNotificationRoute = pathname.includes('/pn/');

  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [modalOpen, setModalOpen] = useState(false);

  const projectQuery = useQuery({
    queryKey: ['comments-project', projId, isProjectNotificationRoute],
    enabled: !!projId,
    queryFn: async (): Promise<{ project: Project | null; type: CommentsType }> => {
      if (!isProjectNotificationRoute) {
        try {
          const project = await projectApi.getById(projId!);
          if (project) return { project, type: 'PROJECT' };
        } catch (error) {
          logger.error('Error loading project', 'Comments', error);
          return { project: null, type: 'PROJECT' };
        }
        logger.warn(`Project ${projId} not found, trying as ProjectNotification`, 'Comments');
      }
      return { project: await getNotificationProject(projId!), type: 'PROJECT-NOTIFICATION' };
    },
  });

  const periodQuery = useQuery({
    queryKey: ['commentPeriod', commentPeriodId],
    enabled: !!commentPeriodId,
    queryFn: () => commentPeriodApi.getById(commentPeriodId!),
  });

  const commentPeriod = periodQuery.data ?? null;
  const project = projectQuery.data?.project ?? null;
  const type: CommentsType =
    projectQuery.data?.type ?? (isProjectNotificationRoute ? 'PROJECT-NOTIFICATION' : 'PROJECT');

  const docsQuery = useQuery({
    queryKey: ['commentPeriodDocs', commentPeriodId],
    enabled: !!commentPeriod?.relatedDocuments?.length,
    queryFn: () => documentApi.getByMultiId(commentPeriod!.relatedDocuments),
  });

  const commentsQuery = useQuery({
    queryKey: ['comments', commentPeriod?._id, page, pageSize],
    enabled: !!commentPeriod?._id,
    queryFn: () => loadComments(commentPeriod!._id, page, pageSize),
    // Keep the table on screen while the next page loads, matching the Angular page, which only
    // showed the big spinner on the first load.
    placeholderData: (previous) => previous,
  });

  useEffect(() => {
    if (!projId || !commentPeriodId) {
      logger.error('Missing route parameters', 'Comments', { projId, commentPeriodId });
      navigate('/projects');
      return;
    }
    if (periodQuery.isError) {
      logger.error('Error loading comment period', 'Comments', periodQuery.error);
      showToast('Failed to load comment period', { duration: 3000, type: 'error' });
      navigate('/projects');
      return;
    }
    if (periodQuery.isSuccess && !periodQuery.data) {
      showToast('Comment period not found', { duration: 3000, type: 'error' });
      navigate('/projects');
    }
  }, [
    projId,
    commentPeriodId,
    periodQuery.isError,
    periodQuery.isSuccess,
    periodQuery.data,
    periodQuery.error,
    navigate,
  ]);

  const tableData = useMemo(
    () =>
      tableObject({
        tableId: 'comments',
        component: CommentsTableRow,
        options: {
          showPageCountDisplay: true,
          showPagination: true,
          showPageSizePicker: true,
          showTopControls: true,
          showHeader: false,
          disableRowHighlight: true,
        },
        currentPage: page,
        pageSize,
        totalListItems: commentsQuery.data?.totalCount ?? 0,
        items: (commentsQuery.data?.comments ?? []).map((comment) => ({ rowData: comment })),
      }),
    [page, pageSize, commentsQuery.data],
  );

  function onMessageOut(msg: ITableMessage) {
    if (msg.label === 'pageNum') {
      setPage(msg.data);
    } else if (msg.label === 'pageSize') {
      setPageSize(Number(msg.data.value));
      setPage(1);
    }
  }

  function onDownloadDocument(doc: Document) {
    downloadDocument(doc)
      .then(() => showToast('Downloading document', { duration: 2000, type: 'info' }))
      .catch(() =>
        showToast('Error opening document! Please try again later', {
          duration: 2000,
          type: 'error',
        }),
      );
  }

  function goBackToProjectDetails() {
    if (type === 'PROJECT' && project) {
      navigate(`/p/${project._id}`);
    } else {
      navigate('/project-notifications');
    }
  }

  function onModalDismiss(reason: string, modalPage: number) {
    setModalOpen(false);
    logger.debug('Modal cancelled', 'Comments', { reason });
    if (project) {
      track('Comment Modal Dismissed', {
        project_id: project._id,
        project_name: project.name,
        comment_period_id: commentPeriod?._id,
        page: modalPage,
        reason,
      });
    }
  }

  const commentPeriodDocs = docsQuery.data ?? [];
  const commentPeriodHeader = commentPeriod
    ? COMMENT_PERIOD_HEADERS[commentPeriod.commentPeriodStatus] || ''
    : '';
  const pageLoading = !commentPeriod || (type === 'PROJECT' && projectQuery.isPending);

  return (
    <>
      <div className="project">
        <main className="project-info">
          <div className="hero-banner-alt">
            <div className="container">
              <div className="hero-banner__content">
                {pageLoading ? (
                  <div className="d-flex justify-content-center align-items-center py-5">
                    <div className="spinner-border" role="status">
                      <span className="visually-hidden">Loading...</span>
                    </div>
                  </div>
                ) : (
                  <>
                    <h1>{project?.name || '-'}</h1>

                    {commentPeriod._id && (
                      <>
                        <h2>{commentPeriodHeader || '-'}</h2>
                        <h2>
                          {mediumDate(commentPeriod.dateStarted)} -{' '}
                          {commentPeriod.longEndDate.toFormat('MMMM dd @ hh:mm a ZZZZ')}
                        </h2>
                        <hr className="comment-period-divider" />

                        <div className="header-section">
                          <div>
                            <div
                              id="instructions"
                              dangerouslySetInnerHTML={safeHtml(
                                String(commentPeriod.instructions ?? ''),
                              )}
                            ></div>
                            {commentPeriod.additionalText && <p>{commentPeriod.additionalText}</p>}
                            {commentPeriod.informationLabel && (
                              <p>{commentPeriod.informationLabel}</p>
                            )}
                          </div>
                        </div>
                      </>
                    )}

                    {type === 'PROJECT' && (
                      <>
                        <span className="ea-decision">{project?.eacDecision?.name || '-'}</span>
                        <div className="basic-info">
                          <div>
                            <span className="info-label">Proponent</span>
                            <p className="value">{project?.proponent?.name || '-'}</p>
                          </div>
                          <div>
                            <span className="info-label">Type</span>
                            <p className="value">{project?.type || '-'}</p>
                          </div>
                          <div>
                            <span className="info-label">Sub-type</span>
                            <p className="value">{project?.sector || '-'}</p>
                          </div>
                        </div>
                      </>
                    )}

                    {commentPeriodDocs.length > 0 && (
                      <div className="mb-3">
                        <div className="card-header">Related Documents</div>
                        <ul className="doc-list mb-0">
                          {commentPeriodDocs.map((doc) => (
                            <li
                              key={doc._id}
                              className="clickable-row"
                              role="button"
                              tabIndex={0}
                              onClick={() => onDownloadDocument(doc)}
                              onKeyDown={(event) => {
                                if (event.key === 'Enter' || event.key === ' ')
                                  onDownloadDocument(doc);
                              }}
                            >
                              <span className="cell icon">
                                <i className="material-icons">insert_drive_file</i>
                              </span>
                              <span className="cell name" title={doc.displayName || ''}>
                                {doc.displayName}
                              </span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {commentPeriod.openHouses && commentPeriod.openHouses.length > 0 && (
                      <div className="mb-3">
                        <div className="card border-0">
                          <div className="card-header">Open Houses</div>
                          <ul className="list-group mb-0">
                            {commentPeriod.openHouses.map(
                              (openHouse: { eventDate: string; description: string }) => (
                                <li
                                  className="list-group-item"
                                  key={`${openHouse.eventDate}-${openHouse.description}`}
                                >
                                  <h6 className="mb-2">
                                    <b>Date:</b>&nbsp;{mediumDate(openHouse.eventDate)}
                                  </h6>
                                  <h6 className="mb-0">
                                    <b>Description:</b>&nbsp;{openHouse.description}
                                  </h6>
                                </li>
                              ),
                            )}
                          </ul>
                        </div>
                      </div>
                    )}

                    <button
                      className="btn btn-sm inverted"
                      onClick={goBackToProjectDetails}
                      type="button"
                    >
                      {type === 'PROJECT'
                        ? 'Back to Project Details'
                        : 'Back to Project Notifications'}
                    </button>
                  </>
                )}
              </div>
            </div>
          </div>
        </main>
      </div>

      <div className="container comments">
        {commentsQuery.isPending ? (
          <div className="d-flex justify-content-center my-5">
            <div className="spinner-border" role="status">
              <span className="visually-hidden">Loading...</span>
            </div>
          </div>
        ) : (
          <>
            {commentPeriod?.commentPeriodStatus === 'Open' && (
              <div className="mb-3 d-flex justify-content-end">
                <button
                  className="btn btn-warning"
                  onClick={() => commentPeriod._id && setModalOpen(true)}
                  type="button"
                >
                  Submit Comment
                </button>
              </div>
            )}

            {tableData.totalListItems > 0 && (
              <div>
                <TableTemplate data={tableData} onMessage={onMessageOut} />
              </div>
            )}
            {tableData.totalListItems === 0 && <div>There are no comments.</div>}
          </>
        )}
      </div>

      {modalOpen && commentPeriod && (
        <AddComment
          currentPeriod={commentPeriod}
          project={project as Project}
          onDismiss={onModalDismiss}
        />
      )}
    </>
  );
}
