// src/app/project-notifications/project-notification-documents-table-details/project-notification-documents-table-details.component.ts
import { Component, ChangeDetectionStrategy, input, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

import { NewlinesPipe } from '../../shared/pipes/newlines.pipe';

@Component({
  selector: 'app-project-notification-documents-table-details',
  templateUrl: './project-notification-documents-table-details.component.html',
  styleUrls: ['./project-notification-documents-table-details.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule, RouterModule, NewlinesPipe],
  standalone: true
})
export class ProjectNotificationDocumentsTableDetailsComponent {
  rowData = input.required<any>();
  
  decisionText = computed(() => {
    const data = this.rowData();
    const decision = data.decision || '-';
    const dateStr = data.decisionDate?.toString().split('T')[0];
    return dateStr 
      ? `Notification Decision - ${decision} | ${dateStr}`
      : `Notification Decision - ${decision}`;
  });

  getTrigger(project: any): string | null {
    return project && project.trigger ? project.trigger.replace(/,/g, ', ') : null;
  }
}

<div>
  <div class="row mb-3 mt-2" tabindex="0">
    <div class="col-12">
      <h4>{{rowData().name?.toUpperCase() || '-'}}</h4>
    </div>
  </div>
  
  <div class="row mb-4" tabindex="0">
    <div class="col-12">
      <div class="pn-decision">
        @if (rowData().associatedProjectId) {
          <a [routerLink]="['/p', rowData().associatedProjectId]">
            <p class="value">{{ decisionText() }}</p>
          </a>
        } @else {
          <p class="value">{{ decisionText() }}</p>
        }
      </div>
    </div>
  </div>

  <div class="row mb-4" tabindex="0">
    <div class="col-12 pn-info-block">
      <label>Description:</label>
      <p class="value" [innerHTML]="(rowData().description || '-') | newlines"></p>
    </div>
  </div>
  
  <div class="row" tabindex="0">
    <div class="col-sm-12 col-md-4 pn-info-block">
      <label>Type</label>
      <p class="value">{{rowData().type || "-"}}</p>
    </div>
    <div class="col-sm-12 col-md-4 pn-info-block">
      <label>Location</label>
      <p class="value">{{rowData().location || "-"}}</p>
    </div>
    <div class="col-sm-12 col-md-4 pn-info-block">
      <label>Proponent</label>
      <p class="value">{{rowData().proponent || "-"}}</p>
    </div>
    <div class="col-sm-12 col-md-4 pn-info-block">
      <label>Sub-Type</label>
      <p class="value">{{rowData().subType || "-"}}</p>
    </div>
    <div class="col-sm-12 col-md-4 pn-info-block">
      <label>Region</label>
      <p class="value">{{rowData().region || "-"}}</p>
    </div>
    <div class="col-sm-12 col-md-4 pn-info-block">
      <label>Notification Trigger</label>
      <p class="value">{{ getTrigger(rowData()) || '-' }}</p>
    </div>
  </div>
</div>

// src/app/pages/project-notifications/project-notification-documents-table-details.tsx
import { Link } from 'react-router';
import { newlines } from 'app/utils/newlines';
import { safeHtml } from 'app/utils/safe-html';

function decisionText(rowData: any): string {
  const decision = rowData.decision || '-';
  const dateStr = rowData.decisionDate?.toString().split('T')[0];
  return dateStr ? `Notification Decision - ${decision} | ${dateStr}` : `Notification Decision - ${decision}`;
}

function getTrigger(project: any): string | null {
  return project && project.trigger ? project.trigger.replace(/,/g, ', ') : null;
}

export function ProjectNotificationDocumentsTableDetails({ rowData }: { rowData: any }) {
  return (
    <div>
      <div className="row mb-3 mt-2" tabIndex={0}>
        <div className="col-12">
          <h4>{rowData.name?.toUpperCase() || '-'}</h4>
        </div>
      </div>

      <div className="row mb-4" tabIndex={0}>
        <div className="col-12">
          <div className="pn-decision">
            {rowData.associatedProjectId ? (
              <Link to={`/p/${rowData.associatedProjectId}`}>
                <p className="value">{decisionText(rowData)}</p>
              </Link>
            ) : (
              <p className="value">{decisionText(rowData)}</p>
            )}
          </div>
        </div>
      </div>

      <div className="row mb-4" tabIndex={0}>
        <div className="col-12 pn-info-block">
          <span className="info-label">Description:</span>
          <p className="value" dangerouslySetInnerHTML={safeHtml(newlines(rowData.description || '-'))}></p>
        </div>
      </div>

      <div className="row" tabIndex={0}>
        <div className="col-sm-12 col-md-4 pn-info-block">
          <span className="info-label">Type</span>
          <p className="value">{rowData.type || '-'}</p>
        </div>
        <div className="col-sm-12 col-md-4 pn-info-block">
          <span className="info-label">Location</span>
          <p className="value">{rowData.location || '-'}</p>
        </div>
        <div className="col-sm-12 col-md-4 pn-info-block">
          <span className="info-label">Proponent</span>
          <p className="value">{rowData.proponent || '-'}</p>
        </div>
        <div className="col-sm-12 col-md-4 pn-info-block">
          <span className="info-label">Sub-Type</span>
          <p className="value">{rowData.subType || '-'}</p>
        </div>
        <div className="col-sm-12 col-md-4 pn-info-block">
          <span className="info-label">Region</span>
          <p className="value">{rowData.region || '-'}</p>
        </div>
        <div className="col-sm-12 col-md-4 pn-info-block">
          <span className="info-label">Notification Trigger</span>
          <p className="value">{getTrigger(rowData) || '-'}</p>
        </div>
      </div>
    </div>
  );
}
