// src/app/components/table/page-size-picker.tsx
import type { IPageSizePickerOption } from './table-object';

interface PageSizePickerProps {
  isDisabled?: boolean;
  isHidden?: boolean;
  sizeOptions?: IPageSizePickerOption[];
  currentPageSize?: number;
  id?: string;
  onPageSizeChosen: (option: IPageSizePickerOption) => void;
}

export function PageSizePicker({
  isDisabled = false,
  isHidden = false,
  sizeOptions = [],
  currentPageSize,
  id,
  onPageSizeChosen,
}: PageSizePickerProps) {
  return (
    <div className="lib-page-size-display" hidden={isHidden} id={id}>
      {sizeOptions.map((sizeOption) => (
        <button
          key={sizeOption.value}
          className={`btn size-picker-option${sizeOption.value === currentPageSize ? ' current' : ''}`}
          onClick={() => onPageSizeChosen(sizeOption)}
          disabled={isDisabled}
          title={`Show ${sizeOption.value} records per page`}
        >
          {sizeOption.displayText}
        </button>
      ))}
    </div>
  );
}

// src/app/shared/components/page-size-picker/page-size-picker.component.ts
/**
 * Defines a single page size option.
 *
 * @export
 * @interface pageSizePickerOption
 */
export interface IPageSizePickerOption {
  /**
   * Text to display in the UI.
   *
   * @type {string}
   * @memberof pageSizePickerOption
   */
  displayText?: string;
  /**
   * Page size.
   *
   * @type {number}
   * @memberof pageSizePickerOption
   */
  value: number;
}

import { Component, input, output, ChangeDetectionStrategy } from '@angular/core';


@Component({
  selector: 'lib-page-size-picker',
  templateUrl: './page-size-picker.component.html',
  styleUrls: ['./page-size-picker.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [],
  standalone: true
})
export class PageSizePickerComponent {
  isDisabled = input(false);
  isHidden = input(false);
  sizeOptions = input<IPageSizePickerOption[]>([]);
  currentPageSize = input<number>();

  pageSizeChosen = output<IPageSizePickerOption>();

  getTitle(sizeOption: IPageSizePickerOption) {
    return `Show ${sizeOption.value} records per page`;
  }

  sizeOptionChosen(sizeOption: IPageSizePickerOption) {
    this.pageSizeChosen.emit(sizeOption);
  }

  isSizeOptionActive(sizeOption: IPageSizePickerOption): boolean {
    return sizeOption.value === this.currentPageSize();
  }
}

<div class="lib-page-size-display" [hidden]="isHidden()">
  @for (sizeOption of sizeOptions(); track sizeOption.value) {
    <button 
      [class.current]="isSizeOptionActive(sizeOption)"
      class="btn size-picker-option"
      (click)="sizeOptionChosen(sizeOption)"
      [disabled]="isDisabled()"
      [title]="getTitle(sizeOption)">
      {{ sizeOption.displayText }}
    </button>
  }
</div>
