// src/app/pages/project-notifications/project-notification-documents-table-rows.tsx
import type { TableRowProps } from 'app/components/table/table-object';
import { idToListName, longDate, openDocumentDownload } from 'app/utils/utils';

export function ProjectNotificationDocumentsTableRow({ rowData, tableData }: TableRowProps) {
  const background = tableData.data?.rowBackgroundColor || '#F7F8FA';
  const goToItem = () => openDocumentDownload(rowData);

  return (
    <tr
      tabIndex={0}
      onKeyUp={event => {
        if (event.key === 'Enter') goToItem();
      }}
    >
      <td data-label="Document Name" onClick={goToItem} style={{ backgroundColor: background }}>
        {rowData.displayName}
      </td>
      <td data-label="Date" onClick={goToItem} style={{ backgroundColor: background }}>
        {longDate(rowData.datePosted)}
      </td>
      <td data-label="Document Author" onClick={goToItem} style={{ backgroundColor: background }}>
        {idToListName(rowData.documentAuthor, tableData.data?.lists ?? [])}
      </td>
    </tr>
  );
}

// src/app/project-notifications/project-notification-documents-table-rows/project-notification-documents-table-rows.component.ts
import { Component, DestroyRef, ChangeDetectionStrategy, inject, signal, output } from '@angular/core';
import { Subject } from 'rxjs';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { DatePipe } from '@angular/common';

import { ConfigService } from '../../services/config.service';
import { TableRowComponent, ITableMessage } from '../../shared/components/table-template/table-row-component';
import { TableObject } from '../../shared/components/table-template/table-object';
import { Utils } from '../../shared/utils/utils';

@Component({
  selector: 'app-project-notification-documents-table-rows',
  templateUrl: './project-notification-documents-table-rows.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [DatePipe],
  host: {
    '(keyup.enter)': 'goToItem(rowData)',
    'tabindex': '0'
  }
})
export class ProjectNotificationDocumentsTableRowsComponent implements TableRowComponent {
  rowData: any;
  tableData!: TableObject;
  messageOut = output<ITableMessage>();
  messageIn = new Subject<ITableMessage>();

  private readonly configService = inject(ConfigService);
  private readonly utils = inject(Utils);
  private readonly destroyRef = inject(DestroyRef);

  private readonly lists = signal<any[]>([]);

  constructor() {
    this.configService.lists
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((list) => this.lists.set(list));
  }

  idToList(id: string) {
    return this.utils.idToListName(id, this.lists());
  }

  goToItem(item: any) {
    this.utils.openDocumentDownload(item);
  }
}

<tr>
  <td data-label="Document Name" (click)="goToItem(rowData)" scope="row" [style.background-color]="tableData.data?.rowBackgroundColor || '#F7F8FA'">{{rowData.displayName}}</td>
  <td data-label="Date" (click)="goToItem(rowData)" scope="row" [style.background-color]="tableData.data?.rowBackgroundColor || '#F7F8FA'">{{rowData.datePosted | date:'longDate'}}</td>
  <td data-label="Document Author" (click)="goToItem(rowData)" scope="row" [style.background-color]="tableData.data?.rowBackgroundColor || '#F7F8FA'">{{idToList(rowData.documentAuthor)}}</td>
</tr>
